### ISSUE TITLE
Xrootd 3.3.3-rc1 external

### ISSUE THREAD

**Issue by bbockelm** [cms-sw/cmsdist#105]
(Already started a conversation with David A about this via email, but filing here)

We'd like the Xrootd external updated to 3.3.3-rc1 for the CMSSW_7_0_X series.  This is to allow me to enable the usage of the new Xrootd client from the Xrootd 3.3.X series.

**Comment by ktf** [comment]
@davidlt can you please include this in all the 7_0_X branches? Thanks.

**Comment by bbockelm** [comment]
Hi,

Any updates on this one?

Thanks,

Brian

**Comment by davidlt** [comment]
@bbockelm , I am looking into it. I see that I need to patch xrootd a bit. Hopefully available tomorrow.

**Comment by davidlt** [comment]
@bbockelm , I have added **3.3.3-rc2** version to 1400 IB.

You might wanna follow up with _xrootd_ developers to include at least the following two patches:
- [xrootd-3.3.3-rc1-gcc47.patch](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_0_X/stable/xrootd-3.3.3-rc1-gcc47.patch) // needed for GCC 4.7.0 and all above.
- [xrootd-3.3.3-rc1-rename-macos-to-apple.patch](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_0_X/stable/xrootd-3.3.3-rc1-rename-macos-to-apple.patch) // I thought we already agreed to include this one :/

I will close the issue once IB is ready and if it's not broken.

**Comment by ktf** [comment]
> I will close the issue once IB is ready and if it's not broken.

Can you queue a build job with your pull request branch and test it separately?
Thanks.

**Comment by davidlt** [comment]
Building was already tested on 3 architectures.

**Comment by davidlt** [comment]
@bbockelm , I have reverted back to **3.2.4** for now. I'll keep the issue open.

**Comment by davidlt** [comment]
Closing this until. You can re-open it once we are ready.
