### ISSUE TITLE
Request for update of external tool "FastJet Contrib"

### ISSUE THREAD

**Issue by rappoccio** [cms-sw/cmsdist#1077]
Hi, Folks,

There is a new version of the "fastjet contrib" external tool (1.014) with new items we would like to use in JME. The instructions to add it are : 

cmsrel CMSSW_7_2_0_pre6
cd CMSSW_7_2_0_pre6/src/
cmsenv
wget http://fastjet.hepforge.org/contrib/downloads/fjcontrib-1.014.tar.gz
tar -zxvf fjcontrib-1.014.tar.gz
cd fjcontrib-1.014
setenv FASTJET_BASE `scramv1 tool tag fastjet FASTJET_BASE`
./configure --fastjet-config=$FASTJET_BASE/bin/fastjet-config --prefix=$PWD CXXFLAGS="-I$FASTJET_BASE/include -I$FASTJET_BASE/tools"
make
make check
make install
make fragile-shared
make fragile-shared-install

Cheers,
Sal, Andreas, Nhan, Raffaele, Jim

**Comment by ktf** [comment]
@degano can you look into this? Thanks.

**Comment by rappoccio** [comment]
As per discussions with Chris Jones via email, I will do checks of threading for this PR, please hold off until I do that.

**Comment by ktf** [comment]
Everything should be done now. CMSSW code still needs fixes.
