### ISSUE TITLE
Please synchronise the IB/CMSSW_7_3_X/debug with IB/CMSSW_7_3_X/stable

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#1096]
Hi,
looking at the IBs, the IB/CMSSW_7_3_X/debug branch is failing because it is missing the latest Pythis8 updates.

Can you set up the automatic synchronisation of IB/CMSSW_7_3_X/debug with IB/CMSSW_7_3_X/stable ?

**Comment by ktf** [comment]
@degano can you look into this, please?
