### ISSUE TITLE
Please install the cmssw debug symbols package for the IB/CMSSW_7_3_X/debug IBs

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#1097]
Hi,
would it be possible to install the cms+cmssw-debug+CMSSW_\* package for the CMSSW_7_3_DEBUG_X integration builds ?

.A

**Comment by fwyzard** [comment]
ping ?

**Comment by ktf** [comment]
alex is looking into this right now.

**Comment by ghost** [comment]
It should be installed now via CVMFS.

**Comment by fwyzard** [comment]
Thanks.

.A
