### ISSUE TITLE
Compile git with PERL support

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#110]
Please do no disable perl support when compiling git, as it disables `git add --interactive` and other stuff. Perl is a system requirement for CMSSW installations so you can expect to have it there. This is a showstopper for CMSSW_6_2_0.

**Comment by davidlt** [comment]
_perl_ is part of prerequisites for CMSSW, but _perl_ modules are not. Adding _perl_ support requires:
- `perl(DBI)`
- `perl(Error)`
- `perl(SVN::Client)`
- `perl(SVN::Core)`
- `perl(SVN::Delta)`
- `perl(SVN::Ra)`
- `perl(YAML::Any)`

In addition to that, it would not allow to use these features running SLC5 build on SLC6 as far as I recall.

Modules seems to be not available on Darwin and Linux by default.

After looking into `./git-add--interactive.perl`, it also uses `Git.pm` module internally.

**Comment by ktf** [comment]
As we privately discussed, please have a look if we can avoid depending on those by either dropping the directory or by not building the _git-svn_ helpers.

**Comment by ktf** [comment]
Actually, do not waste time trying to figure this out, just add fake _Provide_ statements to keep _rpm_ happy and let _git-svn_ die on mac.

**Comment by davidlt** [comment]
Solved for `CMSSW_6_2_0` and above.
