### ISSUE TITLE
[73X] Update dcap to match Fedora policy

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmsdist#1175]
Report and details are here: https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3065/1/1/2.html

The dcap we provide is minimal, but is interfering with other utilities (GRID software). We need to provide dcap with same behavior/ABI compatible to the system one.

I already identified the change needed.

This is a working item for myself. It should be done for CMSSW_7_3_0.

**Comment by ktf** [comment]
Any progress on this? Otherwise please close. We should avoid polluting the issue tracker with things we are not sure about yet.

**Comment by davidlt** [comment]
Here I somewhat got lost. This might be classified as "site problem". AFAIK other sides did not have `gfal2-*` tools installed, not to mention used in CMSSW environment. I think, the policy is not to use GRID utilities in CMSSW environment due to possible unknown/possible ABI incompatibility.

Thus, currently I am not planning to touch it. Closing.
