### ISSUE TITLE
Update root 5.34.22 too use root-mirror/root@fa1e37b3aaae266f4871ef9781f88635cf84f060

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#1258]
root-mirror/root@fa1e37b3aaae266f4871ef9781f88635cf84f060

@degano can you take a look at this? Basically it needs a PR for cams/v5.34.22 plus the additional CMSDIST PR. 74x only

**Comment by ghost** [comment]
@ktf done in https://github.com/cms-sw/cmsdist/pull/1279.
