### ISSUE TITLE
make Geant4 MT default for TREADED branch

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1267]
Recently Geant4 10.0p02 built in MT mode was enabled in the THREADED branch.
To run in MT mode a customisation is needed:

 --customise SimG4Core/Application/customiseMultithreadedSim.customiseMultithreadedSim

and '-n Nthreads' option also should be added to build/run commands.

**Comment by ktf** [comment]
Actually I meant having a PR for `CMSSW_7_4_X_THREADED_X` which makes OscarMTProducer the default one.

**Comment by civanch** [comment]
Yes, let us close this issue - it was my misunderstanding.
