### ISSUE TITLE
Updated HF shower libraries for 2012 and 2015

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1272]
New HF shower libraries for 2012 and 2015 have been created to be used with 7_4_0_pre3. These new libraries has better transfer shower shape. They are available at
/afs/cern.ch/user/a/abdullin/public/fixed_HF_SL/HFShowerLibrary_newpmt_noatt_eta4_16en.root
/afs/cern.ch/user/a/abdullin/public/fixed_HF_SL/HFShowerLibrary_oldpmt_noatt_eta4_16en.root

and should be accessible in 
/afs/cern.ch/cms/data/CMSSW/SimG4CMS/Calo/data

names of files should be
HFShowerLibrary_npmt_noatt_eta4_16en_v2.root 
HFShowerLibrary_oldpmt_noatt_eta4_16en_v2.root

to avoid name clash with the old file. Old shower libraries should not be removed.

**Comment by ghost** [comment]
Done in #1277.

**Comment by davidlange6** [comment]
HI Alessandro- 

To finalize the config for 740pre3, could you further make the following changes
 a) remove the "old" libraries from CMSSW
 b) update the v2 libraries to be these:

cmsdev01.cern.ch:/build/dlange/150107/CMSSW_7_4_X_2015-01-07-1000
HFShowerLibrary_npmt_noatt_eta4_16en_v2.root
HFShowerLibrary_oldpmt_noatt_eta4_16en_v2.root

Thanks-
David

**Comment by ghost** [comment]
@davidlange6 okay, I'm on it right now.

**Comment by ghost** [comment]
@davidlange6 done in https://github.com/cms-sw/cmsdist/pull/1284.
