### ISSUE TITLE
Patch of Geant4 for backward propagator

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1285]
A new p4rivate CMS patch is prepared to be applied on top of Geant4 10.0p03. It includes only fixes for backward propagator (Geant4e).  The patch is available via url: http://cern.ch/vnivanch/verification/verification/data/geant4-10.0p03-cms.patch

The patch should be added first to 7_4_DEVEL and 7_4_THREADED branches, after testing will be proposed to 7_4_X.

**Comment by ghost** [comment]
Testing this.

**Comment by ghost** [comment]
Merged in https://github.com/cms-sw/cmsdist/pull/1286 for the branch IB/CMSSW_7_4_X/next which is used by both DEVEL and THREADED.
