### ISSUE TITLE
Move to root 6.2.03

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#1288]
We were discussing about moving the ROOT6 IB to use the last (released) version of root, however @wmtan was suggesting there might be issues. Do we want to go on with this?

@davidlange6

**Comment by wmtan** [comment]
There are definitely issues.  The question is, do we go to 6.2.03 and then fix the issues, or do we fix the issues first?  It would be easier for me if we went to 6.2.03, so I could fix the issues in an IB.
However, one of the issues I noticed breaks edmCheckClassVersion, so I should probably disable that before we go to 6.2.03.  Please let me know what the decision is on 6.2.03.

**Comment by wmtan** [comment]
I just learned at the ROOT6 planning meeting that 6.2.03 has changes from our current tag that may reduce memory consumption on header parsing.   So, my first priority in ROOT6 is to fix the issues that arise from going to 6.2.03.  So, I will look at this today to see what I can easily fix before we move the IB to 6.2.03.

**Comment by ktf** [comment]
Ok. We keep the move on hold then. On a separate note we should have fixed the issue with roofit in today IB.

**Comment by wmtan** [comment]
I tested 6.2.03.  It breaks edmCheckClassversion, but everything else is more or less OK.
Please merge pull request #7227 and then update to 6.2.03.
https://github.com/cms-sw/cmssw/pull/7227

**Comment by davidlt** [comment]
@wmtan,
https://root.cern.ch/gitweb?p=root.git;a=shortlog;h=refs/heads/v6-02-00-patches
Which one to take?
https://root.cern.ch/gitweb?p=root.git;a=commit;h=2e7ec527c98e5edfe38d1a86d302b061a59c065f
or
https://root.cern.ch/gitweb?p=root.git;a=commit;h=716a06ac242ba671433557e7699e92fee7fdc632

**Comment by wmtan** [comment]
https://root.cern.ch/gitweb?p=root.git;a=commit;h=2e7ec527c98e5edfe38d1a86d302b061a59c065f

**Comment by wmtan** [comment]
ping

**Comment by ktf** [comment]
@degano can you please look into this?

**Comment by ghost** [comment]
Done in #1299.
