### ISSUE TITLE
New shower library.

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#1300]
From @davidlange6 

> Could you replace the two v2 shower libraries we integrated a week or two back with these in 74x
> 
> cmsdev01:
> -rw-r--r--. 1 dlange zh 305579356 Jan 20 20:55 /build/dlange/150120/CMSSW_7_4_X_2015-01-20-0200/src/SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root
> -rw-r--r--. 1 dlange zh 190776418 Jan 20 20:54 /build/dlange/150120/CMSSW_7_4_X_2015-01-20-0200/src/SimG4CMS/Calo/data/HFShowerLibrary_oldpmt_noatt_eta4_16en_v3.root
> 
> You will need #7290 to keep CMSSW workflows working.

@degano can you take care of it?

**Comment by ktf** [comment]
Is this fixed? Can you close it?

**Comment by ghost** [comment]
Yes, fixed in https://github.com/cms-sw/cmsdist/pull/1302 and https://github.com/cms-sw/cmssw/pull/7290. Closing this one.
