### ISSUE TITLE
Data files for Exotica MC production

### ISSUE THREAD

**Issue by davidsheffield** [cms-sw/cmsdist#1319]
We need data files available in Configuration/Generator/data/ for the MC requests EXO-RunIIFall14GS-00268 ---> EXO-RunIIFall14GS-00371. This was discussion on the hypernews thread  https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/1420.html and the pull request https://github.com/cms-sw/cmssw/pull/6991. I was told in the hn thread to open an issue here in order to add the files to cms-data.

The new files that we need are in /afs/cern.ch/user/d/dsheffie/public/HSCP/DataFiles/new/. We also need the files in /afs/cern.ch/user/d/dsheffie/public/HSCP/DataFiles/existing/, but they match files already in /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/data-Configuration-Generator/V01-00-00/Configuration/Generator/data/. So I don't believe they need to be added again (please let me know if they need to be).

**Comment by ghost** [comment]
@davidsheffield @davidlange6 I'll prepare a PR.

**Comment by ghost** [comment]
@davidsheffield also, is this targeted to 74X? Or another release?

**Comment by bendavid** [comment]
Needed In both 74x and 71x

**Comment by ghost** [comment]
@davidsheffield @bendavid Hi, I have moved the datafiles in https://github.com/cms-data/Configuration-Generator (old and new ones). And inserted them in 71X here: https://github.com/cms-sw/cmsdist/pull/1322 and 74X here: https://github.com/cms-sw/cmsdist/pull/1321.
They should be both in starting from tonight IBs.
