### ISSUE TITLE
RecoBTag/SoftLepton repository cms-data area

### ISSUE THREAD

**Issue by zucchett** [cms-sw/cmsdist#1329]
Dear administrators,
we kindly ask for the creation of the RecoBTag/SoftLepton repository in the https://github.com/cms-data area to store the TMVA configuration files.

**Comment by ktf** [comment]
@degano can you please take care of it?

**Comment by ghost** [comment]
@ktf I'm on it.

**Comment by ghost** [comment]
@zucchett I created the repository here: https://github.com/cms-data/RecoBTag-SoftLepton.
You can go ahead and make a PR to include new files, I will then take care to include them in cmsdist. Which release is the target anyway?

**Comment by zucchett** [comment]
Thanks! The target is the last open prerelease CMSSW_7_4_0_pre7.

**Comment by ghost** [comment]
I will close this issue.

**Comment by zucchett** [comment]
Dear Administrators, sorry for coming back on a closed issue, but it seems that it is not possible to fork empty repositories. How can we proceed? Can I send one file to the release manager to bybass the problem?

**Comment by ghost** [comment]
@zucchett yes, do that or even the whole files, as it best suits you.

**Comment by zucchett** [comment]
Thanks @degano, here is the link to the compressed file we need to put into the RecoBTag/SoftLepton repository:
http://www.pd.infn.it/~zucchett/SMT/SoftPFMuon_BDT.weights.xml.gz

**Comment by ghost** [comment]
@zucchett, I put the file in the cms-data repository and created/merged the PR to include the data in 74X here: #1333.
It will be available from this afternoon IB.
