### ISSUE TITLE
Updated cms-data/RecoBTag-SoftLepton

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmsdist#1349]
Dear release managers,

Just pointing you to https://github.com/cms-data/RecoBTag-SoftLepton/pull/1 We would like this included in CMSSW_7_4_0_pre7.

Thanks,
Dinko (for the BTV POG)

**Comment by ghost** [comment]
Done in https://github.com/cms-sw/cmsdist/pull/1351.
