### ISSUE TITLE
Move Geant4 10.00.p03-mpjdmj to 7_5_X

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1359]
A private CMS patch was prepared to be applied on top of Geant4 10.0p03 and validated in the 7_4_DEVEL and 7_4_THREADED branches. Now Geant4 10.00.p03-mpjdmj can be tested by RelVals on top of 7_4_0pre7, for that a special build should be created.

**Comment by davidlange6** [comment]
this is not for 74x itself. if we don't have too much to do after pre7, we can consider it (requesting its validation would be very low  in my priority list in any case)

**Comment by civanch** [comment]
This migration  allowing to use Geant4e backward propagator. Geant4 10.00.p03-mpjdmj was built in MT mode, it is possible to run sequentially using this build (private tests shows that it is working) or build sequentially. I would try out MT mode.

**Comment by davidlange6** [comment]
Sure - but 740pre7 is not the time:)

is there a patch that is purely adding new code for the Geant4e (or just touching that part of Geant4 assuming that we do not otherwise use it)?

**Comment by civanch** [comment]
This mpjdmj is exactly the patch for the propagator. The difference 10.00.p03/10.00.p02 is thread safety and not in physics or tracking. It is safer to move from 10.00.p02 to 10.00p03-mpjdmj with the choice to build Geant4 in MT or in sequential mode.

**Comment by civanch** [comment]
As agreed at OPR because private validation was done and do not show problems, it is possible to integrate  10.00p03-mpjdmj into 7_5_X. Further validation can be done using special build on top of some new 7_4_X pre-release.

**Comment by ghost** [comment]
@civanch where can I find the patch or the source?
If you wish you can make a pull request to our external repository for Geant4 on top of the p03 branch:
https://github.com/cms-externals/geant4/tree/cms/4.10.00.p03

**Comment by civanch** [comment]
@degano , is possible to reuse existing 10.00p03-mpjdmj used in THREADED branch? in 7_5_X we do assume to have MT build of Geant4, so we do not need any change of 10.00p03-mpjdmj.

**Comment by ghost** [comment]
@civanch sure, I will take it from there.
Just to be sure, is the one I merged here:
https://github.com/cms-sw/cmsdist/issues/1285 ?

**Comment by civanch** [comment]
@degano , Yes, exactly.

**Comment by ghost** [comment]
@civanch I created the PR here: https://github.com/cms-sw/cmsdist/pull/1398.
