### ISSUE TITLE
Update libpng to 1.6.16

### ISSUE THREAD

**Issue by osschar** [cms-sw/cmsdist#1374]
During cmsShow initialization we're getting an annoying warning from libpng which is apparently a bug in the library and has been fixed in recent releases.
`libpng warning: Interlace handling should be turned on when using png_read_image`
Versions 1.6.9 to 1.6.15 had a potential integer overflow vulnerability so going to 1.6.16 released in December 2014 seems like the best solution.

If possible, this should go into 7_3 and 7_4.

Sourceforge, the source in libpng.spec, seems to be having some trouble with itself right now ...

**Comment by ktf** [comment]
Moving this to #1375, #1376 should take care of this. I cloned it from the github mirror into cms-externals/libpng.

@degano can you try to build it, please?

**Comment by ktf** [comment]
Should be taken care of... Please reopen if not the case.
