### ISSUE TITLE
Bad file relocations on mac

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#1394]
@VinInn gets:

```
Can't open /build1/sw/osx108_amd64_gcc481/external/git/1.8.3.1-cms3/libexec/git-core/git-citool: No such file or directory.
Can't open /build1/sw/osx108_amd64_gcc481/external/git/1.8.3.1-cms3/libexec/git-core/git-gui: No such file or directory.
```

@degano can you check where that comes from? Thanks

**Comment by ghost** [comment]
Done in https://github.com/cms-sw/cmsdist/pull/1397.

**Comment by ktf** [comment]
Why did you remove the relocation of everything on mac, when it was just two files????

**Comment by ghost** [comment]
@ktf I've fixed it in https://github.com/cms-sw/cmsdist/pull/1404
