### ISSUE TITLE
Move to valgrind 3.10.1 in cms-externals

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#1399]
@degano can you please change the valgrind spec (75X) to use:

https://github.com/cms-externals/valgrind/commit/822f91346cb5996f681fcc79a6f0eeec94f4e17c

just mimic what we do for the other stuff. You probably want to drop all the valgrind patches as well.

**Comment by ghost** [comment]
@ktf done in https://github.com/cms-sw/cmsdist/pull/1405.

**Comment by ktf** [comment]
Can you please backport this to 74X as well? Thanks.

**Comment by ghost** [comment]
@ktf done in #1423.
