### ISSUE TITLE
Update boost in 73x

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#1430]
@ktf, @degano @nclopezo 
we are now ready to update boost to 1.57 in CMSSW_7_3_X. Could you have a look at doing that?

**Comment by davidlt** [comment]
:/
That was done 14 days ago: https://github.com/cms-sw/cmsdist/commit/674b99224b3690f9a3a1d7cee7d756dc23d9abdb

**Comment by ktf** [comment]
Was it actually merged?

**Comment by davidlange6** [comment]
Errr - ok then we did two things at once, for better or worse.. Thanks

**Comment by davidlt** [comment]
@ktf yes, https://github.com/cms-sw/cmsdist/pull/1396
