### ISSUE TITLE
New HF SL for 5_3_X re-simulation

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1451]
There is HI request to provide simulation with HF shower library using 5_3_X. To provide this the new HF SL should be added. The file is located at afs:  /afs/cern.ch/user/a/abdullin/public/HF_HI_53X/HFShowerLibrary_oldpmt_noatt_eta4_16en.root

**Comment by ghost** [comment]
@civanch Working on it right now.

**Comment by civanch** [comment]
@degano , after discussion  with David and Salavat it turn out that the library file from 7_1_X should be used in 5_3_X in order to have the same file in legacy and in production releases. So, it is safe to take  HFShowerLibrary_oldpmt_noatt_eta4_16en_v3.root  for 7_X_Y. Also it is reasonable remove old SL file from 5_3_X.

**Comment by ghost** [comment]
@civanch Is the old file: hfshowerlibrary_lhep_140_edm.root ?

**Comment by civanch** [comment]
Yes it is.

**Comment by ghost** [comment]
@civanch I have prepared the PRs for 5_3_X/stable (slc5 even tho we don't build it anymore) and 5_3_X/slc6_amd64_gcc472 (slc6):
https://github.com/cms-sw/cmsdist/pull/1452
https://github.com/cms-sw/cmsdist/pull/1453
Please review them.

**Comment by ghost** [comment]
@civanch I merged both PRs. I am closing this issue.
