### ISSUE TITLE
RecoBTag-SecondaryVertex repository in the cms-data area

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmsdist#1535]
Dear release managers,

I would like to request the creation of the RecoBTag-SecondaryVertex repository in the cms-data area holding the following TMVA training files:
https://dl.dropboxusercontent.com/u/86555433/CMSSW/BoostedDoubleSV_AK08_BDT.weights.xml.gz
https://dl.dropboxusercontent.com/u/86555433/CMSSW/BoostedDoubleSV_CA15_BDT.weights.xml.gz
Once created, can you also please add this repository as an external for the next CMSSW_7_5_0 IB and pre-release.

Thank you.

@cvernier

**Comment by nclopezo** [comment]
Hi @ferencek,
I created the repository: https://github.com/cms-data/RecoBTag-SecondaryVertex and I added it to the 75X IBs here: https://github.com/cms-sw/cmsdist/pull/1536.
