### ISSUE TITLE
Request for RecoEgamma-PhotonIdentification area in cms-data

### ISSUE THREAD

**Issue by lgray** [cms-sw/cmsdist#1538]
Hi, we are going to need a new repository for photon ID criteria.
Please let me know if there is anything I need to do aside from requesting this repository!

**Comment by ghost** [comment]
@lgray I created the repo: https://github.com/cms-data/RecoEgamma-PhotonIdentification.
You can now push the files you wish to host there, I'll then create the spec file for cmsdist.
Which release will include it?

**Comment by lgray** [comment]
We are looking at whatever is the next 74X release.
Same files will be read in for in 74X & 75X.

-L

On Sun, May 10, 2015 at 2:44 PM, Alessandro Degano <notifications@github.com

**Comment by ghost** [comment]
@davidlange6 @lgray Pending your decision on whether adding those lines I created the PR to cmsdist: https://github.com/cms-sw/cmsdist/pull/1539.

**Comment by ghost** [comment]
@lgray I just merged the PR for the 74X branch as well here: https://github.com/cms-sw/cmsdist/pull/1561.
I'm closing this issue.
