### ISSUE TITLE
Add a runtime xml section to protobuf-toolfile.spec

### ISSUE THREAD

**Issue by rovere** [cms-sw/cmsdist#154]
Hey,
would it be possible to add a section like:

```
<runtime name="PATH"    value="$PROTOBUF_BASE/bin"/>
```

to protobuf-toolfile.spec so that, after setting the tool via scram, the protoc executable is automatically found in the PATH?

Thanks,
Marco.

**Comment by davidlt** [comment]
@rovere , sounds valid to me. I'll add it

**Comment by davidlt** [comment]
@rovere , should be done for **0200** IB. Please, provide feedback that it works once IB is available and I will close the issue.

**Comment by rovere** [comment]
I checked, it's ok, thanks!

@davidlt
