### ISSUE TITLE
Request for a newer ipython release

### ISSUE THREAD

**Issue by cbernet** [cms-sw/cmsdist#1540]
Hello, 

Currently, CMSSW comes with a very old version of ipython (0.10).

We use python 2.7. So would it be possible to upgrade to the most recent stable release of ipython that supports python 2.7? As far as I can see, that would be ipython 3.1.
We would need this change for CMSSW 75X and 74X, and most importantly for the latter.  

Many thanks, 

Colin

**Comment by ghost** [comment]
@cbernet please check https://github.com/cms-sw/cmsdist/pull/1543

**Comment by cbernet** [comment]
Hi @degano,

Would it be possible to upgrade ipython to 3.1.0 in 74X as well? This request is related to  https://github.com/cms-sw/cmssw/pull/9544
in which heppy is adapted to run with ipython 3.1.0. 

Btw I noticed a problem with the version of ipython distributed with 74X (e.g. 743): tab completion does not work. For example, doing the following in ipython results in a tab being inserted: 

```
import math
math.<tab>
```

I am hoping that migrating to ipython 3.1.0 solves this problem, which could also be related to a missing readline package. Could you please check that the test above succeeds or provide me with a way of testing that before the integration? 

Cheers!
Colin

**Comment by ghost** [comment]
@cbernet, I created a PR at #1617.
Before merging I'll let you try it following these instructions:
1) Log in cmsdev04.cern.ch
2) Create a your personal folder under /build
3) Setup a local CMSSW workarea for 74X
4) Once inside do:
`scram setup /build/degano/ipython310_for_74X/a/slc6_amd64_gcc491/external/py2-ipython-toolfile/1.0-cms2/etc/scram.d/py2-ipython.xml`
5) Then: `cmsenv`

Now your ipython should point to the version 3.1.0 I built.
Let me know if you have any issue.

**Comment by cbernet** [comment]
Hi Alessandro, 

Thanks for the fast PR and the testing instructions. 
I have verfified that:
- ipython is 3.1.0
- the tab completion problem is solved
- the branch from my PR works: 
  https://github.com/cms-sw/cmssw/pull/9544

Do you think you could include both PRs at the same time? 

Cheers, 

Colin

**Comment by ghost** [comment]
@cbernet I'll manually test the CMSSW PR, +1 it (if everything is ok) then once all the other signatures are there I'll merge both of them together.
