### ISSUE TITLE
HLTrigger-JetMET repository in the cms-data area

### ISSUE THREAD

**Issue by cvernier** [cms-sw/cmsdist#1554]
Dear release managers,

I would like to request the creation of the HLTrigger-JetMET repository in the cms-data area holding the following TMVA training files:
https://github.com/cvernier/cmssw/blob/hlt-mvapuid/HLTrigger/JetMET/data/weights_noPtCat_BDTG_catev1.xml
Once created, can you also please add this repository as an external for the next CMSSW_7_5_0 IB and pre-release.

Thank you.

@kirschen

**Comment by nclopezo** [comment]
Hi @cvernier,
I did it here: https://github.com/cms-sw/cmsdist/pull/1556

**Comment by nclopezo** [comment]
And the new repository is here: https://github.com/cms-data/HLTrigger-JetMET

**Comment by kirschen** [comment]
Perfect, thanks!
