### ISSUE TITLE
Geant4 patch for 7_1_X - fix memory leaks 

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1674]
Geant4 version 10.0p02 is used for production in 7_1_X branch. The proposed patch provides fixes of extra memory used by internal data structure for nuclear levels, run time memory leak in gamma-nuclear generator, and run time memory leak in FTF model.

Overall effect: RSS memory become nearly const after 100 first events.

We do not expect any effect on physics.

The patch is available at url: 
http://vnivanch.web.cern.ch/vnivanch/verification/verificatio/data/geant4-10.p02-csm.patch

**Comment by ghost** [comment]
@civanch Could you please provide said patch by doing a PR to the cms-externals repository for geant4?
You can find it here: https://github.com/cms-externals/geant4/tree/cms/4.10.00.p02 the branch is named cms/4.10.00.p02

**Comment by civanch** [comment]
@degano , @cmsbuild , I have a problem : cannot push to cms-externals:

remote: Permission to cms-externals/geant4.git denied to civanch.
fatal: unable to access 'https://github.com/cms-externals/geant4/': The requested URL returned error: 403

**Comment by davidlange6** [comment]
you need to make a pull request instead (same as for cmssw)

**Comment by ghost** [comment]
@civanch Yes, you need to do a PR and to do so you first need to fork cms-externals/geant4 to your account, push the changes there and then make the PR as usual.
Thank you.

**Comment by ghost** [comment]
Fixed in #1679.
