### ISSUE TITLE
please upgrade latest CMSSW to frontier_client 2.8.12

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#1676]
Please upgrade the latest CMSSW to frontier_client 2.8.12.  It's a very minor change, only replacing an unhelpful "inconsistent result from poll" message that can happen in 2.8.11 on a connect failure with a more helpful "Connection refused" or "Network unreachable".

**Comment by ghost** [comment]
@DrDaveD fixed in #1678.
