### ISSUE TITLE
data dir for RecoBTag-Combined

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmsdist#1718]
Dear administrators,
we kindly ask for the creation of the RecoBTag/Combined repository in the https://github.com/cms-data area to store TMVA training files for the combined b-taggers.
@pvmulder @imarches @acaudron @ferencek

**Comment by slava77** [comment]
@degano and @smuzaffar (in case you are not watching the repository by default)

**Comment by ghost** [comment]
@jpata @slava77 I created the repository here: https://github.com/cms-data/RecoBTag-Combined with a first dummy commit so you can fork it and then create the PR.
At the time of the PR creation please let us know which release cycles would you like your data to be included in.
