### ISSUE TITLE
please add @govoni (new GEN convener) as watcher

### ISSUE THREAD

**Issue by covarell** [cms-sw/cmsdist#1785]

**Comment by ghost** [comment]
@govoni @covarell Please edit yourself the file watchers.yaml in the https://github.com/cms-sw/cms-bot repository and make a PR.

**Comment by covarell** [comment]
Hmmm... I may have misused the term "watcher" then, in fact I am not myself in this list. 
He should be able to approve/reject pull requests.

**Comment by ghost** [comment]
Oh, okay, then it's categories.py. Is it taking your place? If that's the case I can modify the file myself.

**Comment by covarell** [comment]
No! Just add him...

**Comment by ghost** [comment]
Okay, done here: https://github.com/cms-sw/cms-bot/pull/537
