### ISSUE TITLE
cms-data space for RecoBTag/CTagging training files

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cmsdist#1792]
Dear Admins,

I would like to request the creation of a repository RecoBTag/CTagging under the https://github.com/cms-data organization to store the charm tagging training files.

Please let me know, once is done, which format you want the files to be pushed (plain xml, gzipped, or anything else) and which path they will have in the CMSSW build, to set up properly the FileInPath configuration of the modules that read them.

Thanks.

Mauro

**Comment by slava77** [comment]
Hi Mauro,

I thought that the c-tagger training will go to the database.
Is it going to happen or is there some structural problem
that we have to use files?

```
    --slava
```

**Comment by mverzett** [comment]
Hi Slava,

@pvmulder or @imarches can correct me. The CTagging code is made to be moved to the DB in the future, but the idea was to follow the same path as the combined taggers. Have a first working version with an external file, push the new tagger in the release and then work with the DB people to get the payload.

Cheers

Mauro

**Comment by ghost** [comment]
Yes, that's the strategy followed in https://github.com/cms-sw/cmssw/pull/10197

**Comment by ghost** [comment]
@mverzett Dear Mauro,
you can find the newly created repository here: https://github.com/cms-data/RecoBTag-CTagging.
Once your files will be added to that repository and I'll create the CMSDIST relative spec-file the training files will be under RecoBTag/CTagging/data.
You should push them as plain text files.

**Comment by mverzett** [comment]
@degano [PR Done](https://github.com/cms-data/RecoBTag-CTagging/pull/1)! 
Let me know when everything is in place, so I can send the PR for the charm tagging to CMSSW without failing each and every test because the training files are not there :).

**Comment by ghost** [comment]
@mverzett Done here: https://github.com/cms-sw/cmsdist/pull/1795
It should be in today 11 IB: CMSSW_7_6_X_2015-09-04-1100.
