### ISSUE TITLE
Geant4 10.1p02 for 7_6_X

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#1798]
Sorry that do not make PR for this request but it would be more safe if I create an issue.

In 7_6_DEVEL branch Geant4 10.1p02 shows reasonable performance except few tests crash at exit. The fix for the DEVEL branch is provided in PR 11119, for 7_6_X - in PR 11097. 

When IB for the DEVEL branch will be free of Geant4 problems 10.1p02 should be used for 7_6_X.

**Comment by ghost** [comment]
@civanch What is the status of Geant4 in the DEVEL IB? Is it ready to be ported in the Stable branch?

**Comment by davidlt** [comment]
@degano `CMSSW_7_6_DEVEL_X_2015-09-08-1100` IB RelVals were free of GEANT4 crashes. So at least visible issues are gone.

**Comment by davidlt** [comment]
CC @davidlange6 @smuzaffar

**Comment by davidlange6** [comment]
Lets go ahead and update the geant4 in the 76x mainstream. If it can happen today that would be quite helpful

**Comment by ghost** [comment]
@davidlange6 @civanch I've merged it now here: https://github.com/cms-sw/cmsdist/pull/1803
