### ISSUE TITLE
request for boost libraries

### ISSUE THREAD

**Issue by ggovi** [cms-sw/cmsdist#183]
Hi, i'd like to add these two boost libraries as external tools ( related code will be in 7_0_0 )

boost_iostreams
boost_serialization

Thanks

Giacomo

**Comment by apfeiffer1** [comment]
just a small clarification: we only need the tool files, the libraries
themselves are already in the standard boost build available in cmssw.

On Wed, Sep 4, 2013 at 8:55 PM, ggovi notifications@github.com wrote:

>  Hi, i'd like to add these two boost libraries as external tools (
> related code will be in 7_0_0 )
> 
> boost_iostreams
> boost_serialization
> 
> Thanks
> 
> Giacomo
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cms-sw/cmsdist/issues/183
> .

## 

Thanks,
       cheers, andreas

**Comment by davidlt** [comment]
They are available as external tools, but we don't ship toolfile for them. Untested, but you could do something like that:

```
cat > $CMSSW_BASE/config/toolbox/$SCRAM_ARCH/tools/selected/boost_iostreams.xml <<TOOL_END
<tool name="boost_iostreams" version="@TOOL_VERSION@">
  <info url="http://www.boost.org"/>
  <lib name="boost_iostreams"/>
  <use name="boost"/>
  <use name="zlib"/>
  <use name="bz2lib"/>
</tool>
TOOL_END

cat > $CMSSW_BASE/config/toolbox/$SCRAM_ARCH/tools/selected/boost_serialization.xml <<TOOL_END
<tool name="boost_serialization" version="@TOOL_VERSION@">
  <info url="http://www.boost.org"/>
  <lib name="boost_serialization"/>
  <use name="boost"/>
  <use name="zlib"/>
  <use name="bz2lib"/>
</tool>
TOOL_END
```

Then:

```
scram setup boost_serialization
scram setup boost_iostreams
```

Test if works correctly as expected.

**Comment by ggovi** [comment]
Yes it worked. I've replaced "@TOOL_VERSION@" with the current boost version, 1.51.0

Is there any further action to be taken?

Thanks 

Giacomo

**Comment by davidlt** [comment]
@ggovi Liz wants to keep this on hold. I forgot Core Software meeting today, thus I don't know if this was discussed.

**Comment by apfeiffer1** [comment]
OK, thanks for the update !
I'll then bring this up in the DORP on Fri.

**Comment by davidlt** [comment]
Closing. A special branch was prepared and tool files were added.
