### ISSUE TITLE
Add mock to COMP python

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#1872]
Hi @geneguvo or @ticoann ,

Can we add the mock package to the comp python? This is going to be part of unittest in python 3, but we are going to start using it in WMCore.

When I did my own install of this, it required an update to setuptools. So that will likely need to be upgraded as well.

**Comment by ticoann** [comment]
Hi Eric, I will add that (and update the setup tool) It is in my do to list. Maybe Diego will need to fix that anyway, but I will create the initial patch. :smile:

**Comment by geneguvo** [comment]
Yes, I fully agree. I actually had added a note the other day to update setuptools as soon as HG1510 would be over! Please go ahead Seangchan.

**Comment by ericvaandering** [comment]
Thanks guys
