### ISSUE TITLE
Updated BoostedDoubleSV tagger weight files

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmsdist#1922]
Dear release managers,

I would like the updated BoostedDoubleSV tagger weight files (https://github.com/cms-data/RecoBTag-SecondaryVertex/pull/2) to be added to the latest IBs for 74X, 76X, and 80X release cycles.

Thank you,
Dinko

**Comment by ghost** [comment]
@ferencek I've merged it for 80X here: https://github.com/cms-sw/cmsdist/pull/1924.
Once it's in the IB and everything looks fine we can backport it to 74X and 76X. (75X?)

**Comment by ferencek** [comment]
Thanks. Since 75X is closed for new developments and won't be used for rereco of 2015 data, there is no need to backport to it. However, if that makes bookkeeping easier, feel free to backport to it but the newly added files will not be used in that release cycle.

**Comment by ferencek** [comment]
@degano, since I haven't heard of any problem in 80X, has this now also been backported to 74X and 76X IBs?

**Comment by ghost** [comment]
@ferencek done in #1935 and #1936. I'm closing this issue now.

**Comment by ferencek** [comment]
Thanks.
