### ISSUE TITLE
Please backport frontier_client 2.8.14 and pacparser 1.3.5 to older CMSSW release lines

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#1952]
frontier_client 2.8.14 adds IPv6 support.  It has been available for a while now in CMSSW_7_6_x without any problems shown.  I would like to request that this now get backported to older release lines that are expected to be in active use and supported for at least the next year.  I make this request because it seems likely to me that over the next year people will start to want to be using IPv6-only configurations, and not only for the latest CMSSW release line or later.  The earlier we start to have the support built in to CMSSW, the easier it will be when someone is ready to start using it.

**Comment by ghost** [comment]
I've created a PR for every relevant 7*X release here: #1956 #1957 #1958.
@davidlange6 For which of those do we want to include it? All?

**Comment by DrDaveD** [comment]
I am very sorry I had forgotten to say originally that frontier_client 2.8.14 also should be paired with pacparser 1.3.5.  Fortunately you had remembered anyway.

**Comment by ghost** [comment]
I've merged those PR, I'm closing this issue.

**Comment by DrDaveD** [comment]
What about release lines older than CMSSW_7_X_X?  Are none of them going to be in active use and supported for more than a year?

**Comment by davidlange6** [comment]
53x likely will be used a year from now.

**Comment by DrDaveD** [comment]
So shall we/can we reopen this issue to include 53x, or should I create a new issue?

**Comment by smuzaffar** [comment]
@DrDaveD , looks like we need to apply the following patches in order to build it (I guess it was picking up openssl/md5.h from system https://cmssdt.cern.ch/jenkins/job/build-any-ib/15146/console )
- https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_1_X/stable/frontier_client-2.8.5-fix-gcc47.patch
- https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_1_X/stable/frontier_client-2.8.14-include-fix.patch

can these be included in next version?

**Comment by DrDaveD** [comment]
@smuzaffar, sure I can include the 2.8.14-include-fix. patch in the next version.  I don't much like the "export" hack but I'll do something equivalent.  The 2.8.5 patch should be necessary though, unistd.h is already included in test-req.cc higher up.  Are you saying that the include order matters?

**Comment by smuzaffar** [comment]
@DrDaveD , I did not notice that unistd.h us now included. This patch was there for a long time so may be it is not needed any more.

**Comment by DrDaveD** [comment]
Now a problem has been found with 2.8.14, and I am working on a new release.  The problem has shown up at the HLT, where they use proxies at localhost.

**Comment by smuzaffar** [comment]
@DrDaveD , I am closing this issue, please create a new one when needed
