### ISSUE TITLE
Update Hector in 8_0_X cycle

### ISSUE THREAD

**Issue by ghost** [cms-sw/cmsdist#1998]
As from SDT mailing list it's been asked to update Hector to the latest available version here: https://github.com/hectorhep/hector/tree/1_3_4_patch1_cmssw.

**Comment by davidlange6** [comment]
This one we should have a discussion about in the sim meeting. But no problem to test an updated spec file while that happens.

On Nov 26, 2015, at 10:12 PM, Alessandro Degano <notifications@github.com<mailto:notifications@github.com>> wrote:

As from SDT mailing list it's been asked to update Hector to the latest available version here: https://github.com/hectorhep/hector/tree/1_3_4_patch1_cmssw.

**Comment by ghost** [comment]
The PR for testing is in #1999.

**Comment by ghost** [comment]
The former PR was wrong. The new one is #2005.

**Comment by smuzaffar** [comment]
#2005 has been merged, so we can close this issue.
