### ISSUE TITLE
Doxygen 1.8.4 -> 1.8.5

### ISSUE THREAD

**Issue by cmsdoxy** [cms-sw/cmsdist#204]
Please upgrade doxygen in next CMSSW release.
Doxygen source: http://www.stack.nl/~dimitri/doxygen/download.html

**Comment by ktf** [comment]
Why?

**Comment by cmsdoxy** [comment]
Because this version is better than previous.
http://www.stack.nl/~dimitri/doxygen/manual/changelog.html#log_1_8_5

**Comment by ktf** [comment]
I'm sure it is. What is missing from the current version which is required for your work?

Anyways if you do the work and provide a pull request (not david, BTW, which has already plenty of other stuff to do) for it, I'm fine with merging it.

**Comment by cmsdoxy** [comment]
Pull request: https://github.com/cms-sw/cmsdist/pull/206

**Comment by ktf** [comment]
#211 actually.

**Comment by davidlt** [comment]
Closing as #221 is now merged.
