### ISSUE TITLE
python 2.7.6 is quite old

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#2053]
And in fact 2.7.9 has some pretty significant updates. https://www.python.org/downloads/release/python-279/

@geneguvo and @smuzaffar : Can we get DMWM moved over to the latest (2.7.9 or better 2.7.11). Maybe CMSSW needs to do the same?

I think @vkuznet asked the same some time ago

**Comment by Dr15Jones** [comment]
assign core

**Comment by vkuznet** [comment]
Yes, I requested this on webInterface forum for cmsweb build as well, see https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1406.html

**Comment by davidlt** [comment]
GCC 5.3.0 branch for CMSSW contains Python 2.7.11.

**Comment by smuzaffar** [comment]
CMSSW IBs for gcc530 look good, so moving to 2.7.11 should be fine. @davidlt , did you do something special to avoid HTTPS certificate validation which is ON by default now in python >=2.7.9?

**Comment by davidlt** [comment]
Originally I had changes to `das_client.py` on Python 2.7.9+ to restore old behaviour (i.e. disable SSL certificate validation), but then I just fixed OpenSSL to find CERN ROOT CA (and other certificates) on the system, thus it can validate the certificate.

**Comment by smuzaffar** [comment]
@davidlt , please make a PR for IB/CMSSW_8_0_X/next with updated python , openssl?

**Comment by davidlt** [comment]
The DEVEL IBs (since `CMSSW_8_0_DEVEL_X_2016-01-21-2300`) is running with Python 2.7.11.

I can verify that SSL verification works (executed CMSSW on machine without CERN certificates installed and it rejected connection to cmsweb)

**Comment by smuzaffar** [comment]
@ericvaandering , since python 2.7.11 is now available in CMSSW_8_0_DEVEL IBs, is there any way you can test and make sure it works with in computing env?

**Comment by davidlt** [comment]
Technically their are using Python from their COMP repository, not the one in CMSSW.

**Comment by smuzaffar** [comment]
yes but you never know :-)

**Comment by vkuznet** [comment]
Yes, comp build contains own python, i.e. it is independent from CMSSW,
therefore we need to have a separate build with new python.

**Comment by ericvaandering** [comment]
Right. There are two places we use the CMSSW python. With CRAB, when jobs are submitted, parts of the PSet manipulation are down with CMSSW python. And with WMAgent jobs running on worker nodes, again we use the CMSWW python. All the regular comp stuff is totally detached.

**Comment by ericvaandering** [comment]
@geneguvo Diego, can you comment on the DMWM part of this? (I don't really care what CMSSW is doing :-)

**Comment by geneguvo** [comment]
We should definitely seek to move to the latest 2.7.X on the next release cycle for the COMP builds (HG1603). The fact CMSSW already have a working build of it certainly helps (and we should start from there), but we need to carefully validate all our stack on it.

**Comment by ericvaandering** [comment]
Great. Thanks Diego.

**Comment by smuzaffar** [comment]
@davidlt, can you please make a PR (python/openssl) for cmsdist IB/80X/stable

**Comment by davidlt** [comment]
Here it is: https://github.com/cms-sw/cmsdist/pull/2118
