### ISSUE TITLE
Charge tagger weight file

### ISSUE THREAD

**Issue by aboletti** [cms-sw/cmsdist#2055]
Dear release manager,

I would like to create a new repository on cms-data, in order to contain the weight file for the newly developped charge tagger (RecoBTag/ChargeTagging) for the CMSSW release cycle 80X.

The weight file is available in my lxplus public area (/afs/cern.ch/user/a/aboletti/public/RecoBTag/ChargeTagging/data/ChargeBTag_BDT.weights.xml.gz)

Thanks,
Alessio

**Comment by slava77** [comment]
as I commented in https://github.com/cms-sw/cmssw/pull/12952, the new package RecoBTag/ChargeTagging is not very well justified.

**Comment by aboletti** [comment]
tagger migrated to RecoBTag/Combined package. Weight file commited to another repository, no more need for this one.
New pull request: cms-data/RecoBTag-Combined#2
New Issue: cms-sw/cmsdist#2058
