### ISSUE TITLE
FastSim: bug fix : update data file

### ISSUE THREAD

**Issue by lveldere** [cms-sw/cmsdist#2139]
Dear experts

The data file in the path
FastSimulation/TrackingRecHitProducer/data/PixelForwardResolution2014.root

would need to be updated to the file made available here:
/afs/cern.ch/user/a/asady/public/PixelForwardResolution2014.root

Could someone take care of this,
or provide instructions how to proceed with this?

Many thanks

Lukas

@asady1

**Comment by ghost** [comment]
Dear Lukas,
the data for that package is hosted here: https://github.com/cms-data/FastSimulation-TrackingRecHitProducer.
I suggest you to 
1) Fork the repository in your own area
2) Clone locally your repository, replace the file, commit and push to your repository
3) Make a pull request as we usually do to the cms repository.

From there on I'll take care of integrating the file in the latest release cycle.

**Comment by lveldere** [comment]
thanks! I'll take care of this on Wednesday.
