### ISSUE TITLE
Which branch should be used for externals-update in 81X?

### ISSUE THREAD

**Issue by ghellwig** [cms-sw/cmsdist#2229]
Naivly, I would expect it to be IB/CMSSW_8_1_X/stable, but from https://github.com/cms-sw/cms-bot/blob/master/config.map#L1 it seems that I should rather use IB/CMSSW_8_1_X/gcc530 because this line includes PROD_ARCH=1

Could someone please clarify?

Thank you,
Gregor

**Comment by davidlt** [comment]
`IB/CMSSW_8_1_X/gcc530`, CMSSW_8_1_X started with `IB/CMSSW_8_1_X/stable` (aka GCC 4.9.3), but later we changed compiler to GCC 5.3.0 (`IB/CMSSW_8_1_X/gcc530`).

**Comment by davidlt** [comment]
Btw, we still build GCC 4.9.3 builds, thus you can make your changes to `IB/CMSSW_8_1_X/stable` and then they will be merged to needed branches.

**Comment by ghellwig** [comment]
Thanks @davidlt!

Ok, then I'll proceed with 'stable'.
But in general one should use the PROD_ARCH branch, right? Or always 'stable'?

I am asking because of backports in case of bug fixes in the external.

**Comment by davidlt** [comment]
In most cases it will be stable, but probably not always. E.g., if at some point we stop building GCC 4.9.3 for CMSSW_8_1_X, probably stable will not be used any more. This could happen if we decide we need to use features only available starting GCC 5.3.0. You should look for what architectures we are building certain releases and then check config.map.

**Comment by ghellwig** [comment]
Thanks for clarification!
Is there a way how one can deduce which architectures are built without asking every time?
The easiest way coming to my mind is to look at the release notes of the latest release for a given cycle. But if this has been the last release for this release cycle, this guess is wrong.
