### ISSUE TITLE
 Please backport frontier_client 2.8.19 and pacparser 1.3.5 to older CMSSW release lines

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#2230]
frontier_client 2.8.18 and pacparser 1.3.5 is in CMSSW_8_1_0_pre[12] and hasn't seen any problems.  Please start backporting it to older release lines that still expect to see active use for quite a while, as was attempted for version 2.8.14 in issue #1952.

**Comment by DrDaveD** [comment]
A small problem was found with 2.8.18 -- hold the backport a while until 2.8.19 is tested in as requested in issue #2245

**Comment by smuzaffar** [comment]
@DrDaveD , are you happy with 2.8.19? @degano has created a PR #2289 for 80X, let us know if this is good to go in 80X?

We are planing to test 2.8.19 on online machines using CMSSW_8_1_0_pre4/5 and based on your input and tests we can go ahead with its back port to 80X.

**Comment by DrDaveD** [comment]
Yes I am happy with 2.8.19.  Please do go ahead and backport frontier client 2.8.19 and pacparser 1.3.5 to 80X

**Comment by DrDaveD** [comment]
This is now in 8_0_10.  What other older release lines should be considered to be upgraded for IPv6 support?

**Comment by ghost** [comment]
@DrDaveD It really depends if the scope of frontier_client in CMSSW goes beyond the online data processing. Releases of the 7 (or earlier) cycles are nowadays only used for analysis AFAIK.

**Comment by davidlange6** [comment]
yes, frontier is beyond the online - we have an ipv6 discussion Friday, so it will be easier to answer the question after that.

**Comment by DrDaveD** [comment]
I see it was backported to CMSSW_7_1_24.  That was #2337

**Comment by ghost** [comment]
@iahmad-khan what's the status on the various PRs that you have created? Can you merge those working and fixing those that doesn't?

**Comment by iahmad-khan** [comment]
@degano yes , those that have succeeded can be merged and the one that fails in addons can also be merged for the same reasons as that of 7_1_X has been merged but i am not sure whether should i do it or not(in case of 5_3_X)

**Comment by iahmad-khan** [comment]
Fixed in https://github.com/cms-sw/cmsdist/pull/2337 , https://github.com/cms-sw/cmsdist/pull/2338 , https://github.com/cms-sw/cmsdist/pull/2340
