### ISSUE TITLE
cms-externals/UTM

### ISSUE THREAD

**Issue by tmatsush** [cms-sw/cmsdist#2419]
@davidlange6 @smuzaffar @rekovic @mulhearn

Request of UTM external library update as originally posted in the following issue
https://github.com/cms-l1t-offline/cmssw/issues/368

For 80X, please use the tag r46131-xsd310-patch at https://gitlab.cern.ch/cms-l1t-utm/utm
For 81X, please use the tag r46131-xsd330-patch at https://gitlab.cern.ch/cms-l1t-utm/utm

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please take care of it as soon as possible. We need to get it in for next 8.0.16 release

**Comment by davidlange6** [comment]
just for the record, its done in 81x

On Jul 27, 2016, at 10:20 AM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:

@iahmad-khanhttps://github.com/iahmad-khan , can you please take care of it as soon as possible. We need to get it in for next 8.0.16 release

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals
Done here
80X: https://github.com/cms-sw/cmsdist/pull/2421
81X: https://github.com/cms-sw/cmsdist/commit/89c2bd36feee24c7f47c8845d034208e0f927a2e
