### ISSUE TITLE
Updated BoostedDoubleSV tagger weight files (80X and 81X)

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmsdist#2440]
Dear release managers,

I would like updated BoostedDoubleSV tagger weight files (https://github.com/cms-data/RecoBTag-SecondaryVertex/pull/3) to be added to the latest IBs for the 80X and 81X release cycles.

Thank you,
Dinko

**Comment by iahmad-khan** [comment]
#2441 #2442
