### ISSUE TITLE
External updates for 81x

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#2527]
Hi @degano @iahmad-khan 

could you make a few small changes
LAPACK to version 3.6.1

and add

HDF5 1.8.17 https://support.hdfgroup.org/HDF5/release/obtain5.html (should not depend on anything except for zlib (and cmake if you use that build method) 

./configure --enable-shared --enable-cxx --with-zlib=/cvmfs/cms-ib.cern.ch/2016-39/slc6_amd64_gcc600/external/zlib/1.2.8-giojec2 --prefix $PWD/../install

(maybe we can add also --disable-static to reduce the size)

h5py 2.6.0 which is the corresponding python package  (https://pypi.python.org/pypi/h5py/2.6.0)

thx

**Comment by ghost** [comment]
@davidlange6 Okay, I'll be looking into it now.
