### ISSUE TITLE
rooted patch for ipv6

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#2567]
Please apply the following patch to our existing Xrootd external:

https://github.com/xrootd/xrootd/commit/f09d2f44e89c9186fca4309898f1e9bb4961e0cb

to 53x, 71x, 74x, 75x, 76x, 80x, 81x releases.

@bbockelm @smuzaffar @iahmad-khan

**Comment by davidlange6** [comment]
@bbockelm - should this patch work in both old and new xrootd versions (or should we try to update all the Xrootd clients we have to 4.4.1 at the same time?

**Comment by bbockelm** [comment]
This should already be in 4.4.x; hence, we only need to patch the older clients.

CMSSW 5.3.x has sufficiently old Xrootd that this patch may not apply

**Comment by iahmad-khan** [comment]
@davidlange6 In 71x, 74x, 75x, 76x  , the xrootd version is 4.04 and older. should i just backport 4.4.1 to all of them or apply the patch to xrootd versions in these ?

**Comment by smuzaffar** [comment]
@iahmad-khan , please make a PR for 76X with xrootd 4.4.1 and run jenkins tests.
what is the xrootd version in other branches?

**Comment by iahmad-khan** [comment]
it is 3.2.5 and 4.0.4 in other brnaches

**Comment by iahmad-khan** [comment]
@bbockelm xrootd 4.4.1 is not compatible with root in 7_4_X and 7_5_X so i tried to apply the patch on xrootd 4.0.4 which is currently used in 7_4_X and 7_5_X. But it results in merge conflicts , can you have a look? what could be the possible resolution of that merge conflict in `src/XrdCl/XrdClXRootDTransport.cc` file.

**Comment by bbockelm** [comment]
Hi,

I'm sorry - what log file (and / or branch/repo) do I need to look at?

Brian

**Comment by smuzaffar** [comment]
@bbockelm , root in CMSSW_7_4_X does not compile with xrootd 4.4.1. see the build error here https://github.com/cms-sw/cmsdist/pull/2577#issuecomment-253441342 
Actual jenkins logs are here https://cmssdt.cern.ch/jenkins/job/cmsdist-test-pr/376/console but they do not have the ROOT build log.

**Comment by smuzaffar** [comment]
@bbockelm , for CMSSW_7_5_X see the error here https://github.com/cms-sw/cmsdist/pull/2578#issuecomment-253468219

This might be fixed if we include https://github.com/cms-sw/cmssw/commit/0805d6c443ac0096c1af904cf5b54b110104eb5e#diff-83bec46ca63469c2b8a12fbf2e74d118 for cmssw

**Comment by davidlange6** [comment]
syncing this thread with github - 

I believe the status is:
76x, 80x, 81x are now done (we need to build a release for 76x with the change)
75x has errors but a proposed solution from @smuzaffar 
53x, 71x, 74x have a xrootd version that is not compatible with the fix.

**Comment by bbockelm** [comment]
What's the Xrootd version in 53x and 71x?  It might be sufficiently old that it's unaffected (no IPv6 support at all!)

What's the effective lifetime of 74x and 75x?  Recall we also have a workaround on the server side (which we'd like to get rid of as soon as reasonably possible...)

**Comment by iahmad-khan** [comment]
xrootd versions in 53x/stable and 71x/stable : 3.2.4

**Comment by bbockelm** [comment]
Yes - those versions have no IPv6 support and hence need no patches.

@davidlange6 - what's the need here for 74x and 75x?

**Comment by smuzaffar** [comment]
can this be closed now?

**Comment by iahmad-khan** [comment]
Should we close this issue now?

**Comment by davidlange6** [comment]
we could reopen it in the context of 53x support in the IPV6 only era.. (which can be not that many years away)
