### ISSUE TITLE
Request of UTM external library update

### ISSUE THREAD

**Issue by tmatsush** [cms-sw/cmsdist#2592]
@davidlange6 @smuzaffar @rekovic @apana 

Request of UTM external library update for Tower Counting algorithm [0]
For 80X, please use the tag r47119-xsd310-patch at https://gitlab.cern.ch/cms-l1t-utm/utm
For 81X, please use the tag r47119-xsd330-patch at https://gitlab.cern.ch/cms-l1t-utm/utm

[0] https://github.com/cms-l1t-offline/cmssw/issues/421

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please take care of this.

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals
81X: https://github.com/cms-sw/cmsdist/pull/2598
80X: https://github.com/cms-sw/cmsdist/pull/2595
