### ISSUE TITLE
 Request for new IB for Geant4 10.0 deployment

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#260]
Would it be possible to create a new IB for deployment of the new Geant4 10.0.

The recent reference version is available via url:
http::/cern.ch/vnivanch/geant4.9.6ref10.tar.gz

possible cmake options to build this version:
cmake -DCMAKE_INSTALL_PREFIX=${G4 build dir} \
       -DGEANT4_USE_GDML=ON \
       -DGEANT4_INSTALL_DATADIR=${pass to G4 data} \
       -DXERCESC_ROOT_DIR=${pass to XERCESC} \
       -DGEANT4_INSTALL_EXAMPLES=OFF \
       -DGEANT4_ENABLE_TESTING=OFF \
       -DGEANT4_USE_SYSTEM_CLHEP=OFF \
       -DBUILD_SHARED_LIBS=ON \
       -DBUILD_STATIC_LIBS=OFF \
       -DGEANT4_BUILD_MULTITHREADED=ON \
       ${G4INSTALL}

It is not needed to change data files and CLHEP version for the time being - current one can be used.

**Comment by davidlt** [comment]
I will prepare one today.

**Comment by davidlt** [comment]
The first attempt is prepared for 1400 GVA time, I will close the ticket once the first IB is available.

**Comment by davidlt** [comment]
The first IB is now available, `CMSSW_7_0_GEANT10_X_2013-11-06-1400`. Closing the ticket.
