### ISSUE TITLE
Please upgrade to frontier_client 2.8.20

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#2625]
Please upgrade the latest CMSSW release line to frontier_client 2.8.20.  If all goes well with that I will request backporting it to other release lines that have 2.8.19.  The new version can be found at http://frontier.cern.ch/dist.  Here are the release notes:
```
v2_8_20 - 3 Nov 2016 (dwd)
  - Fix bug introduced in v2_8_15 that caused a segmentation fault
    when a DNS name lookup of proxies fail.  The fault happened in
    the function frontierHttpClnt_usinglastproxyingroup().
  - When both proxyconfigurl and proxyurl options are used, change the
    priority so that proxies returned from proxyconfigurl are used
    before proxyurls.  It used to be the opposite order.
  - When proxyconfigurl options are used, ignore loadbalance=proxies.
```
This was prompted by crashes observed by CMS during today's network intervention at CERN.

**Comment by smuzaffar** [comment]
I have included it for next DEVEL IB (i.e. today's 23h IB). If this goes fine then we shall include it for standard 81X IBs.

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
@DrDaveD , by the way we have this patch for frontier client build
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_8_1_X/gcc530/frontier_client-2.8.5-fix-gcc47.patch
is there any plans to include it upstream?

**Comment by DrDaveD** [comment]
@smuzaffar, unistd.h has been included in test-req.cc since [January 2, 2014](https://github.com/fermitools/frontier/blame/master/client/test-req.cc#L18)

**Comment by smuzaffar** [comment]
@DrDaveD thanks. I have removed our patch now,

**Comment by smuzaffar** [comment]
@DrDaveD ,  this is now available in 81X IBs.

**Comment by smuzaffar** [comment]
@DrDaveD , would you like to do any tests before request to back port it other release (basically all 53X and above)

**Comment by DrDaveD** [comment]
No thanks, I think it's good to backport.  I had already noticed it in an 81X integration build late last week.

**Comment by DrDaveD** [comment]
@smuzaffar, please let me know of any other github issues you create for backporting this.

**Comment by DrDaveD** [comment]
@smuzaffar, have any other issues been created for the backports?

**Comment by smuzaffar** [comment]
As new version(2.8.20) was not part of any release/pre-release , so is not yet fully tested. Today we have build cmssw 810 and 900_pre1 which contain this version, so if no issues found then we will backport it to earlier release cyclces.

**Comment by davidlange6** [comment]
Hi @smuzaffar - lets go ahead and push back to 81x, 80x, 76x, 75x, 53x. I'd like to have this in the 53x build for ~monday/tuesday.

**Comment by smuzaffar** [comment]
@davidlange6 , sure I will do that

**Comment by smuzaffar** [comment]
backport done here 
80x: #2725 
76x: #2726 
75X: #2727 
53X: #2728

**Comment by smuzaffar** [comment]
+externals
