### ISSUE TITLE
Update fastjet-contrib to 1.025

### ISSUE THREAD

**Issue by mseidel42** [cms-sw/cmsdist#2686]
Hi all,

would it be possible to update fastjet-contrib from 1.020 to 1.025?
It includes some new energy correlations, see arXiv:1609.07483v1

Cheers,
Markus

**Comment by iahmad-khan** [comment]
@intrepid42 the new version 1.25 have some problems with cmssw:

https://github.com/cms-sw/cmsdist/pull/2687#issuecomment-263540927


can you propose changes by making a pull request to either https://github.com/cms-externals/fastjet-contrib/tree/cms/v1.25 or cmssw

**Comment by mseidel42** [comment]
Hm, it seems that the ConstituentSubtractor::use_common_bge_for_rho_and_rhom() disappeared with version > 1.0.0 of that contrib :(

**Comment by smuzaffar** [comment]
@intrepid42 , should we close this issue or can you propose changes for cmssw?

**Comment by davidlange6** [comment]
closing given no response here.

**Comment by mseidel42** [comment]
Hi, I can just remove the call to use_common_bge_for_rho_and_rhom() so that everything compiles but I do not know if it is needed by someone/something.

@rappoccio, as you added the ConstituentSubtraction, could you comment, please?

**Comment by rappoccio** [comment]
If the use_common_bge_for_rho_and_rhom method is gone it can probably just be commented out. Granted, basically no one is really using this anyway. 

We would still need to go through the exercise of ensuring thread safety for the contrib as we've done in the past.
