### ISSUE TITLE
cms-data/RecoEgamma-ElectronIdentification#7 to be propagated to 81X and 80X (port of #2682)

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#2693]
Similar to #2690 we will need the new files in 80X and 81X

@ikrav

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please make cmsdist PRs for 80X and 81X.

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals

**Comment by ikrav** [comment]
Hi, when can we have this PR propagated fully to 80X? I have been waiting for this because it is necessary for this PR to be merged and closed before I can submit all 80X electron IDs to CMSSW.

**Comment by slava77** [comment]
@ikrav 
#2694 #2695 and #2696 were merged before Dec 7, they deliver this data to the 81X and 80X distributions.
Have you checked a release in this time range already and still not see the data files?

**Comment by ikrav** [comment]
I think I can see it now. I guess I was wrong about how to check this. Thanks a lot.
