### ISSUE TITLE
cmsdist writers team

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#2723]
@BrunoCoimbra, @amaltaro , @bbockelm, @h4d4, @nikmagini, @ticoann
You are part of cmsdist writer team https://github.com/orgs/cms-sw/teams/cmsdist-writers and
I would like to clean it up. If all you do is to merge PRs then that can be achieved via cms-bot for selected comp developers for selected comp branches.

Can you please reply here if you have any other use cases? I can leave couple of you as writer for tagging the repository.

**Comment by bbockelm** [comment]
I think my addition to the team was mostly historic - you can probably drop it.

Thanks for cleaning things up!

**Comment by amaltaro** [comment]
and I was going to miss this PR. The only thing I need to do is to merge wmagent PRs. Provided cms-bot can merge PRs with a short delay (<15min), then I'm happy to use it.

BTW, don't we have more CRAB folks with such privileges like Marco and Emilis?

**Comment by nikmagini** [comment]
I'm going to leave CMS soon, so I removed myself. Anyway I just needed merge privileges for PhEDEx agents.

**Comment by ticoann** [comment]
Yes, same as Alan for me.

Thanks,
Seangchan

On Dec 9, 2016, at 8:58 AM, Alan Malta Rodrigues <notifications@github.com<mailto:notifications@github.com>> wrote:


and I was going to miss this PR. The only thing I need to do is to merge wmagent PRs. Provided cms-bot can merge PRs with a short delay (<15min), then I'm happy to use it.

BTW, don't we have more CRAB folks with such privileges like Marco and Emilis?

**Comment by smuzaffar** [comment]
Thanks for your feed back.
@amaltaro , merge time should be less than 1min but in case of issues with jenkins/github it can be higher but in that case just add a comment with either @BrunoCoimbra or @h4d4 or me to the PR and we will merge it.

**Comment by smuzaffar** [comment]
@amaltaro and @ticoann , are there any cmsdist branches where you would like to have merge rights ? I am sure you do not want to have merge rights for IB/CMSSW_* branches.

**Comment by amaltaro** [comment]
@smuzaffar comp_gcc493 should be enough (same for @ticoann ), for now :)

**Comment by sextonkennedy** [comment]
Hi Shahzad,

I would like to remain a writer.  We have still not solved the licensing issue, but I intend to pick it up again in Feb.

Cheers, Liz

On Dec 9, 2016, at 7:55 AM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@BrunoCoimbra<https://github.com/BrunoCoimbra>, @amaltaro<https://github.com/amaltaro> , @bbockelm<https://github.com/bbockelm>, @h4d4<https://github.com/h4d4>, @nikmagini<https://github.com/nikmagini>, @ticoann<https://github.com/ticoann>
You are part of cmsdist writer team https://github.com/orgs/cms-sw/teams/cmsdist-writers and
I would like to clean it up. If all you do is to merge PRs then that can be achieved via cms-bot for selected comp developers for selected comp branches.

Can you please reply here if you have any other use cases? I can leave couple of you as writer for tagging the repository.

**Comment by smuzaffar** [comment]
@sextonkennedy , this issue only concern cmsdist writers. You are owner of the organization so you have full right every where. If you are happy with write access to cmssw only then I am happy to create a cmssw-writer team.

**Comment by smuzaffar** [comment]
@BrunoCoimbra, @amaltaro , @h4d4, @ticoann
If you have any open PR then can you comment on it by typing "ping" on the first line to see if cms-bot recognize your message/command?

**Comment by amaltaro** [comment]
I have no open PR at the moment, but I may create one in a day or two.

**Comment by ticoann** [comment]
Hi Shahzad,

“ping” is recognized by cms-bot

https://github.com/cms-sw/cmsdist/pull/2743

Thanks,
Seangchan

On Dec 12, 2016, at 12:15 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@BrunoCoimbra<https://github.com/BrunoCoimbra>, @amaltaro<https://github.com/amaltaro> , @h4d4<https://github.com/h4d4>, @ticoann<https://github.com/ticoann>
If you have any open PR then can you comment on it by typing "ping" on the first line to see if cms-bot recognize your message/command?

**Comment by amaltaro** [comment]
@smuzaffar is it only the PR owner that can communicate with cms-bot and merge the PR?
My ping command failed on the PR created by Seangchan.

**Comment by smuzaffar** [comment]
@amaltaro , github failed to deliver the change to our bot that is why your command was not acknowledged. This is now a usual behaviour and should not happen often (this is the first time I have seen this). In future, if you do not get bot reply in 5 mins then try to comment again.

**Comment by smuzaffar** [comment]
@BrunoCoimbra, @amaltaro ,@h4d4, @ticoann
CMS build bot should now be able to recognize following commands on the first line of your comment
**merge**: To merge the PR
**close**: To close an open PR/issue
**(re)open**: To re-open a closed PR/issue
**ping**: To re-trigger the bot in case it did not recognize your previous comment (due to infrastructure issues)

Except **ping** command you can prefix all other commands with **please, ** :-)

Please start using these commands and if no issues found then I will cleanup the cmsdist-writer team.

**Comment by amaltaro** [comment]
Thanks a lot, Shahzad! It works like a charm for me.

**Comment by smuzaffar** [comment]
@BrunoCoimbra, @amaltaro , @h4d4, @ticoann
have to tried using these https://github.com/cms-sw/cmsdist/issues/2723#issuecomment-267270012 commands to merge PR? 

If no objections then I would like to cleanup the  https://github.com/orgs/cms-sw/teams/cmsdist-writers team now.

**Comment by amaltaro** [comment]
@smuzaffar not really, I didn't have a chance yet to test the merge command (only the ping one).
If you prefer, from my side, you can clean it up and we can scream in case of problems :-)

**Comment by smuzaffar** [comment]
thanks for the suggestion, I guess that is the only way to force you to use it :-)
Cleanup done, in case of issues you know who to scream at :-)

**Comment by amaltaro** [comment]
Thanks ;)
