### ISSUE TITLE
V4 training for the BoostedDoubleSV tagger (80X)

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmsdist#2793]
Dear release managers,

This is a follow-up to https://github.com/cms-sw/cmsdist/issues/2788 to request the v4 weight file for the BoostedDoubleSV tagger to be propagated to the 80X release cycle following the successful integration in the 90X release cycle (https://github.com/cms-sw/cmssw/pull/17294).

Thank you,
Dinko

**Comment by smuzaffar** [comment]
done #2794
