### ISSUE TITLE
Adding Keras to CMSSW_8_0_X-CMSSW_9_0_X

### ISSUE THREAD

**Issue by lpernie** [cms-sw/cmsdist#2821]
Hello,

I would like to use Keras to perform Deep Neural Network.
Since the pakage is already used by some CMS analysis, and its usage it is spreading, I would like to ask if it is possible to make it available by default in 80X and 90X.

Thanks a lot,
Luca

[1] https://keras.io/

**Comment by davidlange6** [comment]
HI Luca

It was on our todo list already - it looks like it should be straightforward to add to at least 90x. I’ll give it a try and report back once its done.

Cheers-
David

**Comment by lpernie** [comment]
Thanks a lot!

**Comment by davidlange6** [comment]
Hi Luca

Starting from CMSSW_9_0_X_2017-02-12-2300 our 90x integration builds have keras and theano. Both appear to function, but maybe you have a non-trivial example to try? We don’t yet have the tensor flow backend, so you have to change the backend to via the KERAS_BACKEND environment variable or by changing ~/.keras/keras.json after you import keras for the first time (which is when this file is created). We’ll either get tensor flow installed or change the default backend soon, but if you can find other problems in the meanwhile that would be great!

**Comment by lpernie** [comment]
Hello David,
I would like to give it a try, but I never used it before. I  wanted a way to perform a parametrized MVA training (not possible with TMVA). 
Give me few days and I will give it a try and let you know.

**Comment by lpernie** [comment]
I'm in release CMSSW_9_0_X_2017-02-14-1100 and I can tell that the basic tutorial shown on:
http://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/
is working fine.
In my opinion having also tensor flow would be very useful.

**Comment by lpernie** [comment]
Just a comment:
I notice that deepdish package is missing. This is in general quite useful when working with HDF5 format (common with DNN). 
https://pypi.python.org/pypi/deepdish

**Comment by davidlange6** [comment]
Sure - that should not be a problem to add.

**Comment by lpernie** [comment]
Thanks a lot!
Also tqdm[1] could be a useful package to add (not mandatory but useful for complex training)
Anyway the addition of tensorflow is the most important part for now I guess.
Thanks.
[1] https://pypi.python.org/pypi/tqdm

**Comment by davidlange6** [comment]
Hi @lpernie - deepdish should be available (but untested) starting from CMSSW_9_0_X_2017-02-27-1100 builds (and thus likely in CMSSW_9_0_0). 

For Tensorflow- it will only go into the slc7 architecture builds, as it looks like slc6 is just too old for support there. Something is there already, but it looks like I need to upgrade the version of protobuf.

tqdm looks like something easy to add (and its small with no dependencies).  I want to try to get some unit tests implemented on other things first.

**Comment by lpernie** [comment]
Thanks a lot!
About Tensorflow... do this mean it will not be available in CMSSW_9_0_0 or that there will be a special release with slc7 where it could be used?

**Comment by davidlange6** [comment]
Hi Luca
there are slc7 versions of releases routinely made. (the tricker issue is slc7 resources, which do exist but in small numbers, eg, lxplus7.cern.ch)

**Comment by lpernie** [comment]
Thanks a lot for the explanation. So I can test it on CMSSW_9_0_0 release on lxplus7.

**Comment by smuzaffar** [comment]
looks like tensorflow is broken in CMSSW_9_0_X_2017-02-27-1100  IB.
```
ssh lxplus7
cd /tmp/`whoami`
scram p CMSSW_9_0_X_2017-02-27-1100
cd CMSSW_9_0_X_2017-02-27-1100/
cmsenv
python -c 'import tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/cms-ib.cern.ch/nweek-02461/slc7_amd64_gcc530/external/py2-pippkgs_depscipy/3.0/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/cvmfs/cms-ib.cern.ch/nweek-02461/slc7_amd64_gcc530/external/py2-pippkgs_depscipy/3.0/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02461/slc7_amd64_gcc530/external/py2-pippkgs_depscipy/3.0/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/cvmfs/cms-ib.cern.ch/nweek-02461/slc7_amd64_gcc530/external/py2-pippkgs_depscipy/3.0/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/cvmfs/cms-ib.cern.ch/nweek-02461/slc7_amd64_gcc530/external/py2-pippkgs_depscipy/3.0/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /cvmfs/cms-ib.cern.ch/nweek-02461/slc7_amd64_gcc530/external/py2-pippkgs_depscipy/3.0/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_AsUTF8String


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by lpernie** [comment]
Dear All,
there are few tools that match with keras, as hyperas[1]. It allows to optimize the hyperparameters and find the best activation function/dropout/loss definition, saving time when building the NN.
At the moment it could be installed locally, but there is any chances it could be installed globally?
[1] http://maxpumperla.github.io/hyperas/

**Comment by smuzaffar** [comment]
hyperas is now part of cmssw distribution https://github.com/cms-sw/cmsdist/pull/3125
