### ISSUE TITLE
Please wait with updating xrootd to 4.6 until an issue is fixed

### ISSUE THREAD

**Issue by chwissing** [cms-sw/cmsdist#2832]
Hi,

there is present an issue with xrootd version 4.6.0:
  https://github.com/xrootd/xrootd/issues/465
  https://github.com/xrootd/xrootd/issues/463

Until this is fixed, it should not be included into the CMSSW externals. Brian knows about it (according to Marian). Nevertheless let me add this issue here as agreed with DavidL in a private mail exchange.

Christoph

**Comment by davidlt** [comment]
pre-4.6.0 is only part of CMSSW development builds (gcc700, will never be used), nothing in production.

**Comment by davidlange6** [comment]
Hi @bbockelm - you requested us to update to v4.6.1-rc1. Does it address the issues that @chwissing raises?

**Comment by bbockelm** [comment]
Yes, v4.6.1-rc1 addresses both issues.

(But rc2 is released and we should switch to that!)

**Comment by smuzaffar** [comment]
both issue mentioned above have been fixed in 4.6.1.RC2 (https://github.com/xrootd/xrootd/commit/10ba4d7adfc5c66f33bcc77cf38ca45f426cb041) which is in 92X cmssw releases now.
