### ISSUE TITLE
move intel compiler and tools to CVMFS

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#2879]
As just announced, "a CVMFS repository is available for accessing the Intel compilers, libraries and performance tuning tools across CERN".

Would it make sense to update `intel-vtune.xml` to use
`/cvmfs/projects.cern.ch/intelsw/psxe/linux/x86_64/2017/vtune_amplifier_xe_2017.2.0.499904`

and `icc-*compiler.xml` to use 
`/cvmfs/projects.cern.ch/intelsw/psxe/linux/x86_64/2017/compilers_and_libraries_2017.2.174/linux`

?

**Comment by smuzaffar** [comment]
@fwyzard , this is already done via https://github.com/cms-sw/cmsdist/pull/2864

**Comment by fwyzard** [comment]
:+1:
