### ISSUE TITLE
add libraries to CUDA external

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#2934]
compiling some of the CUDA samples with the external coming with CMSSW fails due to missing libraries:
  - libcudadevrt.a
  - libcudart_static.a

They are small enough (~1.3 MB) that we could just add them to our external.

**Comment by smuzaffar** [comment]
assign externals
@iahmad-khan , can you please take care of it. @fwyzard , should this only go in 91X?

**Comment by fwyzard** [comment]
It's OK to do it only for 9.1.x .
I'm going through the samples checking if we miss other core libraries.

**Comment by fwyzard** [comment]
After some more checks, only `libcudadevrt.a` is really needed, while in place of `libcudart_static.a` we can use the shared library we already ship.

**Comment by iahmad-khan** [comment]
updated/fixed in 9.1.X
