### ISSUE TITLE
add DataFormats-PatCandidates in cms-data to hold parameterization root files

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#2947]
related to https://github.com/cms-sw/cmssw/pull/18092

Please populate it also with the latest root files from this cms-sw/cmssw PR
This will be needed in 91X to start with.

**Comment by smuzaffar** [comment]
https://github.com/cms-data/DataFormats-PatCandidates is now available. Please make a PR to add the needed files in it. Files should be added on the top level directory (i.e. without any DataFormats/PatCandidates/data structure)

**Comment by slava77** [comment]
@arizzi

**Comment by arizzi** [comment]
https://github.com/cms-data/DataFormats-PatCandidates/pull/1

**Comment by smuzaffar** [comment]
this is now done via #2949
