### ISSUE TITLE
cms-externals/UTM - indexing and overlap removal

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmsdist#2964]
@davidlange6 @smuzaffar

Request of UTM external library update as originally posted in the following issue
https://github.com/cms-l1t-offline/cmssw/issues/503

For 91X, please use the tag overlapRemoval-xsd330 at https://gitlab.cern.ch/cms-l1t-utm/utm.

**Comment by smuzaffar** [comment]
@mrodozov is taking care of it #2965

**Comment by smuzaffar** [comment]
+externals
