### ISSUE TITLE
Switch 7_0_GEANT4 branch from the candidate Geant4 version to the offitial release 10.0

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#298]
Full migration to the version 10.0 includes updates of CLHEP, data files and source code itself. The patch of cmake/gmake configure options  prepared for previous version of Geant4 (pull request 265) needs to be applied on top of Geant4.

CLHEP:  
http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.1.4.1.tgz

Geant4 download page url:
http://geant4.web.cern.ch/geant4/support/download.shtml 

Source:
geant4.10.00.tar.gz

Updated datasets:
G4NDL.4.4.tar.gz
G4EMLOW.6.35.tar.gz
G4PhotonEvaporation.3.0.tar.gz
G4RadioactiveDecay.4.0.tar.gz
G4NEUTRONXS.1.4.tar.gz
G4ABLA.3.0.tar.gz

**Comment by davidlt** [comment]
I will take care of it.

**Comment by civanch** [comment]
The main part is geant4.10.00.tar.gz,  on top of it the patch prepared for #265 should be applied.

**Comment by davidlt** [comment]
@civanch `GEANT10` IB is back online. The next available should be `CMSSW_7_0_GEANT10_X_2014-01-07-1400`. It includes your required changes. I didn't include `clhep-2.1.1.0-no-virtual-inline.patch` for CLHEP as it didn't apply cleanly. I will ask Giulio to reassess the need of it once IB is available before forward porting.

**Comment by davidlt** [comment]
@civanch IB failed due to some missing pieces in CMSDIST from ?/stable branch. It was merged and hopefully 1400 IB is fine.

**Comment by civanch** [comment]
Hi David,
why we use clhep-2.1.1.0 patch instead of new clhep version: http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.1.4.1.tgz ?

**Comment by davidlt** [comment]
We needed to patch previous CLHEP version for performance reasons, I believe. I do not know yet, if the same patching is required for CLHEP 2.1.4.1, but there is a high probability that it will be. Let's wait for the 1400 IB.

In addition to that, I still see at least one unit test failing in `SimG4Core/Geometry`.

**Comment by civanch** [comment]
I have postpone the fix of this unit test, because in cand versions of Geant4 there were bugs in geometry, which may be fixed in final 10.0.

**Comment by davidlt** [comment]
The new IB is ready, you may start looking into the failing unit test, while I check CLHEP patch.

**Comment by davidlt** [comment]
I have forward ported the patch and it should be in 1400 IB. Closing this ticket.
