### ISSUE TITLE
new MVA classifiers for EGAMMA

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#299]
New xml files should be updated in the /data externals in these two packages
RecoParticleFlow/PFTracking
RecoEgamma/ElectronIdentification

See details in 
https://github.com/cms-sw/cmssw/pull/1801

@lgray

**Comment by ktf** [comment]
Sorry but where is this data actually located?

**Comment by slava77** [comment]
These download.url files
https://github.com/lgray/cmssw/blob/91ec9d69842a31d2a096dbc851fb4168c4fdfd4c/RecoParticleFlow/PFTracking/data/download.url
https://github.com/lgray/cmssw/blob/91ec9d69842a31d2a096dbc851fb4168c4fdfd4c/RecoEgamma/ElectronIdentification/data/download.url

have the following new files
For RecoEgamma/ElectronIdentification
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoEgamma/ElectronIdentification/data/TMVA_BDTSoftElectrons_9Dec2013.weights.xml

For RecoParticleFlow/PFTracking
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/TMVAClassification_ConvBremFinder_Testetgt20absetagt1_479_BDT.weights.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/TMVAClassification_ConvBremFinder_Testetgt20absetalt1_479_BDT.weights.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/TMVAClassification_ConvBremFinder_Testetlt20absetagt1_479_BDT.weights.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/TMVAClassification_ConvBremFinder_Testetlt20absetalt1_479_BDT.weights.xml

**Comment by ktf** [comment]
This is now done. Will be in next IB.

**Comment by slava77** [comment]
Next IB: is it 0200 or did it already make into 1400?

**Comment by ktf** [comment]
1400 should have them.
