### ISSUE TITLE
Need bpmpd external package for HI developments in 53X

### ISSUE THREAD

**Issue by yetkinyilmaz** [cms-sw/cmsdist#309]
Hi.
This is a follow-up on the request for changing the bpmpd code to external. The change was decided in the RECO/AT meeting of December 5, 2013.
https://indico.cern.ch/conferenceDisplay.py?confId=271466#2013-12-05

The technical details of the package were discussed here:
https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/2915.html

Thanks for any help.

**Comment by smuzaffar** [comment]
Do you have the build recipe (spec file) for this?

**Comment by ktf** [comment]
Closing this. Reopen if it still applies.
