### ISSUE TITLE
New patch for Geant4 9.6p02

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#310]
During winter break number of SIM production jobs were lost due to the new Geant4 bug. The fix should be applied for CMSSW_7_0_X, CMSSW_6_2_X, and CMSSW_6_2_X_SLHC.

The patch is very simple and should not affect any CMS object but only fix crashes in production. It can be accessed via url: https://vnivanch.web.cern.ch/vnivanch/geant4-9.6p02-cms01.patch

**Comment by ktf** [comment]
@degano can you prepare the updated geant4.spec ? Thanks.

**Comment by ktf** [comment]
@degano we need the same fix for 62x and 62xslhc

**Comment by civanch** [comment]
Thanx for adding the patch to 7_0_X. For me is working fine. The next step would be addition to 6_2_X and 6_2_XSLHC where the bug was first observed.

**Comment by ghost** [comment]
The patch is merged in all the relevant releases.
