### ISSUE TITLE
xrootdpyfs doesn't work (missing dependency?)

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmsdist#3341]
In `CMSSW_9_3_X_2017-08-09-1100`, I can't import `xrootdpyfs`:
```
python
>>> import xrootdpyfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms-ib.cern.ch/nweek-02484/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-akfcbo/lib/python2.7/site-packages/xrootdpyfs/__init__.py", line 182, in <module>
    from .fs import XRootDPyFS
  File "/cvmfs/cms-ib.cern.ch/nweek-02484/slc6_amd64_gcc630/external/py2-pippkgs_depscipy/3.0-akfcbo/lib/python2.7/site-packages/xrootdpyfs/fs.py", line 29, in <module>
    from fs.base import FS
ImportError: No module named fs.base
```

When I look at the output of `pip freeze`, the list does not contain the `fs` package. I guess this needs to be added as a dependency.

Also, it would be nice to add these Python bindings to the next 80X release, since that is still the analysis release for hundreds of users.

**Comment by smuzaffar** [comment]
should be fixed via #3346

**Comment by davidlange6** [comment]
looks like this was closed prematurely - xrootdpyfs seems to depend on the old (2008 vs 2016) version of fs...whereas of course whats available today is the new one. maybe its a trivial fix to xrootd but maybe not.

**Comment by gudrutis** [comment]
This issue should be fixed by pull request #3445.

**Comment by smuzaffar** [comment]
@davidlange6 , @kpedro88  this is now fixed in latest 94X IB.
Which release you wanted to backport these changes.... is it 80X?

**Comment by kpedro88** [comment]
@smuzaffar it would be great for this to work in any releases used for analysis. I would count 80X, 92X (and maybe 93X?).

**Comment by gudrutis** [comment]
Pull request #3451 should fix this issue on 93X.
Pull request #3454 should fix this issue on 92X.

**Comment by smuzaffar** [comment]
this is now available in 80x, 92x and above.
