### ISSUE TITLE
openmpi 2.1.1 --enable-mpi-cxx  failed to build on aarch64

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#3421]
@pmillet , looks like openmpi v2.1.1 with  --enable-mpi-cxx has build errors for ARM64 and PowerPC. This issue was also reported here https://github.com/open-mpi/ompi/issues/2055 . Looks like this was fixe in latest releases. Should we try v3.0.0 or if you want to stick to v2 then we can try the v2.x branch's latest commit to build (v2.1.2 is not yet released).

**Comment by smuzaffar** [comment]
by the way, @mrodozov is testing v2.1.2RC4

**Comment by pmillet** [comment]
if it would work with a newer v2 version this would be best

**Comment by mrodozov** [comment]
I've built the new version found here https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.2rc4.tar.gz using the existing patch namely openmpi-2.1.1-disable-lsf-support.patch. Then I've also built version 3.0 found here https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz with this patch https://patch-diff.githubusercontent.com/raw/open-mpi/ompi/pull/4204.patch provided for the issue you've opened here https://github.com/open-mpi/ompi/issues/3546 so what would you suggest ?

**Comment by smuzaffar** [comment]
@mrodozov , thanks for checking this. Can you please make a PR for v2.1.2RC4 for 94X/gcc630.
If @pmillet  want to test v3.0.0 then we can update it for 94X DEVEL IBs.
@pmillet , can you provide some unit test for openmpi in cmssw?

**Comment by pmillet** [comment]
@mrodozov @smuzaffar  - I just tested v2.1.2RC4 and it seems to work fine with Sherpa. From that side it is ok to stay with v2 releases.

**Comment by smuzaffar** [comment]
done via https://github.com/cms-sw/cmsdist/pull/3424
