### ISSUE TITLE
Create PhysicsTools/NanoAOD data area

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#3429]
using the files in PhysicsTools/NanoAOD/data in 
cms-sw/cmssw#20563

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it.

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals
https://github.com/cms-sw/cmsdist/pull/3431 should add the new data external in 94X
