### ISSUE TITLE
Theano incompatible with Keras v2

### ISSUE THREAD

**Issue by aminnj** [cms-sw/cmsdist#3491]
Hi,

I'm trying to use keras with the theano backend from within CMSSW. This works fine in releases up until CMSSW_9_2_3. From CMSSW_9_2_4 and on, the version of keras provided is too new for the theano version, and this causes a crash like [1]. The test code below illustrates this.
```python
import keras
import theano
from keras.models import Sequential
from keras.layers import MaxPooling2D, Conv2D

print keras.__version__
print theano.__version__

model = Sequential()
model.add(Conv2D(32, 10, 10,border_mode='valid',input_shape = (1,100,100)))
model.add(MaxPooling2D(pool_size=(2, 2))) # <-- crashes here after 9_2_4
```
For example, in 9_2_3, the versions of keras and theano are 1.2.2 and 0.8.2. In 9_2_4, they become 2.0.5, 0.8.2 (and these versions are the same as in CMSSW_9_4_0_pre2, for example).

Is it possible to update theano to maintain compatibility with keras?

Thanks,
Nick 

[1] 
https://github.com/fchollet/keras/issues/5785

**Comment by smuzaffar** [comment]
@aminnj , thanks for reporting this. Looks like we need to update Theano to 0.9.0
```
>python ~/x.py 
Using Theano backend.
2.0.5
0.9.0
x.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (10, 10), padding="valid", input_shape=(1, 100, 1...)`
  model.add(Conv2D(32, 10, 10,border_mode='valid',input_shape = (1,100,100)))
>echo $?
0
```

**Comment by smuzaffar** [comment]
assign extrnals
@mrodozov , can you please update Theano to 0.9.0 for 94X (and then back port to 93X and 92X).
@aminnj , do you have any test which we can run to make sure that this is working otherwise we can just use the code you have mentioned in your first comment.

**Comment by aminnj** [comment]
Hi, thanks for testing this with 0.9.0. You can use my test snippet, as that's the only discriminative error for theano with keras v1 and v2 I've found.

**Comment by smuzaffar** [comment]
thanks to @mrodozov , this has been fixed for latest 92,93 and 94 IBs and will be part of next releases
