### ISSUE TITLE
add tensofrlow CLI scripts to externals

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#3551]
From integration of https://github.com/cms-sw/cmssw/pull/19893

> could we get all the CLI scripts https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/tools and https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms in CMSSW?

@pablodecm  @riga  @ferencek @mverzett

**Comment by davidlange6** [comment]
we should include these yes..

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/3747 should include these scripts ( https://github.com/cms-sw/cmsdist/pull/3747/files#diff-0ad0c903e6e365b28568821301015306R55 )
