### ISSUE TITLE
Switch ROOT6 branch to the new Geant4 reference tag 10.3ref11

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#3560]
Geant4 provides one of the last reference version before full release, which requires validation within CMSSW. For that an upgrade of CMSSW_10_0_ROOT6 branch is needed.

The new version of Geant4 is available at ~vnivanch/public/geant4-10-03-ref-11/geant4
or as a tar ~vnivanch/public/geant4-10-03-ref-11/g410.3ref11.tar.gz 

This reference version should fully substitute the code in cms/4.10.04.b01
Additionally to the code a new dataset is needed:
~vnivanch/public/G4EMLOW7.3.tar.gz or ~vnivanch/public/G4EMLOW7.3

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it
