### ISSUE TITLE
Switch 7_1_X to CLHEP 2_1_4_1 

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#357]
CMSSW_7_1_X needs to be switched to CLHEP 2_1_4_1 to be a starting point for making a patch for thread safe random generation. In GEANT4_10 branch this switch was already done (pull request 298).

**Comment by ktf** [comment]
@nclopezo can you start preparing a pull request for that? Thanks.

**Comment by nclopezo** [comment]
I created the pull request #362 using @davidlt's commits for IB/CMSSW_7_1_X/geant10 branch

**Comment by ktf** [comment]
@degano since @nclopezo goes on holidays starting tonight, can you try to build 710_pre1 with this PR applied on top of it so that we make sure it builds correctly?

**Comment by ktf** [comment]
Should be taken care by #362.
