### ISSUE TITLE
Update Geant4 candidate version for the ROOT6 branch

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#3594]
The candidate version for the new Geant4 release 10.4 is available. We need to update ROOT6 branch.

The new version of Geant4 is available at ~vnivanch/public/geant4-10-04-cand-01/geant4
or as a tar ~vnivanch/public/geant4-10-04-cand-01/geant4-10-04-cand-01.tar.gz

This reference version should fully substitute the code in cms/4.10.04.b01
Additionally to the code new datasets are needed:
1) ~vnivanch/public/geant4-10-04-cand-01/G4ENSDFSTATE2.2.tar.gz or ~vnivanch/public/geant4-10-04-cand-01/G4ENSDFSTATE2.2
2) ~vnivanch/public/geant4-10-04-cand-01/PhotonEvaporation5.2.tar.gz or ~vnivanch/public/geant4-10-04-cand-01/PhotonEvaporation5.2 
3) ~vnivanch/public/geant4-10-04-cand-01/RadioactiveDecay5.2.tar.gz or ~vnivanch/public/geant4-10-04-cand-01/RadioactiveDecay5.2

**Comment by mrodozov** [comment]
closing this, the changes are done in the PRs (see the reference above)
