### ISSUE TITLE
Update cms-data/RecoBTag-Combined to V01-00-08 in 94X IBs

### ISSUE THREAD

**Issue by pablodecm** [cms-sw/cmsdist#3687]
A cherry-pick of https://github.com/cms-sw/cmsdist/commit/33254eff2209237efc75e25696c6fd84796e59b6 to https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_9_4_X/gcc630 IB branch is required to backport https://github.com/cms-sw/cmssw/pull/19893 to 9_4_X as discussed in https://github.com/cms-sw/cmssw/issues/21864.

**Comment by pablodecm** [comment]
Last time was done by @mrodozov, I could open a PR myself if needeed but I am not sure what is the convention for cms-dist changes.

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cmsdist/pull/3688
