### ISSUE TITLE
Latest tkonlinesw update breaks gcc700 IBs

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmsdist#3727]
IBs since CMSSW_10_1_X_2018-02-06-2300 fail for gcc700 due to compilation problems related to tkonlinesw. The removal of a patch meant for gcc7 compatibility could be related to this issue.

**Comment by Dr15Jones** [comment]
@fabiocos the patch that was useful for the previous version of tkonlinesw did provide the proper fix for the problem now being seen. A new such patch would be needed for this version.

**Comment by smuzaffar** [comment]
@mrodozov is working on it

**Comment by mrodozov** [comment]
It's done here https://github.com/cms-sw/cmsdist/pull/3728.

**Comment by smuzaffar** [comment]
assign externals

**Comment by fabiocos** [comment]
the problem looks fixed, thanks
