### ISSUE TITLE
Request for updated external (MVA for e/pion pre-selection)

### ISSUE THREAD

**Issue by lgray** [cms-sw/cmsdist#377]
Necessary for: https://github.com/cms-sw/cmssw/pull/2242

The updated file is already in the central afs area:
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoEgamma/ElectronIdentification/data/TMVA_BDTSoftElectrons_27Jan2014.weights.xml

**Comment by ktf** [comment]
Actually the file was not there...

**Comment by lgray** [comment]
I can execute `wget http://cmsdoc.cern.ch/cms/data/CMSSW/RecoEgamma/ElectronIdentification/data/TMVA_BDTSoftElectrons_27Jan2014.weights.xml` and retrieve the file just fine.

Likewise, `ls /afs/cern.ch/cms/data/CMSSW/RecoEgamma/ElectronIdentification/data/TMVA_BDTSoftElectrons_27Jan2014.weights.xml` displays the file...

**Comment by ktf** [comment]
That's because I just added it.

**Comment by ktf** [comment]
Should be done. Reopen if not the case.

**Comment by lgray** [comment]
@ktf I don't see any obvious button to re-open this particular issue, unless you just want me to start a new one. 

Anyway, the file you copied is now somehow corrupt. 
@dbenedet and myself were using this file with absolutely no problem.

I tried using whatever FileInPath was giving me, using what was in the build, and getting the file in my local release.

When running in the latest IB + cms-sw/cmssw#2243 I get the following error:

```
01-Feb-2014 11:01:30 CET  Initiating request to open file file:step2.root
01-Feb-2014 11:01:31 CET  Successfully opened file file:step2.root
01-Feb-2014 11:01:40 CET  Closed file file:step2.root
----- Begin Fatal Exception 01-Feb-2014 11:01:40 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=GEDGsfElectronProducer label='gedGsfElectronsTmp'
   Additional Info:
      [a] Fatal Root Error: @SUB=TXMLEngine::ParseFile
XML syntax error at line 260

----- End Fatal Exception -------------------------------------------------
```

... If I understand correctly cmssw is opening the file fine but cannot parse.

@dbenedet Could you copy the file again into the common afs area? Perhaps the next IB will be ok.

@slava77

**Comment by dbenedet** [comment]
Hello I recopied the file in the central afs:
/afs/cern.ch/cms/data/CMSSW/RecoEgamma/ElectronIdentification/data/
which seemed to be different in the version copied by Giulio. Don't what happen.

**Comment by dbenedet** [comment]
I put also one version in my public if you need again to copy again:
/afs/cern.ch/user/b/benedet/public/TMVA_BDTSoftElectrons_27Jan2014.weights.xml

**Comment by ktf** [comment]
Not sure either. When I checked the file was _not_ there.

**Comment by dbenedet** [comment]
Hi Giulio, but then from where did you take the file??

**Comment by ktf** [comment]
From the url lindsey put in the download.url file

**Comment by lgray** [comment]
Anyway, the present file in the common afs area works just fine. Tested runTheMatrix.py -l 17.0 with the new file in the local release. Please take that one.\

Just FYI: I got it into the local release using cat download.url | xargs wget, so it's consistent with what is saved centrally.

**Comment by lgray** [comment]
@ktf Looks like the appropriate file is now shipped with the release. 

@slava77 Please go ahead and start on cms-sw/cmssw#2243
