### ISSUE TITLE
URGENT: use new frontier_client version 2.8.10

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#378]
Please replace frontier_client 2.8.9 ASAP with 2.8.10.  2.8.9 crashes with a segmentation fault any time data is requested more than 5 minutes after the first data is requested.

This is for at least 7_1_X.  I don't know if 7_0_X has been updated to 2.8.9 yet.

**Comment by davidlange6** [comment]
@DrDaveD - is this already confirmed to be the reason for the large scale seg faults in 700pre1 relvals?

**Comment by DrDaveD** [comment]
Yes

**Comment by davidlange6** [comment]
Thanks

**Comment by DrDaveD** [comment]
Wait, I thought you meant 710pre1.  Is that what you meant?

**Comment by davidlange6** [comment]
yes - 710pre1 - sorry

**Comment by ktf** [comment]
Next IB should have the new version. Do we need to do pre2 tomorrow?

**Comment by davidlange6** [comment]
might as well….
