### ISSUE TITLE
dd4hep depends on rootpy

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#3800]
why? Thats quite unusual- I don't see it in the dd4hep repository.

**Comment by smuzaffar** [comment]
@davidlange6 , I think this is because of few python scripts in dd4hep which import ROOT https://github.com/AIDASoft/DD4hep/search?l=Python&q=root&type=&utf8=%E2%9C%93

**Comment by davidlange6** [comment]
Ah.... there is rootpy and pyroot... declaring a root dependency is enough in this case

David


On 10 Mar 2018, at 23:14, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , I think this is because of few python scripts in dd4hep which import ROOT https://github.com/AIDASoft/DD4hep/search?l=Python&q=root&type=&utf8=%E2%9C%93

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/3838 cleans up this dependency
