### ISSUE TITLE
Memory leak in pythia8 226 for 9_3_X

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmsdist#3840]
C. Jones reports that he recently found a bug in Pythia8 226 used in 9_3_X which is causing an extreme memory leak in MC workflows being run. This is apparent in versions earlier than 230 used in 10_1_X, and affects production. The suggested fix is actually trivial, we need to change include/Pythia8Plugins/LHAPDF6.h line 138 from

 138     } else LHAPDF6Interface::initializedSets[id] = make_pair(pdfInfo,0);
to
 138     } else LHAPDF6Interface::initializedSets[id] = make_pair(pdfInfo,1);

I.e. change the 0 to a 1 (the number is a reference count and it should start at 1).

**Comment by fabiocos** [comment]
@perrozzi  @efeyazgan FYI
@smuzaffar I understand that we could simply apply a patch to the code, of course its effect should be checked by the generator group

**Comment by smuzaffar** [comment]
@fabiocos , We have already applied the patch for 10.1.X ( https://github.com/cms-externals/pythia8/commits/cms/230 )  and there is a PR https://github.com/cms-sw/cmsdist/pull/3839 for 93X as well (not yet integrated).

**Comment by fabiocos** [comment]
@smuzaffar @kpedro88 thanks, I think this could be part of the new 9_3_X to be built for the upgrade studies

**Comment by kpedro88** [comment]
Yes, it would be good to include it when the release is cut.

**Comment by perrozzi** [comment]
thanks, it would be good to have a brief discussion today at the ORP
@mkirsano @alberto-sanchez

**Comment by kpedro88** [comment]
This can be closed, #3839 is merged.

**Comment by fabiocos** [comment]
@perrozzi @mkirsano @alberto-sanchez was a test run on the new vs old version, checking that the memory leak has gone but that the results stay unchanged?

**Comment by alberto-sanchez** [comment]
@fabiocos, we have run a basic test, using one of our workflows that we use for an ongoing analysis.
We run the same cfg, for 9_3_6 and 9_3_7, in the generation of Chib(3P) -> Upsilon(3S) gamma. The result is identical. I am attaching a couple of slides. 
[comparison_936_937.pdf](https://github.com/cms-sw/cmsdist/files/1831096/comparison_936_937.pdf)
So, both releases are the same , at least for this test.

**Comment by fabiocos** [comment]
@alberto-sanchez excellent, thanks

**Comment by fabiocos** [comment]
@alberto-sanchez obviously any test should probe the class https://github.com/cms-externals/pythia8/blob/cms/230/include/Pythia8Plugins/LHAPDF6.h  involved, I assume your is doing so

**Comment by davidlange6** [comment]
production "Tests" (sigh) show this problem is not fixed (or there is a new one affecting the same workflow. What test was actually performed?

**Comment by efeyazgan** [comment]
Not a memory leak test but just running a process and checking nothing got screwed up, cross sections and a few distributions are the same as in 9_3_6.

**Comment by davidlange6** [comment]
guess its time to reopen this issue until the underlying problems resolved and checked.

**Comment by fabiocos** [comment]
@davidlange6 could you please point me to the problematic workflow?

**Comment by davidlange6** [comment]
all I know is above

https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4981/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/1/1/2/1/1/1/1/1/1/1/1/1/1/1/2/1/1/1/1.html

**Comment by Dr15Jones** [comment]
I've traced down the problem. The change I made to fix the reference counting does work, the data object is now removed. However, it doesn't matter because the data object being removed has pointers to large objects which it does not delete.

See

https://github.com/Dr15Jones/pythia8/blob/cms/230/include/Pythia8Plugins/LHAPDF6.h#L25

**Comment by Dr15Jones** [comment]
Here is the fix:

https://github.com/cms-externals/pythia8/pull/9

Without the fix, after 5000 events the job exceeds 3GB of RSS. With the fix, it stays under 400MB.
