### ISSUE TITLE
Erroneous dependency of professor2 on py2-matplotlib?

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmsdist#3996]
Compiling code in CMSSW with scram, the following warning appears:

****WARNING: Invalid tool py2-matplotlib. Please fix professor2 file.

Indeed py2-matplotlib is not part of the tools configured in the regular 10_2_X environment, but present in the professor2.xml. As far as I can see from Jenkins logs the tool is found during the full builds in the cache, from https://cmssdt.cern.ch/jenkins/job/build-any-ib/59559/consoleText for CMSSW_10_2_X_2018-05-13-0000:

Starting to process package external+py2-matplotlib+1.5.2-gnimlf
Checking if py2-matplotlib is cached.
py2-matplotlib is available from remote repository "cms.week0". Not building. Downloading and installing...
Package external+py2-matplotlib+1.5.2-gnimlf found in repository

But py2-matplotlib itself is then not part of the tools in the release. If this is not really needed, the line https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_2_X/gcc630/professor2-toolfile.spec#L17 should be removed

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/commit/a8c83e41c9a017dad1ceb409938b906291662605 should fix this warning
