### ISSUE TITLE
Request of UTM external library update

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmsdist#4132]
Request of UTM external library to fix distinct L1 conditions being hashed to the same string.

Please use the tag utm_0.6.7 at https://gitlab.cern.ch/cms-l1t-utm/utm

CMSSW release: 10_2_X and 10_1_X.

**Comment by smuzaffar** [comment]
- 10.2.X: https://github.com/cms-sw/cmsdist/pull/4133
- 10.1.X: https://github.com/cms-sw/cmsdist/pull/4134
