### ISSUE TITLE
Request add google benchmark as an external

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmsdist#4146]
I have found using google benchmark

https://github.com/google/benchmark

to be very handy to do micro-benchmarks that can help decide exactly which variations of an algorithm are the fastest. I can continue to build it on my own and 'hack' it into my scram workspace, but it would be more convenient if we included it.

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
@Dr15Jones , #4150 should add google benchmark in cmssw. I would like to added couple of unit tests from the example usage of https://github.com/google/benchmark . Should I add these unit tests under Utilities/General or FWCore/Utilities?

**Comment by smuzaffar** [comment]
+externals
google benchmark is in 10.2.X IBs.
