### ISSUE TITLE
Problem building Rivet 2.0.0

### ISSUE THREAD

**Issue by ghost** [cms-sw/cmsdist#417]
@mkirsano

I created a spec file to build Rivet 2.0.0 following the integration of #374.

I am experiencing a weird error during the configuration of Rivet:

```
checking fastjet/TrackJetPlugin.hh usability... yes
checking fastjet/TrackJetPlugin.hh presence... yes
checking for fastjet/TrackJetPlugin.hh... yes
configure: Found yaml-cpp library at /build/degano/rivet_20/a/slc6_amd64_gcc481/external/yaml-cpp/0.5.1/lib/libyaml-cpp.so
configure: Found yaml-cpp header directory at /build/degano/rivet_20/a/slc6_amd64_gcc481/external/yaml-cpp/0.5.1/include
checking yaml-cpp/node.h usability... no
checking yaml-cpp/node.h presence... no
checking for yaml-cpp/node.h... no
checking yaml-cpp/node/node.h usability... no
checking yaml-cpp/node/node.h presence... no
checking for yaml-cpp/node/node.h... no
configure: error: yaml-cpp API version could not be determined
```

Although the header yaml-cpp/node/node.h is actually there:

```
ll /build/degano/rivet_20/a/slc6_amd64_gcc481/external/yaml-cpp/0.5.1/include/yaml-cpp/node/node.h 
-rw-r--r--. 1 degano zh 3335 Apr 14  2013 /build/degano/rivet_20/a/slc6_amd64_gcc481/external/yaml-cpp/0.5.1/include/yaml-cpp/node/node.h
```

Do you happen to know what might be the reason of the failure?

**Comment by mkirsano** [comment]
Hello,
  Some time ago I successfully built rivet 2 using the following spec file:

/afs/cern.ch/user/m/mkirsano/public/rivet.spec

I did not yet try to use this rivet in CMSSW, I suggested to Lars to do 
such tests.

```
            Cheers, Mikhail
```

**Comment by ghost** [comment]
Hello @mkirsano,
following your recipe I managed to add Rivet 2 to 7_1_X, 
It is now available in the latest build but is disabled by default in order to preserve the dependency of Rivet 1.8 used by the package GeneratorInterface/RivetInterface.

It can be easily enable using scram:

```
scram setup rivet2
```

And then addressed in the Build files with "rivet2".

Cheers,
Alessandro.
