### ISSUE TITLE
Python bindings for clang

### ISSUE THREAD

**Issue by ojeda** [cms-sw/cmsdist#421]
Would it be possible to have the LLVM external install its Python bindings for clang (or as a new external)? i.e. these ones:

  https://github.com/llvm-mirror/clang/tree/master/bindings/python/clang

We would need them if the BOOSTIO branch gets integrated into the main branch, but since this may be interesting for everyone anyway, I am raising the issue here first.

**Comment by ktf** [comment]
Please bring it up in next ORP.

**Comment by apfeiffer1** [comment]
On Thu, Feb 20, 2014 at 11:47 AM, Giulio Eulisse
notifications@github.comwrote:

>  Please bring it up in next ORP.

OK, added to the twiki, hoping that this is enough for the vORP... :)

Thanks,
       cheers, andreas

**Comment by ktf** [comment]
Should be there next IB. Reopen if not ok.
