### ISSUE TITLE
XROOTD 4.8.4

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#4214]
New version of xrootd (v4.8.4) is available  https://github.com/xrootd/xrootd/blob/v4.8.4/docs/ReleaseNotes.txt

@mrodozov , can you please update https://github.com/cms-externals/xrootd and make a cmsdist PR?

**Comment by mrodozov** [comment]
testing it with #4215

**Comment by smuzaffar** [comment]
thanks,

**Comment by mrodozov** [comment]
the PR for the new xrootd takes > 15 hours, trying to figure it out with @gudrutis
