### ISSUE TITLE
External txt calibration files for HI jets in 5_3_X

### ISSUE THREAD

**Issue by yetkinyilmaz** [cms-sw/cmsdist#424]
Dear experts;
we (@yslai @mtonjes @mandrenguyen) are working on preparing 5_3_X for new HI jet reconstruction, which requires some calibration files in txt format.
Based on discussions with @slava77 we need the following files :

/afs/cern.ch/user/y/yilmaz/public/ue/ue_calibrations_calo_data.txt
/afs/cern.ch/user/y/yilmaz/public/ue/ue_calibrations_calo_mc.txt
/afs/cern.ch/user/y/yilmaz/public/ue/ue_calibrations_pf_data.txt
/afs/cern.ch/user/y/yilmaz/public/ue/ue_calibrations_pf_mc.txt

to be copied into:

http://cmsdoc.cern.ch/cms/data/CMSSW/RecoHI/HiJetAlgos/data/

in order to use them in the upcoming 5_3_X release as externals. Can you please copy them? 

Thanks.

**Comment by slava77** [comment]
May I suggest to add some version/date name for more easier future tracking of changes, after they are copied to the cmsdoc

**Comment by yetkinyilmaz** [comment]
Hi Slava;
this is of course a very good point, but we take care of this by the txt file "headers" (the first to comment lines inside the file itself) because in the reconstruction code these filenames are fixed (switch between data/mc happens automatically based on edm::Event::isRealData() method), so we don't need to change the code (even any cffs) when updating these calibrations.

**Comment by slava77** [comment]
Giulio pointed me to #428 which is merged since 3 days.
