### ISSUE TITLE
Request of UTM external library update for HI (utm_0.7.1)

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmsdist#4334]
Request of UTM external library to handle new algorithms for HI run 2018

Please use the tag utm_0.7.0 at https://gitlab.cern.ch/cms-l1t-utm/utm

CMSSW release: 10_3_X and 10_2_X and 10_1_X.

Update in 10_3_X is needed for data-taking, i.e. emulation of uGlobalTrigger in the HLT
Update in 10_2_X is need for 1) O2O . 2) DQM .  3) DQM Online   4) DQM Offline

Update in 10_1_X is needed for O2O - as a matter of fact, we need it for the tests of HI being done this week. (this is URGENT)

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it?

**Comment by fabiocos** [comment]
@rekovic is this version back-ward compatible? I mean is it valida for both HI and regular pp data?

**Comment by rekovic** [comment]
@fabiocos 
Yes, it is backward compatible.  It adds new objects, keeping the previously available objects intact.

Add four new objects for asymmetry with a single counter threshold cut (8 bit):
ASYMET : esConditionType::AsymmetryEt
ASYMHT : esConditionType::AsymmetryHt
ASYMETHF : esConditionType::AsymmetryEtHF
ASYMHTHF : esConditionType::AsymmetryHtHF

 New features discussed in issue https://gitlab.cern.ch/cms-l1t-utm/utm/issues/2 by Arnold.
Attn @arnold, @apana

**Comment by mrodozov** [comment]
I went to install the new version from tag 070 but there was include missing in one makefile so 
I opened this https://gitlab.cern.ch/cms-l1t-utm/utm/merge_requests/16
to fix it when it's merged we'll update the package

**Comment by apana** [comment]
Hi Mircho,

I have been using the new utm library to update the uGT emulator and
had no problem compiling, installing, and running the uTM library in
CMSSW_10_2_1. Here's the recipe I'm using (from a clean 10_2_1 project
area):

cd $CMSSW_BASE
git clone https://gitlab.cern.ch/cms-l1t-utm/utm.git
cd utm
git checkout utm_0.7.0
scram tool info xerces-c
setenv XERCES_C_BASE <XERCES_C_BASE directory printed by the above command>
scram tool info boost
setenv BOOST_BASE <BOOST_BASE directory printed by the above command>
make all
make install

cd $CMSSW_BASE/src
# Now edit ../config/toolbox/{$SCRAM_ARCH}/tools/selected/utm.xml and
# change UTM_BASE to the directory pointed to by the output of "echo
$CMSSW_BASE/utm", then

git cms-addpkg L1Trigger/L1TGlobal ## for example

scram setup utm
scram b -j7

Hope this helps.

Cheers,
Len

**Comment by smuzaffar** [comment]
@apana, you might have picked up boost headers from system. When we build then we get build error about unable to find boost headers. https://gitlab.cern.ch/cms-l1t-utm/utm/blob/master/tmUtil/tmUtil.cc#L8 now uses boost but https://gitlab.cern.ch/cms-l1t-utm/utm/blob/master/tmUtil/Makefile file does not explicitly add BOOST_ROOT/include .

We need to get that Makefile fixed otherwise we can not build utm.

**Comment by smuzaffar** [comment]
@apana , I tried your instructions on cmsdev15 (where boost is not installed on system) and got this error [a]. 
```
muzaffar@cmsdev15.cern.ch>make -j 10 all
//
// make all
//
//   in /build/muz/utm/CMSSW_10_2_1/utm/tmUtil
//     compile tmUtil.cc ...
tmUtil.cc:8:10: fatal error: boost/algorithm/string/join.hpp: No such file or directory
 #include <boost/algorithm/string/join.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:58: tmUtil.o] Error 1
make: *** [Makefile:45: all] Error 1
```

**Comment by smuzaffar** [comment]
cmsdist PR to update utm is 
10.3.X: https://github.com/cms-sw/cmsdist/pull/4338
10.2.X: https://github.com/cms-sw/cmsdist/pull/4340

**Comment by rekovic** [comment]
@smuzaffar 
Can you please add a PR for 10.1.X.  I just updated the header of this issue.

>Update in 10_1_X is needed for O2O - as a matter of fact, we need it for the tests of HI being done this week. (this is URGENT)

Many thanks.

**Comment by smuzaffar** [comment]
@rekovic , cmsdist PR for 10.1.X is https://github.com/cms-sw/cmsdist/pull/4343

**Comment by rekovic** [comment]
Thanks.
