### ISSUE TITLE
Create spec file for rucio client in comp_gcc630 branch

### ISSUE THREAD

**Issue by ticoann** [cms-sw/cmsdist#4347]
JIRA tickets related to this

https://its.cern.ch/jira/browse/CMSRUCIO-30

Here is the dependencies

https://github.com/rucio/rucio/blob/master/tools/pip-requires-client

@h4d4, Lina, I will try to work on this one. But I have some questions regarding this.

I was just wondering whether we can use those specs by copying to comp branch. should I pick the same gcc version (630) or does it matter?

https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_10_2_X/gcc630

If we need to change specs in above branch for comp_gcc630 branch, what do we need to change,  i.e py2-six.spec

Thanks,

**Comment by ticoann** [comment]
For my information

Here is the missing pacakges.

argcomplete>=1.9.4

dogpile.cache>=0.6.5

boto>=2.48.0; python_version >= '2.7'

tabulate>=0.8.2

progressbar2>=3.37.1

bz2file>=0.98

python-magic>=0.4.15

 

Need to be upgrade

urllib3>=1.23                py2-urllib3 1.22

setuptools>=36.8.0     py2-setuptools 28.3.0

 

we already have

py2-futures 3.2.0

py2-requests 2.19.1

py2-argparse 1.4.0

py2-nose 1.3.7

py2-six 1.11.0

**Comment by amaltaro** [comment]
It's already available: https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-rucio-clients.spec

**Comment by amaltaro** [comment]
please close
