### ISSUE TITLE
Need a 'new' version of cppunit

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmsdist#4372]
The cppunit code is using `std::auto_ptr` which is deprecated in the C++ standard. However, it appears that the official version of cppunit is no longer being updated. Therefore I suggest we either

1) find a fork of cppunit that is being updated by the community or
2) fork our own version of cppunit so we can updated it to the latest C++ standard.

Eventually we can phase out our use of cppunit in favor of catch2 (which we are already beginning to use).

**Comment by davidlange6** [comment]
regardless of the current state of development, it looks like we might be nine years behind the most recent release...

**Comment by davidlange6** [comment]
potential good news:

git clone git://anongit.freedesktop.org/git/libreoffice/cppunit
 cd cppunit/
grep -r auto_ptr

returns nothing..

**Comment by smuzaffar** [comment]
cmsdist PR https://github.com/cms-sw/cmsdist/pull/4383 should update cppunit to version 1.40.1
