### ISSUE TITLE
Update root 6.12.X to add dictionary for std::unqiue_ptr

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmsdist#4386]
see https://sft.its.cern.ch/jira/browse/ROOT-9698 
The needed patch
https://github.com/root-project/root/commit/7e6ac0167db0eaecd5ed0c6bd739aab752098fc6

**Comment by gartung** [comment]
needed for
 https://github.com/cms-sw/cmssw/pull/24710 
and 
https://github.com/cms-sw/cmssw/pull/24565

**Comment by smuzaffar** [comment]
new root with the patch is available via https://github.com/cms-sw/cmsdist/pull/4387 PR

**Comment by gartung** [comment]
Need this patch too
https://github.com/root-project/root/pull/2960/commits/066167ead65c3020332aa095601796305deb4feb
