### ISSUE TITLE
Add deprecated warning to clang compilation options

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmsdist#4400]
Please test a few IB's with -Wdeprecated added to the clanf compilations options. The deprecated warning flag has finer detail if needed.
http://clang.llvm.org/docs/DiagnosticsReference.html#wdeprecated

**Comment by mrodozov** [comment]
I've enabled all Wdeprecated flags listed above (separately) and recompiled cmssw with clang (using the 10-03 clang IB)
Warnings coming from cmssw only (excluding externals) are ~10k 
Mostly they fall under the -Wdeprecated-dynamic-exception-spec category, here the entire list:
```
      1 [-Wbraced-scalar-init]
      2 [-Wconstant-conversion]
  10124 [-Wdeprecated-dynamic-exception-spec]
      1 [-Wdeprecated-dynamic-exception-spec]:
      2 [-Wempty-body]
     12 [-Wenum-compare-switch]
      2 [-Wfor-loop-analysis]
      8 [-Wheader-guard]
      1 [-Wimplicit-exception-spec-mismatch]
     34 [-Winconsistent-missing-override]
      2 [-Winfinite-recursion]
      3 [-Winstantiation-after-specialization]
      7 [-Wliteral-conversion]
      1 [-Wmismatched-new-delete]
     46 [-Wmismatched-tags]
     48 [-Woverloaded-virtual]
      3 [-Wparentheses-equality]
     44 [-Wpessimizing-move]
     12 [-Wpotentially-evaluated-expression]
      1 [-Wself-assign-field]
      7 [-Wself-assign]
      8 [-Wshift-negative-value]
      5 [-Wtautological-constant-out-of-range-compare]
      2 [-Wtautological-undefined-compare]
      3 [-Wundefined-bool-conversion]
      1 [-Wunneeded-internal-declaration]
     16 [-Wunused-const-variable]
     21 [-Wunused-function]
      9 [-Wunused-lambda-capture]
     56 [-Wunused-variable]
```
Flags for compilation and build log are available here:
https://cernbox.cern.ch/index.php/s/FAyXqfgApIswxBK
https://cernbox.cern.ch/index.php/s/VtRWmYKU6GZikL7
and here
/afs/cern.ch/user/m/mrodozov/public/CLANG_warnings

**Comment by gartung** [comment]
Interesting that no deprecated function/template warnings show up. 

Thanks.
