### ISSUE TITLE
evtgen

### ISSUE THREAD

**Issue by alberto-sanchez** [cms-sw/cmsdist#4407]
Since EvtGen has moved, I wonder if we could clone the source 
http://phab.hepforge.org/source/evtgen.git
to cms-externals and start creating the branches following the same nomenclature as currently use
from the given tags

R01-03-00 -> 1.3.0
R01-06-00 -> 1.6.0
R01-07-00 -> 1.7.0

thanks

**Comment by alberto-sanchez** [comment]
@smuzaffar Should I proceed and create the repository?. We will need to update evtgen soon

**Comment by smuzaffar** [comment]
@alberto-sanchez , sorry I overlooked this issue. https://github.com/cms-externals/evtgen is now available with branches
```
EvtGen tag -> CMS branch
R01-03-00 -> cms/1.3.0
R01-06-00 -> cms/1.6.0
R01-07-00 -> cms/1.7.0
```

**Comment by alberto-sanchez** [comment]
Thanks alot!.  
For future updates, are we going to have master branch or how we will proceed?

**Comment by smuzaffar** [comment]
Do you want to move the development of evtgen in to cms-externals/evtgen or we just want to patch it for cms use? If it is just patching on top of their tags then just make PR for cms/xxx branch and we will integrate it in cmssw.

**Comment by alberto-sanchez** [comment]
Got it!
