### ISSUE TITLE
Update root 6.12.x to get bug fix for std::unique_ptr

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmsdist#4501]
Need this patch for root to handle the case of reading back a unique_ptr from the root file
root-project/root@066167e

**Comment by gartung** [comment]
Needed for https://github.com/cms-sw/cmssw/pull/25239

**Comment by Dr15Jones** [comment]
@gartung CMSSW_10_4 is moving to ROOT 6.14. Could you check that the 6.14 we are already using in the ROOT_614 build contains the fix you need?

**Comment by gartung** [comment]
@Dr15Jones the branch cms/v6-14-00-patches/8e96679 does not have it yet. I think Phillipe submitted a backport request to root/v6-14-00-patches.

**Comment by gartung** [comment]
Backport PR is 
https://github.com/root-project/root/pull/2961

**Comment by gartung** [comment]
change to root/6-14-00-pathches
