### ISSUE TITLE
Update head of ROOT/v6-14-00-patches to include fix for unique_ptr 

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmsdist#4508]
Please update the head of ROOT/v6-14-00-patches to include this commit
https://github.com/root-project/root/commit/54cf5d9a22eb94656d244700d9823be2972f8db3

**Comment by gartung** [comment]
@smuzaffar

**Comment by mrodozov** [comment]
I believe this commit is included now in 6-14 https://github.com/cms-sw/root/commit/0fc2c1613040907ac05023ab2e4a0af4f2577923#diff-43b0645ddbe7a9e4f086e91a573467c7
so I'm closing this

**Comment by gartung** [comment]
@smuzaffar I see that this is in the CMS root 6.14 branch, but what is the head of the current ROOT branch used in CMSSW_10_5_X or CMSSW_10_5_X/root or CMSSW_10_5_X/rootnext

**Comment by smuzaffar** [comment]
- 10.5.X: https://github.com/root-project/root/commit/34f75bf (v6.12 branch)
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_5_X/gcc700/root.spec
- 10.5.rootnext: https://github.com/root-project/root/commit/c6edc31 (v6.14 branch)
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_5_X/rootnext/root.spec
- 10.5.root: https://github.com/root-project/root/commit/c6edc31 (master)
  - https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_5_X/rootmaster/root.spec
