### ISSUE TITLE
Remove unneeded dependencies code from the comp specs

### ISSUE THREAD

**Issue by amaltaro** [cms-sw/cmsdist#4522]
Once this PR gets merged:
https://github.com/cms-sw/cmsdist/pull/4521

there won't be the need anymore to keep the logic to generate the package dependencies in every single spec file, for instance this block:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmagent.spec#L33-L43

FYI @h4d4

**Comment by smuzaffar** [comment]
and also you do not need to have such lines https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmagent.spec#L46 in your spec. cmsBuild will auto generate these dependencies setup files and do the relocation.

**Comment by smuzaffar** [comment]
@amaltaro , can we close this issue now?

**Comment by amaltaro** [comment]
Certainly! Thanks, Shahzad. Closing.
