### ISSUE TITLE
Add pydot  library

### ISSUE THREAD

**Issue by elusian** [cms-sw/cmsdist#4525]
Dear admins
as discussed in https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2603.html I'm opening an issue for the addition of pydot to cmssw.

This library is needed for model visualization in keras.

Regards,
Enrico

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cmsdist/pull/4526
It will be available in next 23h IB.
