### ISSUE TITLE
Update XROOTD 4.8.5

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#4617]
New version of xrootd (v4.8.5) is available https://github.com/xrootd/xrootd/blob/v4.8.5/docs/ReleaseNotes.txt 

@mrodozov , can you please update https://github.com/cms-externals/xrootd and make a cmsdist PR?

**Comment by smuzaffar** [comment]
@bbockelm , do you foresee any any reason not to move to xrootd 4.8.5

**Comment by bbockelm** [comment]
Nope, there's no significant bugs in that version's client I am tracking.
