### ISSUE TITLE
Move IOPool/Input/testdata root files to an external package

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmsdist#4618]
The PR cms-sw/cmssw#25018 adds a new root file to IOPool/Input/testdata of about 100 kB, on top of already existing 750 kBs of older root data. This is the opportunity to move all these files outside the main CMSSW repository to a new dedicated external data package.

@smuzaffar as we have discussed can we have that new package? This would allow to finally merge the PR preventing the addition of extra space

**Comment by Dr15Jones** [comment]
There are questions as to how we can make PoolSource find the moved files.

**Comment by Dr15Jones** [comment]
@smuzaffar under this proposal, where would the actually data files appear?

**Comment by smuzaffar** [comment]
Just like any data file, these files will be install under `$CMS_PATH/share/cms/data-IOPool-Input/<tag>` (which should be part of CMSSW_SEARCH_PATH ).

**Comment by smuzaffar** [comment]
@Dr15Jones , are you worried about unit test https://github.com/cms-sw/cmssw/blob/master/IOPool/Input/test/TestPoolInput.sh#L68 ? We can do something like
```
IOPoolInputData=$CMSSW_BASE/src
for dir in $(echo $CMSSW_SEARCH_PATH | tr : '\n') ;  do
  if [ -e ${dir}/IOPool/Input/data ] ; then
    IOPoolInputData=${dir}
    break
  fi
done
```

and then instead of `${CMSSW_BASE}/src/IOPool/Input/testdata/` we can use `$IOPoolInputData/`

**Comment by Dr15Jones** [comment]
With this proposal we should either

1. Create two separate repositories, data-IOPool-Input and data-FWCore-Modules, since the original data and the one needed for the new pull request are needed by different CMSSW packages, or
1. Create a completely different named repository, data-Framework-Tests (?), which is meant to hold files used for testing for all framework related tests.

**Comment by smuzaffar** [comment]
+1 for creating two repos but I noticed @fwyzard wanted to add the new file under IOPool/Input (may be he wants to get it tested via the unit test).
I would like to keep the data repo names and cmssw package names same so that one day we can assign signatures for data externals too

**Comment by Dr15Jones** [comment]
I think @fwyzard wanted to use IOPool/Input because I originally suggested to put it there. I now think my original idea was bad and we would want to keep the data file used for a test in a place related to the package running the test.

**Comment by fwyzard** [comment]
l am completely agnostic as to where to put the file - just let me know
where and how :-)

**Comment by smuzaffar** [comment]
closing this. This has been resolved by https://github.com/cms-sw/cmsdist/pull/4627
