### ISSUE TITLE
update vecgeom or patch to resolve uninit value use

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#4626]
I was running valgrind on wf 150.0
and it looks like I rediscovered the issue fixed in https://gitlab.cern.ch/VecGeom/VecGeom/merge_requests/545
This is now present in present in v01.00.00

In valgrind the UninitCondition in an instantiation of a G4Polycone called from ```DDG4SolidConverter::polycone_rrz(DDSolid const&)``` appears at
https://gitlab.cern.ch/VecGeom/VecGeom/blob/v00.05.00/source/UnplacedPolycone.cpp#L754

**Comment by smuzaffar** [comment]
@slava77 , https://github.com/cms-sw/cmsdist/pull/4628 patches vecgeom. The latest version does not go well with geant4 version we have.
