### ISSUE TITLE
Request for updated external (MVA for e/pion pre-selection)

### ISSUE THREAD

**Issue by lgray** [cms-sw/cmsdist#465]
Please update the soft-electron MVA weights file, as found in https://github.com/cms-sw/cmssw/pull/2717

Thanks!

**Comment by davidlt** [comment]
You don't need to modify `download.url`, what you want to modify is in CMSDIST: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_1_X/stable/data-RecoEgamma-ElectronIdentification.spec

**Comment by ktf** [comment]
Actually we are about to set up one repository per data package. @degano can you take care of this one as well?

**Comment by ktf** [comment]
Should be done.
