### ISSUE TITLE
Upgrade the comp_gcc630 openssl version

### ISSUE THREAD

**Issue by amaltaro** [cms-sw/cmsdist#4816]
While using the python cryptography package, I'm getting this deprecation warning:
```
CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
```

we had some discussions going on on this subject in the past months.

Maybe we could try upgrading it to the same version used in the master branch (by CMSSW).
Or we could try a larger leap and go straight with their latest stable 1.1.1 series release.

@smuzaffar I know you were trying to upgrade it in the master branch. Maybe we can discuss what were your findings and/or blockers on upgrading it.

**Comment by smuzaffar** [comment]
@amaltaro , for `CentOS8` we have decided to use system OpenSSL which is `1.1.1`.
For SLC7, we are still using `1.0.2d` and there is no plans to upgrade it.

**Comment by amaltaro** [comment]
We might just wait for that as well then. Would you know when we are suppose to start getting CMSSW for CentOS8?

**Comment by smuzaffar** [comment]
CMSSW_11_1_0_pre1, CMSSW_11_1_0_pre2 were build and deployed for CentOS8 too. Note that CentOS8 is not yet the production architecture.

**Comment by smuzaffar** [comment]
@amaltaro , should we close this issue?

**Comment by amaltaro** [comment]
Yes! We decided to rely on the system based openssl library for SLC7 as well. This issue was fixed by: https://github.com/cms-sw/cmsdist/pull/6440

Closing (thanks for the reminder, Shahzad)
