### ISSUE TITLE
cmsdev20 and lxplus: old version of CMake v 2.8.12.2 

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmsdist#4826]
Would it be possible to update CMake to 3.4.3 or higher?

Thanks.

**Comment by smuzaffar** [comment]
you mean cmake version available on cmsdev machines itself or the one part of cmssw?

**Comment by ianna** [comment]
either, both

**Comment by smuzaffar** [comment]
lxplus is not in our control so can not update any thing there.
We have cmake in cmssw but for now we are missing the toolfile for it that is why it is not available when one does cmsenv. We will add the missing toolfile. For now you can source /cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/cmake/3.10.2/etc/profile.d/init.[c]sh to get it.

**Comment by ianna** [comment]
Thanks, @smuzaffar 
I think, it's sufficient.
