### ISSUE TITLE
Merge Geant4 10.0p01 on top of CMSSW_7_1_0_pre4

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#483]
According to the plan of Geant4 10.0p01 integration a special build needs to be created on top of CMSSW_7_1_0_pre4, which includes all modifications available at the GEANT10 branch. This build will be used for RelVal validation versus pre4. 

Practically it will be a merge of GEANT10 to 7_1_0_pre4.

For this special build will be optimal to recompile Geant4 10.0p01 in sequential mode, do not apply CMS private patch, and use Geant4 data files from GEANT10 branch.

GEANT10 branch should be left unchanged, it will be used for further development of MT variant of CMSSW simulation.

**Comment by civanch** [comment]
Updated datasets (used  already in GEANT10 branch):
G4NDL.4.4.tar.gz
G4EMLOW.6.35.tar.gz
G4PhotonEvaporation.3.0.tar.gz
G4RadioactiveDecay.4.0.tar.gz
G4NEUTRONXS.1.4.tar.gz
G4ABLA.3.0.tar.gz

**Comment by civanch** [comment]
To build in sequential mode one needs to set OFF for MT,
possible cmake options to build this version:

cmake -DCMAKE_INSTALL_PREFIX=${G4 build dir} \
-DGEANT4_USE_GDML=ON \
-DGEANT4_INSTALL_DATADIR=${pass to G4 data} \
-DXERCESC_ROOT_DIR=${pass to XERCESC} \
-DGEANT4_INSTALL_EXAMPLES=OFF \
-DGEANT4_ENABLE_TESTING=OFF \
-DGEANT4_USE_SYSTEM_CLHEP=OFF \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_STATIC_LIBS=ON \
-DGEANT4_BUILD_MULTITHREADED=OFF \
${G4INSTALL}

**Comment by civanch** [comment]
As we also agree the merge if successful should go into 7_1_X.

**Comment by ktf** [comment]
@degano can you please add Vladimirs changes to geant4.10 to disable 
multithreading so that we can start building a release based on this? 
Thanks.

**Comment by ktf** [comment]
@degano it looks like we need to have:

```
-DG4MULTITHREADED
```

dropped from the geant4-toolfile.spec

**Comment by ktf** [comment]
Vladimir, the current GEANT4_X IB is the candidate for the release. Unless you have objections we can go ahead and build.

**Comment by davidlange6** [comment]
@ktf - is the branch completely consistent with pre4 +g4 changes or has it evolved to include the 71x IB at this point?
(we would like it to be like pre4)

**Comment by ktf** [comment]
right. we will actually rebuild pre4 itself, just cmsdist changes, sorry 
for the confusion.

**Comment by davidlange6** [comment]
ah.. thanks..

**Comment by civanch** [comment]
@ktf, GEANT4_X IB seems to be OK. I am running some private tests. This will take some time but from the middle of run it is clear that there is no crashes or bad warnings. So, you can go ahead with build of the release pre4+G4 10.

**Comment by ktf** [comment]
yes, it's ongoing.

**Comment by civanch** [comment]
CMSSW_7_1_0_pre4_GEANT10 work to me fro simple private tests. Physics validation will take time. What about merge of Geant4 10.0p01 to the 7_1_X?

**Comment by ktf** [comment]
Yes, sure.

@davidlange6 , I guess we should do this for pre5, right?

**Comment by civanch** [comment]
If we believe that 10.0 is our goal, I would prefer merge now for pre5. After merge I will need to added minor clean-up of uninitialised variables and migrate to consumes. New GEN-SIM (after pre4) we will do for geometry. These RelVals may be compared with pre4_geant10. 

If we do not do merge now, any modification for SIM should be done separately in 2 branches (7_1_X and GEANT10). We should do these modifications having in mind merging of branches at any moment. I would expect more problems with this strategy.

**Comment by civanch** [comment]
@davidlange6 , @ktf,
It seems that 7_1_0_pre4_GEANT10 is working - RelVals are in progress. It would be good to merge GEANT10 branch to 7_1_X in order to continue technical improvements (consumes migrations and others).

**Comment by ktf** [comment]
@degano can you prepare the externals? Notice we need to pick up also 
the data files from the geant4 branch.

**Comment by ktf** [comment]
Ok, looks like merging for us is two clicks away (!). @davidlange6 waiting for your ok.

**Comment by davidlange6** [comment]
good for me.

**Comment by civanch** [comment]
Was done for 7_1_0_pre6
