### ISSUE TITLE
Update htcondor to 8.8.1/8.8.2

### ISSUE THREAD

**Issue by khurtado** [cms-sw/cmsdist#4877]
Schedd machines have been upgraded to 8.8.1, the condor binding should also do the same.

Note: 
8.8.2 was released 3 days ago, which include a new feature in the bindings for printing classAds in json format that some people in SI were waiting for:
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6950
If schedds are updated to that version, this package should update to that too.

This is related to:
https://github.com/dmwm/WMCore/issues/9064

**Comment by khurtado** [comment]
@davidlange6, @Dr15Jones, @smuzaffar, @fabiocos, @kpedro88 
Made the changes and it compiled successfully on `vocms055` with them.

**Comment by smuzaffar** [comment]
@khurtado , this is comp responsibility. @h4d4 shall take care of it.

**Comment by smuzaffar** [comment]
@khurtado, can we close this?

**Comment by khurtado** [comment]
@smuzaffar Yes, this has been resolved already.
