### ISSUE TITLE
addind Zstandard library

### ISSUE THREAD

**Issue by smorovic** [cms-sw/cmsdist#4947]
Zstandard is a fast compression library which outperforms zlib (gzip) in compression speed with comparable compression factor.

I recently presented benchmarks, showing slight improvement for HLT (RAW) payloads, here (slides 6-7 in particular):
https://indico.cern.ch/event/818796/contributions/3421318/attachments/1838786/3018173/compression_CMSSW_update2.pdf

I would therefore suggest to add it to the CMS distribution. Depending on this, a CMSSW PR isbeing prepared to provide Zstandard (as well as LZMA) compression option with all Streamer output modules as well as readers in the Streamer input source. Those changes are currently in the branch:
https://github.com/smorovic/cmssw/tree/zstd-106X

Latest version of the library sources is available here:
https://github.com/facebook/zstd/releases/download/v1.4.0/zstd-1.4.0.tar.gz

I found two possibilities to build only the library sources without executables:

a) regenerate makefiles with Cmake and use custom options:

cmake build/cmake -DZSTD_BUILD_CONTRIB:BOOL=OFF -DZSTD_BUILD_STATIC:BOOL=OFF -DZSTD_BUILD_TESTS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DZSTD_BUILD_PROGRAMS:BOOL=OFF -DZSTD_LEGACY_SUPPORT:BOOL=OFF -DCMAKE_INSTALL_PREFIX:STRING=/usr -DCMAKE_INSTALL_LIBDIR:STRING=lib -Dzstd_VERSION:STRING=1.4.0

make DESTDIR=%i install

b) use existing Makefile from lib directory - this in addition to "a)" also builds the static library:
cd lib/
make ZSTD_LEGACY_SUPPORT=OFF DESTDIR=%i install

Best regards,
Srecko Morovic

**Comment by davidlange6** [comment]
hi Srecko
have you compared against lz4 which is already available.
https://github.com/lz4/lz4 has some comparison benchmarks.

**Comment by smorovic** [comment]
Hi David,

Not yet. Let me look how to use API and I'll come back with measurements.

Cheers,
Srecko

**Comment by Dr15Jones** [comment]
@bbockelm FYI

**Comment by smorovic** [comment]
Hi,
I added LZ4 benchmark in new version of the presentation (slide 8):
https://indico.cern.ch/event/818796/contributions/3421318/attachments/1838786/3018173/compression_CMSSW_update2.pdf

Some details:
For pp data (compressed size /vs uncompressed size):
LZ4:           10.7 seconds, 92% (acceleration=60)
Zstandard: 11.5 seconds, 68% (level=1)

Maximum compression for LZ4: 20 seconds, 80% (acceleration=1)

LZ4 doesn't seem to be appropriate for event payload which is mostly raw data.

**Comment by bbockelm** [comment]
Yeah, LZ4 is not right for large volumes of data - it’s all about event rate.

We have a branch in hand to do this in ROOT and a summer student to use some of the more clever pieces of ZSTD.  Any reason why we shouldn’t wait on ROOT support?

Particularly, we should at least work with ROOT to reserve a constant in the header field.

**Comment by bbockelm** [comment]
Ah yes, this is for Streamer. ZSTD is likely a good choice there.

**Comment by smorovic** [comment]
Yes, it's for Streamer which uses compression API directly (with zlib). Compression in this case is done one event at the time, so payload size is 1 - 1.5 MB. It's not achieving much better ratio than zlib, but is faster.

If ROOT is getting this for Run 3, we can wait so that we don't have to package it separately.

**Comment by bbockelm** [comment]
Well, we will need it packaged in cmsdist even when ROOT adds support.  So probably can go ahead here.
