### ISSUE TITLE
Include hepdata_lib python package

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmsdist#4954]
[hepdata_lib](https://pypi.org/project/hepdata-lib/) is a tool for users to convert their ROOT files into the standard HepData format for analysis archival and distribution. It would be useful to distribute this to users in CMSSW.

**Comment by smuzaffar** [comment]
@kpedro88 , https://github.com/cms-sw/cmsdist/pull/4965 should bring hepdata-lib in to cmssw env.

**Comment by kpedro88** [comment]
thanks @smuzaffar!
