### ISSUE TITLE
ROOT build picks up new GL libraries that need to be added to the drivers file

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmsdist#5099]
Hi,

I have been installing the release with a cc7 docker image, but the 
installation fails with:

libGLX.so.0()(64bit) is needed by lcg+root+6.14.09-nmpfii5-1-1.x86_64
	libOpenGL.so.0()(64bit) is needed by lcg+root+6.14.09-nmpfii5-1-1.x86_64

I can them from the image:
[cvcms@lxcvmfs74 ~]$ docker run -it cmssw/slc7-installer:usercvcms sh -c 'ls /usr/lib64/libGLX.so.0'
/usr/lib64/libGLX.so.0
[cvcms@lxcvmfs74 ~]$ docker run -it cmssw/slc7-installer:usercvcms sh -c 'rpm -qf /usr/lib64/libGLX.so.0'
libglvnd-devel-1.0.1-0.8.git5baa1e5.el7.x86_64
[cvcms@lxcvmfs74 ~]$ docker run -it cmssw/slc7-installer:usercvcms sh -c 'ls /usr/lib64/libOpenGL.so.0'
/usr/lib64/libOpenGL.so.0
[cvcms@lxcvmfs74 ~]$ docker run -it cmssw/slc7-installer:usercvcms sh -c 'rpm -qf  /usr/lib64/libOpenGL.so.0'
libglvnd-opengl-1.0.1-0.8.git5baa1e5.el7.x86_64

What could be the issue?
Thanks,
Bockjoo

   -------------------------------------------------------------
    Visit this CMS message (to reply or unsubscribe) at:
    https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2630.html

**Comment by gartung** [comment]
The driver file, eg
http://cmsrep.cern.ch/cmssw/repos/cms/drivers/slc7_amd64_gcc810-driver.txt
needs to be updated to include libglnd libglnd-opengl as the ROOT build has decided to pick up those two libraries from the system.

**Comment by bockjoo** [comment]
libglvnd-opengl is in the common driver file, but libglvnd-glx is missing from
http://cmsrep.cern.ch/cgi-bin/cmspkg/driver/cms/slc7_amd64_common?repo_uri=cmssw
Also, line 1596 of http://cmsrep.cern.ch/cmssw/repos/bootstrap.sh is strange.
( [ -f $tempdir/$arch-driver.txt ] , a test line )
Is it a bug or some bash feature that I don't understand?

**Comment by gartung** [comment]
see https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2630/1/1/2.html
