### ISSUE TITLE
Support for different python2 and python3 versions

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#5126]
hi @smuzaffar all

i'd like to add support for different versions of python tools for python2 and python3. More and more stuff is dropping python2 support for new developments.

Do you have any thoughts as how to do that? We could start making a requirements_py3.txt file to track version updates unique to python3 and build separate packages in cases where the python2 and python3 versions differ. It seems the current infrastructure makes that not too difficult.

**Comment by davidlange6** [comment]
actually this would appear to be sufficient. It currently assumes the set of dependencies is the same for python2 and python3 - but that would be easy to change

https://github.com/cms-sw/cmsdist/compare/IB/CMSSW_11_0_X/gcc700...davidlange6:py3_190801?expand=1

**Comment by davidlange6** [comment]
also - the Requires statements for python tool dependencies outside of pip/* and python_tools.spec would still need to be adjusted.

Anyway, I can continue with that if this makes sense as a way to go

**Comment by smuzaffar** [comment]
@davidlange6 , yes looks like right direction. But I think we do not need build-with-pip.file changes. We have to have py2-XXX.file and py3-XXX.file in order to provide extra changes. So I would suggest to change pip/package.sh and dump the contents of py2-XXX.file for py2-XXX and py3-XXX.file for py3-XXX and if there is just XXX.file then dump it for both py2 and py3. So basically we need to rename all exists `pip/py2-*.file` to `pip/*.file`. If there is different dependency for Python3 then that can go in py3-*.file

**Comment by davidlange6** [comment]
> On Aug 1, 2019, at 4:19 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:
> 
> @davidlange6 , yes looks like right direction. But I think we do not need build-with-pip.file changes. We have to have py2-XXX.file and py3-XXX.file in order to provide extra changes. So I would suggest to change pip/package.sh and dump the contents of py2-XXX.file for py2-XXX and py3-XXX.file for py3-XXX and if there is just XXX.file then dump it for both py2 and py3. So basically we need to rename all exists pip/py2-.file to pip/.file. If there is different dependency for Python3 then that can go in py3-*.file
> 

My motivation was to avoid this duplication of code. - eg most of whats in py2-XXX.file will be copied to py2-XXX.file. But, right can be done that way without the build-with-pip.file changes...

**Comment by smuzaffar** [comment]
yes most of py2-XXX.file needs to be in py3-XXXX.file only if there are different py2 and py3 versions otherwise we just need XXX.file. One can keep common stuff in XXX.file and have 
py2 and py3  use `##INCLUDE XXX`

**Comment by davidlange6** [comment]
i'll try that - that sounds like it can reduce the code further.

**Comment by smuzaffar** [comment]
@davidlange6 , are you working on it? otherwise I can ask @tulamor to look in to it.

**Comment by davidlange6** [comment]
I’m not (but it’s on the todo list)

I’m certainly happy if someone else takes care of it:)




On 13 Sep 2019, at 08:22, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , are you working on it? otherwise I can ask @tulamor<https://github.com/tulamor> to look in to it.

**Comment by smuzaffar** [comment]
pkgtools now does support different py2 and py3 versions.
