### ISSUE TITLE
pyROOT enum fixes: update rootmaster to pickup merge of root-project/root#4121 ... and root-project/root#4202

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#5127]
Please update to the recent rootmaster  to check that the feature/fix needed in the context of cms-sw/cmssw#26446  actually works OK for us.

**Comment by smuzaffar** [comment]
@slava77 , latest root master is now available in CMSSW_11_0_ROOT6_X_2019-08-04-2300 and above. Can you please check if this fixes the issue.

**Comment by slava77** [comment]
@drkovalskyi  
please check if the problem with enums is solved now in (CMSSW_11_0_ROOT6_X_2019-08-04-2300)

**Comment by slava77** [comment]
> @drkovalskyi
> please check if the problem with enums is solved now in (CMSSW_11_0_ROOT6_X_2019-08-04-2300)

please let me know if the test was successful.
Thank you.

**Comment by drkovalskyi** [comment]
Yes and no. Yes because enums now get the right sign, but No because ROOT.reco.GhostMuonFromGaugeOrHiggsBoson now is wrong.
If your run /afs/cern.ch/user/d/dmytro/public/forSlava/test_pyroot.py in the old release you get:

> ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  =  -10
> pt: 1.1 	simType: 4294967292 	extSimType: 4294967286
> pt: 1.0 	simType: 4294967294 	extSimType: 4294967292

In the nightly you get
> ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  =  4294967286
> pt: 1.1 	simType: -4 	extSimType: -10
> pt: 1.0 	simType: -2 	extSimType: -4

**Comment by slava77** [comment]
```python
print "ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.GhostMuonFromGaugeOrHiggsBoson
...
    for muon in muons:
        if muon.simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson or muon.simExtType()>1e4 or muon.simExtType()<0:
            print "pt: %0.1f \tsimType: %d \textSimType: %d" % (muon.pt(),muon.simType(),muon.simExtType())
```

Do I understand correctly that the type is now recognized correctly and ```muon.simExtType()==ROOT.reco.GhostMuonFromGaugeOrHiggsBoson``` comparison is now working?

**Comment by drkovalskyi** [comment]
No, the comparison fails, because the left side that was broken and used to give 2^32-true value now gives the right value, but the right side that used to give the right value is now broken

**Comment by slava77** [comment]
ah, ok, I didn't interpret the "or" in the conditional right and thought that this was just a print issue.
I'll follow up on the ROOT ticket.

**Comment by slava77** [comment]
@Dr15Jones  @pcanal 
please check that the above behavior is not somehow a feature of FWLite-pyROOT interplay.
The compiled methods now return appropriate values, while the enum value pulled via ```ROOT.reco.``` looks wrong

**Comment by slava77** [comment]
```
>>> print "ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.GhostMuonFromGaugeOrHiggsBoson
ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  =  4294967286
```

However,
```
>>> print "ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  = ", ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson
ROOT.reco.GhostMuonFromGaugeOrHiggsBoson  =  -10
```

With this modification in the test .py file
```python
        if muon.simExtType()==ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson:
            print "pt: %0.1f \tsimType: %d \textSimType: %d" % (muon.pt(),muon.simType(),muon.simExtType())
```
I get 
```
ROOT.reco.ExtendedMuonSimType.GhostMuonFromGaugeOrHiggsBoson  =  -10
pt: 1.1         simType: -4     extSimType: -10
```

So, it looks like the problem is solved.
@drkovalskyi  
please check and confirm that this works for your needs.
Thank you.

**Comment by drkovalskyi** [comment]
I wouldn't call it solved. The result depends on whether one includes enum typename or not. We need to either make ROOT.reco.GhostMuonFromGaugeOrHiggsBoson undefined or AttributeError or fix it. Otherwise people will use it blindly without checking its value since all the enums with positive values will work in both cases like ROOT.reco.MatchedMuonFromGaugeOrHiggsBoson for example.

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
please advance to a more recent rootmaster to pick up root-project/root#4202 as well.
Please post here when a new IB with it is available.
Thank you.

**Comment by mrodozov** [comment]
@slava77 some other complications emerged after the updates, root people are fixing it (see the open PRs on root updates)

**Comment by smuzaffar** [comment]
@slava77 , @drkovalskyi can yo uplease check latest ROOT6 IB again? We have updated root yesterday which contained some fixes in pyROOT for enums.

**Comment by slava77** [comment]
> @slava77 , @drkovalskyi can yo uplease check latest ROOT6 IB again? We have updated root yesterday which contained some fixes in pyROOT for enums.

please see https://github.com/cms-sw/cmssw/pull/26446#issuecomment-527567587
sorry for disorganized feedback

**Comment by smuzaffar** [comment]
assign externals
thanks @slava77 . Once we have confirmation from @drkovalskyi  then I will close this issue.

**Comment by slava77** [comment]
we have a confirmation now that the enums are working now in 6.18 and root master.
I'm closing this issue.
