### ISSUE TITLE
Backport hls external to CMSSW_10_6_X

### ISSUE THREAD

**Issue by aperloff** [cms-sw/cmsdist#5178]
I would like to request that the hls external, recently added to CMSSW_11_0_X, be backported to CMSSW_10_6_X. This external is very useful for development of the phase 2 L1 trigger code, much of which isn't ready for the change to CMSSW_11_0_X.

**Comment by fabiocos** [comment]
@aperloff what is the plan to move developments to 11_0_X? In principle this backport is harmless, as  it will not affect anything else, but I would like to avoid this as a long term philosophy, 10_6_X is not meant for development any more

**Comment by aperloff** [comment]
@fabiocos the plan is to eventually move to 11_0_X. However, that is a long way off. I need to wait for two different groups to rebase their branches before I can use 11_0_X, and that is unlikely to happen before the L1 trigger TDR is published. In the meantime, development of the L1 trigger software/firmware can't come to a halt.

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cmsdist/pull/5182

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals
