### ISSUE TITLE
Rucio setup destroys the python path

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#5199]
#4856 works for just the Rucio client, but apparently other things are taken out of the path. I've noticed the path no longer works for openstack commands. Others (more seriously) report that the GFAL2 tools are removed from the path.

Can this be fixed?

**Comment by belforte** [comment]
It is a well known thing that CMSSW setup conflicts with grid tools.
One can fix pythonpath, but there's always the danger that e.g. some grid client depends on incompatible binaries, code is not pure python there (and even there there's no
guarantee long term of coordinated migration to different python versions).
Do we really want/need Rucio client to be accessible within CMSSW environment ?
FWIW, CRAB client deals with this by forking calls to external grid client as subprocesses with scram unsetenv prepended to the command. It is more a workaround then a solution, but.. so far, so good.

**Comment by smuzaffar** [comment]
rucio setup set its own python/pip and dependencies and yes if mix env then it will fail. I do not see any easy way to avoid it

**Comment by belforte** [comment]
do you mean that pip install rucio-client already breaks gfal ?

**Comment by smuzaffar** [comment]
rucio client depends on long list of externals packages e.g see /cvmfs/cms.cern.ch/rucio/1.20.2/lib/python2.7/site-packages plus our external python which can bring in different version of openssl etc. So yes ones you have setup rucio client env it can break gfal

**Comment by belforte** [comment]
OTOH Diego C. (CC-ed) has apparently manged to use rucio client and gfal,
and so I presume many ATLAS people.
One thing is CVMFS vs. PIP (CMS probem, I fear), the other is Rucio breaks
gfal (Rucio problem, I'd say).

**Comment by clelange** [comment]
CMSSW (I checked CMSSW_11_X) currently doesn't come with [gfal2-python](https://pypi.org/project/gfal2-python/) while it is available in the system python that comes with CC7 on lxplus. Since @dciangot's python scripts require the gfal2 python module, we should either have this module installed as part of CMSSW or rucio. Which one do you think is better?

I didn't observe that the modules (rucio-client and gfal2) conflict. Since both the CMSSW and the rucio setup scripts explicitly set (or expand) the `$PYTHONPATH`, which on vanilla lxplus is empty and therefore points to the system defaults, gfal2 just disappears (since the `$PYTHONPATH` does not contain `/usr/lib64/python2.7/site-packages` anymore).

**Comment by clelange** [comment]
How should we proceed? If there's no need for gfal2-python in CMSSW, I guess it's best to install it as part of the rucio installation. I've therefore created a PR to do that (hopefully in the correct repository): https://github.com/cms-sw/cms-bot/pull/1210

**Comment by belforte** [comment]
Sounds like one will end up with two versions of gfal2-python, one in /usr/lib/python2.7/site-packages and one in cvmfs.

**Comment by smuzaffar** [comment]
agree with @belforte , adding more packages in rucio client is asking for more trouble.

**Comment by clelange** [comment]
So you prefer to have users rely on their python packages system installation for tools that will eventually be available for use for everyone? Wouldn't it be better to have control over that and set up tests to check that things don't break with the additional installation of gfal2? And/Or check with the rucio developers to let them know that we intend to use gfal2 and if they expect any issues with that?

**Comment by smuzaffar** [comment]
the problem is we are going in a direction that we want a tool to setup env for all the possible tools a user can use. This is not going to end any where.

**Comment by clelange** [comment]
OK, my understanding had been that the tools developed by @dciangot were eventually supposed to become centrally supported tools.
Anyway, would you agree with extending the `$PYTHONPATH` in https://github.com/cms-sw/cms-bot/blob/master/rucio/setup.sh#L13 by appending `/usr/lib64/python2.7/site-packages/` to the end so that these tools would at least work on the standard lxplus7 installation? This would pick up the system installation of gfal2 and should work for all python2.7 installations. A later change to python3 would require this to be changed.
Independently, I think this issue can be closed.

**Comment by davidlange6** [comment]
> On Oct 17, 2019, at 10:12 AM, Clemens Lange <notifications@github.com> wrote:
> 
> OK, my understanding had been that the tools developed by @dciangot were eventually supposed to become centrally supported tools.
> Anyway, would you agree with extending the $PYTHONPATH in https://github.com/cms-sw/cms-bot/blob/master/rucio/setup.sh#L13 by appending /usr/lib64/python2.7/site-packages/ to the end so that these tools would at least work on the standard lxplus7 installation? This would pick up the system installation of gfal2 and should work for all python2.7 installations. A later change to python3 would require this to be changed.
> Independently, I think this issue can be closed.

Dangerous at best even for python2 (as it will override randomly cms python versions depending on whats installed) - however, we are also at the point of supporting python3 already in cmssw, so using PYTHONPATH does not work in the production environment...

**Comment by clelange** [comment]
OK, thanks, I guess we'll have to go with a custom setup script for the CMS rucio tools that encapsulate the bare rucio setup.

**Comment by smuzaffar** [comment]
using system python to install rucio allows `gfal-*` tools to run . We are currently testing this https://github.com/cms-sw/cms-bot/issues/1321 
 
Note that existsing rucio setup and new one based on system python only work for SLC7.

**Comment by clelange** [comment]
Alright, thanks for picking that up again. Looking forward for instructions on using rucio with CMSSW setup.

**Comment by smuzaffar** [comment]
rucio client using system python is now available on cvmfs . As for the old rucio setup, this only works for SLC7 and with system python.

[a]
```
> source /cvmfs/cms.cern.ch/rucio/setup.sh
rucio 1.22.7
> gfal-stat srm://dpmhead-rc.cern.ch:8446/srm/managerv2?SFN=/dpm/cern.ch/
  File: 'srm://dpmhead-rc.cern.ch:8446/srm/managerv2?SFN=/dpm/cern.ch/'
  Size: 0	directory
Access: (0755/drwxr-xr-x)	Uid: 47	Gid: 47	
Access: 1970-01-01 01:00:00.000000
Modify: 2019-03-14 18:05:18.000000
Change: 2020-06-08 11:27:15.000000
```

**Comment by smuzaffar** [comment]
fixed
