### ISSUE TITLE
Add CppCheck static-analysis tool

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#5217]
@mrodozov @tulamor can you please add https://github.com/danmar/cppcheck to cmssw externals. Its a static-analysis tool for C/C++ code

**Comment by fabiocos** [comment]
@smuzaffar @tulamor what is the purpose of this addition of another tool, on top of what we already have? Which are the unique new features that it is adding?

**Comment by smuzaffar** [comment]
It is just another c++ static analyzer tool. Few months ago we suggested to look in to it  to see if it catches more bugs and security issues ( http://cppcheck.sourceforge.net/ ). Looks like it is not relocateable so there is no point including it in cmssw.
