### ISSUE TITLE
Update millepede version

### ISSUE THREAD

**Issue by adewit** [cms-sw/cmsdist#5307]
Dear experts, 
[cc @mmusich and @dmeuser]
We would like to update to a more recent release of millepede than is currently included as an external. As the last time an update was made was several years ago, and the person who took care of it at the time has since left CMS, we're not 100% sure of the procedure. Is all there is to it to update this file: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/master/millepede.spec with the version of the programme that we want to include? Is there a way for us to test locally that the correct version is being included, or do we fully rely on the CI tests once a PR is made? Any pointers would be appreciated.

**Comment by fabiocos** [comment]
assign alca

**Comment by fabiocos** [comment]
@adewit if you want to test a new external version you may follow the the instructions https://twiki.cern.ch/twiki/bin/view/CMS/SDTExternalsWithCMSSW

I see that @mrodozov has already started an update

**Comment by mmusich** [comment]
@fabiocos @mrodozov thanks!
For my education: how can we tell once the update in the externals is available in an IB?

**Comment by fabiocos** [comment]
You may monitor the CMSDIST IB content in the menus now available in the IB page https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_0_X (if this is the question), and of course see whether update https://github.com/cms-sw/cmsdist/pull/5309 is integrated (as soon as it enters the branch the IB will pick it)

**Comment by mrodozov** [comment]
Once the PR is merged - it goes into the following IB. You can also check from the IB page 
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_0_X
and in every IB section there is a "CMS dist" tab , where "Commits" go, first are the cmssw changes tabs (Default, ROOT6, DEVEL_X, PY3 etc) and the last one is always CMS dist which shows for that 
IB what went into externals.
