### ISSUE TITLE
update root 6.14 for 10_6_X to solve enum issues in pyroot

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#5313]
This is ~currently a heads up for~ request to merge features added in root-project/root#4592 in cms-sw/root and update 10_6_X to it.
These are available in root-project:v6-14-00-patches since Oct 30.

**Comment by slava77** [comment]
the fix in the enums was now merged in root-project:v6-14-00-patches.
Please investigate possibility to merge this and apply for 106X.

**Comment by fabiocos** [comment]
@slava77 in principle I am ok in backporting the root 6.14 patch, once we have validated the master pre-release where it has been first merged

**Comment by slava77** [comment]
> @slava77 in principle I am ok in backporting the root 6.14 patch, once we have validated the master pre-release where it has been first merged

sounds good.
Do I understand correctly that it may be ready to go by Nov 25? (including/assuming pre12 in 2 weeks and relval reports a week after)

**Comment by fabiocos** [comment]
it looks like as a reasonable timescale, do you see a problem with this?

**Comment by slava77** [comment]
> it looks like as a reasonable timescale, do you see a problem with this?

no problem, just picking a date when to set a reminder

**Comment by slava77** [comment]
however, does this timeline mean that pre12 is going to be built with 6.14?

**Comment by fabiocos** [comment]
I would say so, ROOT 6.18 validation would likely not be fully final by this week. In any case we have still a couple of pre-releases (one open) before building 11_0_0.

**Comment by slava77** [comment]
@fabiocos 
I wanted to check on the status of this request/issue.
Please clarify if the 6.14 tests in pre12 were OK and we can update root for 10_6_X.
Thank you.

**Comment by fabiocos** [comment]
@slava77 the pre12 validation is still ongoing, as soon as there is a reasonable green light we will integrate it. Is there a specific urgent use case for this?

**Comment by slava77** [comment]
> @slava77 the pre12 validation is still ongoing, as soon as there is a reasonable green light we will integrate it. Is there a specific urgent use case for this?

There is no urgent use case, I was simply reacting to the reminder set based on the preceding discussion.

**Comment by slava77** [comment]
I see that 10_6_7 has #5319 included.
I checked that the test script to test the negative enums works in this release (and it does not in 10_6_6).
@drkovalskyi   please pass this along to the POG.

**Comment by smuzaffar** [comment]
this has been fixed.
