### ISSUE TITLE
External request: CondFormats/JetMETObjects/data

### ISSUE THREAD

**Issue by jstupak** [cms-sw/cmsdist#533]
I would like to request creation of an external for CondFormats/JetMETObjects/data, as suggested by @ktf and @slava77.  This external will contain 2 ROOT files for quark-gluon tagging and 2 for pileup jet ID, as part of the "jet toolbox":

http://home.fnal.gov/~jstupak/files/ReducedHisto_2012.root
http://home.fnal.gov/~jstupak/files/ReducedHisto_2012_CHS.root

 http://home.fnal.gov/~jstupak/files/TMVAClassificationCategory_JetID_53X_chs_Dec2012.weights.xml
http://home.fnal.gov/~jstupak/files/TMVAClassificationCategory_JetID_53X_Dec2012.weights.xml

**Comment by slava77** [comment]
any progress here?
It looks like a DB solution in https://github.com/cms-sw/cmssw/pull/2820 may take a while

**Comment by slava77** [comment]
@ktf Giulio?
ping

**Comment by ktf** [comment]
@degano can you look into this? Thanks.

**Comment by ghost** [comment]
Done in #545.
