### ISSUE TITLE
DD4hep: update to master

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmsdist#5341]
Please, update the dd4hep external to its master branch. This fixes a bug in G4 converter for Polyhedra.

Thanks.

**Comment by kpedro88** [comment]
@ianna please specify the commit hash, since master is not a stable reference.

**Comment by ianna** [comment]
https://github.com/AIDASoft/DD4hep/pull/593

**Comment by kpedro88** [comment]
Looks like the actual hash in upstream is: https://github.com/AIDASoft/DD4hep/commit/f1c86074ad0bf44686bf61131ebf92bc1d233734

**Comment by smuzaffar** [comment]
@ianna  https://github.com/cms-sw/cmsdist/pull/5342  should bring in the latest changes
