### ISSUE TITLE
Backport cms-git-tools to CMSSW_9_4_X and earlier releases

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#5343]
FYI, @fabiocos , @kpedro88, @fwyzard 
Recently we have noticed that building a patch release for 9.3.X was not possible as we were not able to get the cmssw sources. It failed with error message [a].  We have very old version of https://github.com/cms-sw/cms-git-tools available in 9.4.X and earlier release cycles. If we use latest cms-git-tools then it works [b]. Basically the changes [c] fixes the issue.

I would suggest to back port latest cms-git-tools to all releases.

[a]
https://cmssdt.cern.ch/jenkins/view/Jenkins%20Tests/job/jenkins-test-patch-checkout/25/console

[b]
https://cmssdt.cern.ch/jenkins/view/Jenkins%20Tests/job/jenkins-test-patch-checkout/27/console

[c]
https://github.com/cms-sw/cms-git-tools/compare/ac859e96a7fa05f79f9a357c7c7a996a53855b23...bc99713ee184ebeaed27a30401f425de6d5b26b5

**Comment by fabiocos** [comment]
As discussed, there should be no dependency in this update on the exact git version in each release, so if this allow the builds to work smoothly I would suggest to do the backport for all active old cycles, and pick them at the first needed build.

**Comment by smuzaffar** [comment]
this has been done for all release cycles.
