### ISSUE TITLE
Request for FastJet Contrib in 5_3_X

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmsdist#538]
Hi,

Would it be possible to include the FastJet Contrib package in 5_3_X releases? It has already been added to 7_1_X releases (#369 and #393). This would simplify development and testing of new tools as well as backporting certain features from more recent releases.

Thank you,
Dinko

**Comment by ghost** [comment]
@ferencek if this package is still desired in 5_3_X should be discussed at ORP meeting.

**Comment by ferencek** [comment]
@degano It would certainly be helpful to have it in 5_3_X since in that way all the plugins included in the FastJet Contrib package would be available for testing in the 5_3_X releases (it would also simplify backporting some of the tools included in more recent releases). In fact, it would also be helpful to have it for 7_0_X. However, I'm not sure how complicated this would be from the technical point of view. When do ORP meetings take place?

**Comment by ktf** [comment]
I assume this is taken care for? Reopen if not the case.

**Comment by ferencek** [comment]
Most developments at this point have moved to newer releases so this request is no longer essential. Thank you.
