### ISSUE TITLE
Return back Geant4 10 MT build for the GEANT10 branch

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#542]
Geant4 10 has been merged to the main development branch using sequential build of geant4 10.0p01. For multi-threaded developments we need to return back previous multi-threaded build of Geant4 10.0p01 with cms private patch of build options for the GEANT10 branch.

**Comment by ktf** [comment]
@davidlt can you take care of this, since you did it in the first place? Thanks.

**Comment by davidlt** [comment]
Wil do.

**Comment by davidlt** [comment]
Done now, should be in 1400 IB.

**Comment by civanch** [comment]
Was done long ago.
