### ISSUE TITLE
External Request for RecoLocalCalo/EcalDeadChannelRecoveryAlgos/data/NNWeights/

### ISSUE THREAD

**Issue by argiro** [cms-sw/cmsdist#543]
As per @slava77 suggestion, we are requesting an external package to store the text files now contained at:

https://github.com/dmitrijus/cmssw/tree/neural-corrections/RecoLocalCalo/EcalDeadChannelRecoveryAlgos/data/NNWeights

these are the weights of neural networks used for recovery of isolated single channels in Ecal

**Comment by ghost** [comment]
Done in #544.
