### ISSUE TITLE
Update frontier client to version 2.9.0

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#5487]
Please update the frontier client for new CMSSW releases to version 2.9.0.  Here are the [release notes](http://frontier.cern.ch/dist/clientreleasenotes.txt).  I don't think there's anything particularly urgent enough to backport them to older CMSSW release lines, but if there are some that are still actively being updated it could be helpful to backport it there, in particular for the support of IPv6 addresses in URLs.

**Comment by smuzaffar** [comment]
- [ ] CMSSW_11_1_X https://github.com/cms-sw/cmsdist/pull/5488
