### ISSUE TITLE
Update Rucio client in CMSSW/CVMFS

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#5506]
Following #4856 can we get the update to the most recent Rucio client 1.21.6 (1.21.7 is coming Feb 3).

**Comment by ericvaandering** [comment]
@smuzaffar

**Comment by smuzaffar** [comment]
@bockjoo , can you please install this Rucio client version on CVMFS

**Comment by smuzaffar** [comment]
@ericvaandering , thanks to @bockjoo , rucio client verison 1.21.6 is now available
```
> source /cvmfs/cms.cern.ch/rucio/setup.sh
> rucio --version
rucio 1.21.6
```
