### ISSUE TITLE
pr 111X (110X) , UTM 0.7.5 in cms-externals

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmsdist#5555]
Dear @smuzaffar, 
(attn @boudoul)

New UTM for 11_1_X, and backport to 11_0_X
========================
This is a request to add a new version of the UTM library, tag utm_0.7.5, [1] needed for L1T to be included in CMSSW_11_1_X, and backport to 11_0_X.  This UTM library is intended to be used for MWGR#1.

Description:
=========
The patch fixes the bunch crossing offset issue concerning external signals and centrality signals (+/- offset was ignored). This bug was introduced in version 0.7.0.  The patch also contains fix of offending syntax. 

Run Coordination/Operations note:
==========================
This UTM library is intended to be used for tests in MWGR#1 if can make it in time. The UTM library is used for O2O (p5), and GlobalTrigger emulation, performed in HLT, OnlineDQM, OfflineDQM.  So deploying the new CMSSW with the updated UTM library requires operations coordination.

[1]
https://gitlab.cern.ch/cms-l1t-utm/utm/tree/utm_0.7.5

**Comment by boudoul** [comment]
Dear @rekovic 
MWGR is starting in less than 48h  ...

**Comment by rekovic** [comment]
Hi @boudoul Thanks!
I imagine this is very tight to make all these changes in such a short time.
In any case, we need to merge this external library in CMSSW, and test it whenever becomes possible.

**Comment by boudoul** [comment]
Hi @rekovic , maybe the best is to come in meetings where the plans of subdetectors and subsystems for MWGRs (present and future)  are discussed. Last week, we had a run meeting (tuesday) and a operation meeting (friday), I don't remember from your L1T colleagues any mention of this - 

Still,  let's try to support at best your request and ease the tests by scheduling it. What about explaining us the context and the goal etc.. tomorrow at the run meeting (starting from 3pm  https://indico.cern.ch/event/890074/ ) ? Do you think you can prepare a couple of slides on this topic to give us all details we need to know? It will likely be too short to be integrated for this MWGR, but let's discuss it and see what we can do. 

Thanks.
