### ISSUE TITLE
add '## INITENV +PATH LD_LIBRARY_PATH %{i}/lib64' to libjpeg-turbo.spec

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmsdist#5574]
libjpeg-turbo puts its libraries into %{i}/lib64.  The spec is missing the corresponding INITENV, so LD_LIBRARY_PATH isn't getting set correctly.  This isn't a problem within the full CMSSW environment, but it breaks independent usage of ROOT.  This can be reproduced via

```
source /cvmfs/cms.cern.ch/slc7_amd64_gcc820/lcg/root/6.12.07-pafccj3/etc/profile.d/init.sh
root -l
root [0] gSystem->Load("libASImage.so")
cling::DynamicLibraryManager::loadLibrary(): libjpeg.so.8: cannot open shared object file: No such file or directory
(int) -1
root [1] .q
```

**Comment by smuzaffar** [comment]
thanks @dan131riley . This change is already par of TF 2.1 update here https://github.com/cms-sw/cmsdist/pull/5525/files#diff-e18d5995de3e9033825093b1611080b6R2
