### ISSUE TITLE
backport of CalibPPS/ESProducers to CMSSW_10_6_X

### ISSUE THREAD

**Issue by jan-kaspar** [cms-sw/cmsdist#5575]
We would like to ask backporting the changes from
  https://github.com/cms-data/CalibPPS-ESProducers/pull/2
to the CMSSW_10_6 cycle.

In particular that the .../data/CalibPPS/ESProducers points to the V01-01-00 version.

**Comment by smuzaffar** [comment]
@jan-kaspar , I guess we need this for 11.0.X too?
@mrodozov , can you please take care of it
