### ISSUE TITLE
Update YODA and Rivet 

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmsdist#5587]
assign generators
we are updating yoda and rivet recipes (see https://github.com/cms-sw/cmsdist/pull/5586)
as we had to patch yoda (see https://github.com/cms-sw/cmsdist/pull/5531/files , yoda file)
and we thought let's ask if we should update to newer rivet and yoda versions

**Comment by agrohsje** [comment]
Let me add @intrepid42 and @xjanssen. They should further comment.

**Comment by mseidel42** [comment]
Hi Mircho, please feel free to go ahead and update to Rivet 3.1.0 and Yoda 1.8.0. Let me know if there are compilation or runtime errors (in the unit tests) that require updates in RivetInterface!

**Comment by mrodozov** [comment]
#5586 is updated. rivet and yoda build standalone, lets see cmssw
