### ISSUE TITLE
LLVM distribution

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#5627]
While working with the Intel fork of LLVM, I've been trying to use as much as possible the same flags that we use to build LLVM for CMSSW:
https://github.com/cms-sw/cmsdist/blob/1cb8199fb63b14de5de873c56b0bfb5afcdf6fa5/llvm.spec#L40-L50

This `-DLLVM_LIBDIR_SUFFIX:STRING=64` has been an issue, but after discussing with the developers should be getting fixed (intel/llvm#1228, intel/llvm#1261).

This `-DBUILD_SHARED_LIBS:BOOL=ON` has been an issue, after reporting it was fixed (intel/llvm#1259) at least for the LLVM/clang *build*, but not for the *installation* (see intel/llvm#1229).
I was about to start working on the installation part, but reading the LLVM documentation I found a couple of mentions that `BUILD_SHARED_LIBS` should not be used when building a distribution:
   - from [CMake.html](https://llvm.org/docs/CMake.html):
     > **Note**
     > `BUILD_SHARED_LIBS` is only recommended for use by LLVM developers. If you want to build LLVM as a shared library, you should use the `LLVM_BUILD_LLVM_DYLIB` option.

   - from [BuildingADistribution.html](https://llvm.org/docs/BuildingADistribution.html#general-distribution-guidance):
     > **Warning**
     > One very important note: Distributions should never be built using the `BUILD_SHARED_LIBS` CMake option. That option exists for optimizing developer workflow only. Due to design and implementation decisions, LLVM relies on global data which can end up being duplicated across shared libraries resulting in bugs. As such this is not a safe way to distribute LLVM or LLVM-based tools.

   - more from [BuildingADistribution.html](https://llvm.org/docs/BuildingADistribution.html#special-notes-for-library-only-distributions):
     >*Special Notes for Library-only Distributions*
     > One of the most powerful features of LLVM is its library-first design mentality and the way you can compose a wide variety of tools using different portions of LLVM. Even in this situation using `BUILD_SHARED_LIBS` is not supported. If you want to distribute LLVM as a shared library for use in a tool, the recommended method is using `LLVM_BUILD_LLVM_DYLIB`, and you can use `LLVM_DYLIB_COMPONENTS` to configure which LLVM components are part of libLLVM.

At this point, before trying to fix the SYCL installation when `BUILD_SHARED_LIBS` is used, I'm left wondering: why do we use it at all ?

---

On a separate note, I see that we enable CUDA support only on x86_64:
https://github.com/cms-sw/cmsdist/blob/1cb8199fb63b14de5de873c56b0bfb5afcdf6fa5/llvm.spec#L51-L56

Now that CUDA is available also on ARM and Power, should we try building support for it in LLVM/clang on those architectures as well ?

**Comment by fwyzard** [comment]
@smuzaffar @mrodozov what do you think ?

**Comment by smuzaffar** [comment]
@fwyzard , do not remember why BUILD_SHARED_LIBS was used instead of LLVM_BUILD_LLVM_DYLIB. Yes looks like  BUILD_SHARED_LIBS is more for developers of LLVM. 

@mrodozov , can you please update llvm.spec to use LLVM_BUILD_LLVM_DYLIB and enable cuda support for all archs

**Comment by fwyzard** [comment]
The latter is done in #5628 .

**Comment by mrodozov** [comment]
yes certainly

**Comment by smuzaffar** [comment]
@fwyzard , are you happy with the changes, can we close this issue?

**Comment by fwyzard** [comment]
The build looks fine.

The installation puts a lot of static libraries under `$LLVM_BASE/lib64`.
Do we have a way to check if we actually need them to use clang and the orther tools ?

**Comment by smuzaffar** [comment]
I think only simple way is to re-compile full CLANG cmssw under strace and see if any of the statis libs are loaded. @mrodozov  can you please try that?

**Comment by fwyzard** [comment]
Maybe it would be easier to make a build where we delete all `lib64/*.a` files (except for `libomptarget-nvptx.a` that has to be static) and check if we can still use llvm, clang and the tools as usual ?

**Comment by smuzaffar** [comment]
sounds much better. @mrodozov can you please try this?

**Comment by davidlange6** [comment]
hi @smuzaffar @mrodozov - unfortunately this solution breaks libraries using cmake and depending on llvm. 

CMake Error at /cvmfs/cms-ib.cern.ch/nweek-02646/slc7_amd64_gcc820/external/llvm/10.0.0-gchjei/lib64/cmake/llvm/LLVMExports.cmake:830 (message):
  The imported target "LLVMDemangle" references the file

     "/cvmfs/cms-ib.cern.ch/nweek-02646/slc7_amd64_gcc820/external/llvm/10.0.0-gchjei/lib64/libLLVMDemangle.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/cvmfs/cms-ib.cern.ch/nweek-02646/slc7_amd64_gcc820/external/llvm/10.0.0-gchjei/lib64/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

**Comment by mrodozov** [comment]
The file libLLVMDemangle.a was indeed removed, because we wanted to have the static libs removed. 
Is this solution doesn't work for something to depend on LLVM and use the cmake config at the same time ?
We are deliberately removing the *.a objects after the install. #6144 is doing that.

**Comment by fwyzard** [comment]
David, what package is failing ?
Any chance to make it use the shared libraries instead of the static ones ?

**Comment by davidlange6** [comment]
its include-what-you-use - but its irrelevant I think. I believe a CMakeLists.txt file with

```find_package(LLVM CONFIG REQUIRED)```

is sufficient to trigger the error.

Eg, our llvm cmake file (eg, /cvmfs/cms-ib.cern.ch/nweek-02646/slc7_amd64_gcc820/external/llvm/10.0.0-gchjei/lib64/cmake/llvm/LLVMExports.cmake) says that a list things will get found as libraries - but a bunch don't exist given the rm *.a - eg, LLVMDemangle.

```foreach(_expectedTarget LLVMDemangle LLVMSupport LLVMTableGen llvm-tblgen LLVMCore 
......
```
maybe there is some way to turn off this check and configure by hand?  But better that our build is self consistent.
