### ISSUE TITLE
managing python packages with similar names

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#5663]
@smuzaffar 

I was looking at updating some python packages... we have a set where <name> and <name>2 exist (these are coming back together but typically only in python3).. To move forward we need both of packages in at least one example - but this seems to trigger a bug:

Here is an example

--- a/pip/requirements.txt
+++ b/pip/requirements.txt
@@ -219,7 +219,8 @@ Send2Trash==1.5.0
 simplegeneric==0.8.1
 singledispatch==3.4.0.3
 six==1.14.0
-smmap2==2.0.5
+smmap==3.1.0
+smmap2==3.1.0
 soupsieve==1.9.5
 sqlalchemy==1.3.11
 stevedore==1.32.0

more pip/smmap2.file 
Requires: py2-smmap

PKGTOOLS/cmsBuild --repo cms.week0 -a slc7_amd64_gcc820 -j 6 --builders 5 build py2-smmap2
Bootstrapping cmsBuild area.
Done. Setup log can be found in /build/dlange/200318/tmp/bootstrap.log.
Generated cache: external+gcc+8.2.0-pafccj
/build/dlange/200318/CMSDIST/py2-smmap#File:.spec
ERROR! File not found: /build/dlange/200318/CMSDIST/py2-smmap#File:.spec

I don't see what triggers this.... maybe you do?

**Comment by smuzaffar** [comment]
can you try re-building in fresh area or delete your tmp/specCache and re-try

**Comment by smuzaffar** [comment]
by the way, correct version to use is `3.0.1` :-)

**Comment by smuzaffar** [comment]
I do not understand why you need both of these in distribution?

**Comment by davidlange6** [comment]
I wanted to upgrade gitdb2 - properly, that mean to have gitdb==4.0.2 for python3 and gitdb2==2.0.6 for python2.

Unfortunately:
gitdb2==2.0.6 depends on smmap2
gitdb==4.0.2 depends on smmap

of course we can patch gitdb2 to depend on smmap instead of smmap2. (well, not sure I can make that replacement in a nice way, but..)

my reproducer was in a fresh area.... but trying again does give the same error.

**Comment by smuzaffar** [comment]
ah OK, if  gitdb2 explicitly requires smmap then yes we should have smmap too.
I tried build smmap and smmap2 locally and it works.

**Comment by davidlange6** [comment]
argh - never mind - I miss a end-of-line statement. (in two independent areas...)
