### ISSUE TITLE
Please upgrade frontier_client to 2.9.1

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#5672]
Please update [frontier_client](http://frontier.cern.ch/dist) to version 2.9.1.  Here are the [release notes](http://frontier.cern.ch/dist/clientreleasenotes.txt).  Please also backport it at least as far as you did 2.9.0, because that introduced a bug affecting monitoring.

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it.

**Comment by smuzaffar** [comment]
- 5.3.X: #5683
- 7.1.X: #5684
- 8.0.X: #5686
- 9.3.X: #5687
- 9.4.X: #5688
- 10.6.X: #5689
- 11.0.X: #5690
- 11.1.X: #5673

**Comment by smuzaffar** [comment]
@mrodozov , I see the backport is missing for 10.2.X . Can you please open a PR for 10.2.X?

**Comment by mrodozov** [comment]
10.2.X: https://github.com/cms-sw/cmsdist/pull/5707

**Comment by smuzaffar** [comment]
@DrDaveD , frontier cleint 2.9.1 was included in CMSSW_11_1_0_pre5. Can you please confirm that it looks good and the bug you mentioned above has been fixed for 11.1.0.pre5? After your green light we will start integrating 2.9.1 in older release cycles.

**Comment by DrDaveD** [comment]
@smuzaffar Yes the bug is fixed in CMSSW_11_1_0_pre5, looks good.
