### ISSUE TITLE
python3 and missing (?) ssl

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#5679]
hi @smuzaffar - using the latest CMSDIST to look at python packages, I run into:

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting zipp==3.1.0
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/zipp/

which eventually fails... Google suggests that we've not built python3.8 with SSL, which indeed seems to be the case:

Python 3.8.2 (default, Mar 20 2020, 19:21:40) 
[GCC 8.3.1 20190225] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/build/dlange/200321/slc7_amd64_gcc820/external/python3/3.8.2/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
>>> 

the spec file does declare the dependency, so its something not totally trivial..

**Comment by davidlange6** [comment]
However - if I force a rebuild python3 on cmsdev21, it picks up openssl properly (eg, “import ssl” works), and I can get the zipp sources…

Strange… I guess I can continue with what I was working on - but presumably there is something to fix..

On Mar 21, 2020, at 2:22 PM, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:



hi @smuzaffar<https://github.com/smuzaffar> - using the latest CMSDIST to look at python packages, I run into:

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting zipp==3.1.0
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/zipp/

which eventually fails... Google suggests that we've not built python3.8 with SSL, which indeed seems to be the case:

Python 3.8.2 (default, Mar 20 2020, 19:21:40)
[GCC 8.3.1 20190225] on linux
Type "help", "copyright", "credits" or "license" for more information.

import ssl
Traceback (most recent call last):
File "", line 1, in
File "/build/dlange/200321/slc7_amd64_gcc820/external/python3/3.8.2/lib/python3.8/ssl.py", line 98, in
import _ssl # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

the spec file does declare the dependency, so its something not totally trivial..

**Comment by smuzaffar** [comment]
are you building within container ? may be outside container it picked up ssl from system?

**Comment by smuzaffar** [comment]
Building inside container I get
```
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
```
while outside container ( where we have ssl devel packages installed on system)
```
checking whether compiling and linking against OpenSSL works... yes
checking for X509_VERIFY_PARAM_set1_host in libssl... yes
checking for --with-ssl-default-suites... python
```
I will check how to tell python to configure with our SSL

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
adding `--with-openssl=${OPENSSL_ROOT}` worked. I will open a PR now with the fix 
```
checking for openssl/ssl.h in /build/muz/x/w/slc7_amd64_gcc820/external/openssl/1.0.2d-pafccj... yes
checking whether compiling and linking against OpenSSL works... yes
```

**Comment by smuzaffar** [comment]
Looks like `--with-openssl` fixes the issue . 
- Building in container and without `--with-openssl`
```
> source w/slc7_amd64_gcc820/external/python3/3.8.2-cms/etc/profile.d/init.sh 
> python3 -c 'import ssl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/build/muz/x/w/slc7_amd64_gcc820/external/python3/3.8.2-cms/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```
- Building in container with `--with-openssl`
```
> source w/slc7_amd64_gcc820/external/python3/3.8.2-cms/etc/profile.d/init.sh 
> python3 -c 'import ssl'
> python3 -c 'from http.client import HTTPSConnection'
```

https://github.com/cms-sw/cmsdist/pull/5680 shoudl fix this

**Comment by davidlange6** [comment]
Thanks!

**Comment by makortel** [comment]
+1
