### ISSUE TITLE
Update LLVM 10.0

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#5703]
FYI @mrodozov

**Comment by smuzaffar** [comment]
llvm 10 is now in CLANG IBs, once new compilation warnings are all cleaned up then we will integrate it for normal IBs.

**Comment by mrodozov** [comment]
Seems more warnings are getting in compared with the already fixed :/

**Comment by smuzaffar** [comment]
we already have fixes for all of those.
