### ISSUE TITLE
Update Rucio client and Rucio config file?

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#5752]
Following #4856 can we get the update to the most recent Rucio client 1.22.2?

Also I would like to have the rucio.cfg located in $RUCIO_HOME/etc/rucio.cfg updated for what I hope is the last time. It should read:

```
# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Vincent Garonne, <vgaronne@gmail.com>, 2017
# - Eric Vaandering, <ewv@fnal.gov>, 2018

[common]
[client]
rucio_host = http://cms-rucio.cern.ch
auth_host = https://cms-rucio-auth.cern.ch
auth_type = x509_proxy
ca_cert = /etc/grid-security/certificates/
request_retries = 3
```

(The difference is the rucio and auth_host lines)

**Comment by ericvaandering** [comment]
For @bockjoo

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cms-bot/pull/1291 updates the rucio.cfg

**Comment by smuzaffar** [comment]
@bockjoo , I would suggest to add this installed via jenkins too. If agree then I will add the jenkins job.

**Comment by bockjoo** [comment]
It's been manually running. You can add it to Jenkins now.

**Comment by smuzaffar** [comment]
@ericvaandering , rucip client verison 1.22.2 is now installed. rucio.cfg is also updated cms-sw/cms-bot#1291
