### ISSUE TITLE
[PPC CC8] Cuda install without official .rpm or .run installer

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmsdist#5817]
I'm trying to get CUDA on CC8 PPC but Nvidia doesn't have rpm or the .run installer for this arch 
Since I'd expect some similarities between cc7 and cc8 I installed the cc7 rpm (using the arm config in cuda.spec) but this results in 
```
FAILED: projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/omptarget-nvptx_generated_cancel.cu.o
cd /scratch/mrodozov/build_cmssw_toolconf/BUILD/cc8_ppc64le_gcc8/external/llvm/9.0.1-cms/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src && /scratch/mrodozov/build_cmssw_toolconf/cc8_ppc64le_gcc8/external/cmake/3.14.5/bin/cmake -E make_directory /scratch/mrodozov/build_cmssw_toolconf/BUILD/cc8_ppc64le_gcc8/external/llvm/9.0.1-cms/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/. && /scratch/mrodozov/build_cmssw_toolconf/cc8_ppc64le_gcc8/external/cmake/3.14.5/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/scratch/mrodozov/build_cmssw_toolconf/BUILD/cc8_ppc64le_gcc8/external/llvm/9.0.1-cms/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/./omptarget-nvptx_generated_cancel.cu.o -D generated_cubin_file:STRING=/scratch/mrodozov/build_cmssw_toolconf/BUILD/cc8_ppc64le_gcc8/external/llvm/9.0.1-cms/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/./omptarget-nvptx_generated_cancel.cu.o.cubin.txt -P /scratch/mrodozov/build_cmssw_toolconf/BUILD/cc8_ppc64le_gcc8/external/llvm/9.0.1-cms/build/projects/openmp/libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nvptx.dir/src/omptarget-nvptx_generated_cancel.cu.o.Release.cmake
/usr/include/c++/8/type_traits(335): error: identifier "__ieee128" is undefined
usr/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/usr/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

/usr/include/c++/8/bits/std_abs.h(101): error: identifier "__ieee128" is undefined

/usr/include/c++/8/bits/std_abs.h(102): error: identifier "__ieee128" is undefined

5 errors detected in the compilation of "/scratch/mrodozov/build_cmssw_toolconf/BUILD/cc8_ppc64le_gcc8/external/llvm/9.0.1-cms/cmsdist-tmp/tmpxft_0000d51e_00000000-8_cancel.compute_70.cpp1.ii".
CMake Error at omptarget-nvptx_generated_cancel.cu.o.Release.cmake:275 (message):

```
which I guess is due to cuda binaries incompatibility. 
The question is should I put cuda stuff in conditions until they publish cc8 binaries or there is a way to hack this somehow. If I comment the three cuda related flags llvm builds fine, with all other externals
@fwyzard

**Comment by makortel** [comment]
assign core, heterogeneous

**Comment by fwyzard** [comment]
Did you try the PowerPC RHEL 7 version ?

http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux_ppc64le.run

**Comment by mrodozov** [comment]
I did. It says it's a posix script that fails on line 512 (segmentation fault)

**Comment by fwyzard** [comment]
It's the same installer as for Ubuntu 18.04, so it should support the recent C++ ABI as well (if it matters).

**Comment by fwyzard** [comment]
> I did. It says it's a posix script that fails on line 512 (segmentation fault)

Do you have a log or trace ?

**Comment by mrodozov** [comment]
> > I did. It says it's a posix script that fails on line 512 (segmentation fault)
> Do you have a log or trace ?

[cudalog.log](https://github.com/cms-sw/cmsdist/files/4616750/cudalog.log)

Nothing much, it runs the .run installed and fails

**Comment by fwyzard** [comment]
I see... hard to debug without access to a PowerPC machine :-(

**Comment by fwyzard** [comment]
How urgent is this ?

Let's see if NVIDIA pushes a new version of CUDA by the end of the week (they have a big announcement scheduled for Thursday) that solves the issue - otherwise we can try to extract the libraries from the rpms instead of the runfile.

**Comment by smuzaffar** [comment]
@mrodozov , I see thaty you had managed to install once `cc8_ppc64le_gcc8/external/cuda/10.2.89` ... so what changed that it is not building now?

**Comment by mrodozov** [comment]
> How urgent is this ?
> 
> Let's see if NVIDIA pushes a new version of CUDA by the end of the week (they have a big announcement scheduled for Thursday) that solves the issue - otherwise we can try to extract the libraries from the rpms instead of the runfile.

Well, we can have the build without the CUDA part until we solve this
I can't say it's very urgent, we are just preparing the CC8 cmssw-tool-conf to have it and clean it as we do for x86 and arm 


> @mrodozov , I see thaty you had managed to install once `cc8_ppc64le_gcc8/external/cuda/10.2.89` ... so what changed that it is not building now?

I installed the CC7 CUDA .rpm, but LLVM doesn't build with it (which is the most relevant thing depending on CUDA)

**Comment by fwyzard** [comment]
> I installed the CC7 CUDA .rpm, but LLVM doesn't build with it (which is the most relevant thing depending on CUDA)

Mhm, in that case I don't think installing from the runfile would help :-(

What were the LLVM errors like ?

**Comment by mrodozov** [comment]
If you see my initial comment, but see the first line till the end of it. It's nvptx something and then
it can't find a type:
`error: identifier "__ieee128" is undefined`

**Comment by mrodozov** [comment]
[llvmlog.log](https://github.com/cms-sw/cmsdist/files/4622712/llvmlog.log)
this is the log

**Comment by fwyzard** [comment]
I see that the error is from libomptarget .

Since we don't use OpenMP from llvm, and definitely not for offloading,
maybe you could try to work around the problem by disabling the "openmp"
target ?

(but let's wait 24 hours...)

.A

**Comment by mrodozov** [comment]
this is now working. closing it
