### ISSUE TITLE
GCC 10.1 based IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#5819]
GCC 10.1.1 is out. Lets try to setup IBs based on it

**Comment by smuzaffar** [comment]
@mrodozov , I have created IB/CMSSW_11_1_X/gcc10 branch and most of the externals are built and uploaded to `cms` repository. There are few still failing . Can you please try to get cmssw-tool-conf built for `slc7_amd64_gcc10` ?

**Comment by davidlange6** [comment]
Cool - lets see how many string-comparison based gcc version comparisons this will break...

On May 13, 2020, at 12:44 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



GCC 10.1.1 is out. Lets try to setup IBs based on it

**Comment by smuzaffar** [comment]
done
