### ISSUE TITLE
Build madgraph 2.6.7 for Centos7 releases

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmsdist#5885]
We are currently building version 2.6.7 for Centos8 releases
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/cc8/madgraph5amcatnlo.spec
which is newer than the one used in 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/madgraph5amcatnlo.spec
The question I have is can we backport 2.6.7 in Centos7 releases.

**Comment by mrodozov** [comment]
assign generators

**Comment by agrohsje** [comment]
Sorry @mrodozov  . I just discovered this thread. Can you clarify the purpose? What is this used for? In official production we currently have 2.6.5 from here: https://cms-project-generators.web.cern.ch/cms-project-generators/MG5_aMC_v2.6.5.tar.gz

**Comment by mrodozov** [comment]
for consistency with what is in cc8, since 265 is official production we'll get it in slc7 when it's updated.
