### ISSUE TITLE
Update Rucio config file

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#5894]
@bockjoo 

Like #5752. 

Can we make the config file read like this? The difference is the ca_cert line

```
# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Vincent Garonne, <vgaronne@gmail.com>, 2017
# - Eric Vaandering, <ewv@fnal.gov>, 2018

[common]
[client]
rucio_host = http://cms-rucio.cern.ch
auth_host = https://cms-rucio-auth.cern.ch
auth_type = x509_proxy
ca_cert = /cvmfs/cms.cern.ch/grid/etc/grid-security/certificates/ 
request_retries = 3
```

**Comment by bockjoo** [comment]
*@ericvaandering <https://github.com/ericvaandering>*

The config is updated. The change should appear in 30 minutes or less.

**Comment by ericvaandering** [comment]
Thanks!

Sent from a mobile device.

On Jun 1, 2020, at 15:33, Bockjoo Kim <notifications@github.com> wrote:

﻿

*@ericvaandering <https://github.com/ericvaandering>*<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ericvaandering-253E-2A&d=DwQFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=gP7ppzP9RqGZN9gq3GNdcJll4-kBKwLphWdp5CbKrMA&s=36KA1rGKq3GPdPaj_gOuekBvU0Bn72UZWPhcHLVVQQU&e=>

The config is updated. The change should appear in 30 minutes or less.
