### ISSUE TITLE
Move to ROOT6.22 for CMSSW_11_2_ROOT620 IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#5905]
We are testing root 6.20 in cmssw 11.1.X and if validation goes fine then we will include root 6.20 for 11.1.0. We are still building 11.1.ROOT620.X IBs to test root 6.20. 

We also have 11.2.ROOT620.X IBs but I would suggest to use to root 6.22 instead. So for 11.2.X we will have
- 11.2.X : based on root 6.20 (it is currently based on 6.18)
- 11.2.ROOT622.X: Based on root 6.22
- 11.2.ROOT6.X: Based on root master 

Any objections @makortel , @silviodonato , @Dr15Jones

**Comment by smuzaffar** [comment]
assign externals,core

**Comment by makortel** [comment]
I agree it would be good to start testing 6.22, but I'm a bit concerned of switching 11_2_X to 6.20 before a green light from validation.

(what have we typically done in such situations in the past?)

**Comment by smuzaffar** [comment]
Of course  we will wait for the validation first before moving 11.2.X to root 6.20

**Comment by makortel** [comment]
Excellent, then I'm ok with the plan.

**Comment by smuzaffar** [comment]
We now have ROOT622 IBs setup for CMSSW_11_2_X.
Once we have the green signal from Pdmv about ROOT620 validation then we will include that in 11.1.X and 11.2.X master IBs.
