### ISSUE TITLE
bash autocompletion does not work for command "crab"

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmsdist#5916]
after `cmsenv` now bash autocompletion works for commands `crab-prod, crab-pre, crab-dev` but not for `crab`.
```
belforte@lxplus7126/~> complete|grep -i crab
complete -o filenames -F _UseCrab_prod crab-prod
complete -o filenames -F _UseCrab_pre crab-pre
complete -F _minimal crab
complete -o filenames -F _UseCrab_dev crab-dev
belforte@lxplus7126/~>
```

autocompletion is back after `source /cvmfs/cms.cern.ch/common/crab-setup.sh` which I guess is why users did not notice:
```
belforte@lxplus7126/CRAB3> complete|grep -i crab
complete -o filenames -F _UseCrab_prod crab-prod
complete -o filenames -F _UseCrab_pre crab-pre
complete -o filenames -F _UseCrab_prod crab
complete -o filenames -F _UseCrab_dev crab-dev
belforte@lxplus7126/CRAB3> 
```
this is likely due to
https://github.com/cms-sw/cmsdist/blob/97290ce259b2530b2e026e13be5cc8ac9c19185f/crab-build.file#L73-L74

could we simply add there a line on the tune of (pseudocode):
```
if crab_type == prod then append "complete -F _UseCrab_prod -o filenames crab" to %{i}/etc/crab-bash-completion.sh
```
?

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
+core
this should be fixed via https://github.com/cms-sw/cmsdist/pull/5919
