### ISSUE TITLE
Oracle instant client - new version available

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmsdist#5950]
After the core software meeting we were going trough Oracle website
to search if there is a Arm release now available, although there isn't the client 
version moved to version 19 wrt the 12 we are using. 
The question is can we get the latest client considering compatibility issues and if you know any obstacles not letting us use it

**Comment by smuzaffar** [comment]
assign db

**Comment by smuzaffar** [comment]
@ggovi , oracle client version we are using is 12.1.0.2.0 . As @mrodozov mentioned there is newer instant client version 19 availble. Do you see any reason to not move to latest version?

**Comment by smuzaffar** [comment]
we trying building 19c ( https://github.com/cms-sw/cmsdist/pull/5959 ) but it does not yet support C++11 ABI. We have asked oracle team to provide occi build with GCC5 (for ORacle Linux 8). Once we have occi lib then we will try again. Till then lets keep this issue open.
