### ISSUE TITLE
HighFive library for handling HDF5 Files

### ISSUE THREAD

**Issue by smrenna** [cms-sw/cmsdist#5987]
I am requesting a new external for handling HDF5 for generator level calculations.
This is a header-only library available at github:

https://github.com/BlueBrain/HighFive.git

Please install tag v2.0.

I have not tested with other versions.

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care or this.

**Comment by smrenna** [comment]
Note, there is nothing to build.   It is a header only library.    I don't care about any of the tests, etc.   I don't know if I made that clear.
