### ISSUE TITLE
Include fmt external

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmsdist#6011]
The https://github.com/fmtlib/fmt has an implementation of C++20's [`std::format`](https://en.cppreference.com/w/cpp/utility/format) (and the standard appears to be based on it). Currently [no `std` implementation support `std::format`](https://en.cppreference.com/w/cpp/compiler_support#cpp20), so in the mean time it would be useful to include https://github.com/fmtlib/fmt as an external.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@smuzaffar @mrodozov Could you take a look at this at some point? Thanks.

**Comment by mrodozov** [comment]
@makortel yes, sorry sometime I miss notifications

**Comment by makortel** [comment]
No problem, thanks!
