### ISSUE TITLE
Replace MySQL-python library by something else that supports python3

### ISSUE THREAD

**Issue by amaltaro** [cms-sw/cmsdist#6025]
As described in pypi:
https://pypi.org/project/MySQL-python/

this third-party library does not support python3.

We need to check whether services depending on it are really using this library. It might be that we can simply drop it instead of adopting another package for mysql interface.

Apparently needed by: 
* crabserver
* t0
* wmagent

**Comment by amaltaro** [comment]
Feel free to assign it to myself.

**Comment by mrodozov** [comment]
https://pypi.org/project/PyMySQL ? 
I think the question is how close to your existing API calls the new tool can be, minimizing rewriting old calls to new

**Comment by amaltaro** [comment]
Yes, that might be a good option. But first I need to make sure that our services are really using this package, which I'm not really sure...

**Comment by amaltaro** [comment]
Moving this issue under the WMCore project: https://github.com/dmwm/WMCore/issues/9805
