### ISSUE TITLE
Including libstdc++fs in link  

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#6029]
We'd like to use the c++17 standard filesystem library. In gcc8 it requires adding -lstdc++fs
(this is apparently fixed in gcc9). What is the preferred way of doing this? as part of the gcc-cxxcompiler tool file or as a separate tool that one can then add to a BuildFile where it is used?

**Comment by smuzaffar** [comment]
assign core

**Comment by smuzaffar** [comment]
we should add a new toolfile stdcxx-fs (in gcc-toolfile.spec) and explicitly use it where needed.
