### ISSUE TITLE
do we need three castorShowerLibraries

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#6077]
-rw-r--r--. 1 dlange zh 570090084 Jul 15 09:47 CastorShowerLibrary_CMSSW500_Standard.root
-rw-r--r--. 1 dlange zh 165866508 Jul 15 09:48 castorShowerLibrary_QFBE.root
-rw-r--r--. 1 dlange zh 142193172 Jul 15 09:47 castorShowerLibrary.root

only the first (sadly the biggest) is used it seems..

**Comment by davidlange6** [comment]
assign simulation

**Comment by civanch** [comment]
@davidlange6 , @smuzaffar , I agree, only 1st file is used both for Run-1 and Run-2.

**Comment by davidlange6** [comment]
Could you make a PR to drop the others from cms-data?

On Jul 15, 2020, at 10:26 AM, Vladimir Ivantchenko <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> , @smuzaffar<https://github.com/smuzaffar> , I agree, only 1st file is used both for Run-1 and Run-2.

**Comment by smuzaffar** [comment]
@mrodozov , can you please take care of it?

**Comment by mrodozov** [comment]
Seems we don't have SimG4CMS-Forward in data, we have this:
https://github.com/cms-sw/cmssw/blob/master/SimG4CMS/Forward/data/download.url 
@smuzaffar could you create the repo, so I can drop the data folder from cmssw and add the only file ?

**Comment by mrodozov** [comment]
this is fixed in 6124, closing
