### ISSUE TITLE
HDF5 1.10.6 with parallel support

### ISSUE THREAD

**Issue by sabasehrish** [cms-sw/cmsdist#6123]
We need parallel support to the updated hdf5 1.10.6 ( update request was made in #6087). 
I checked in include/H5pubconf.h, and see the following, can I request to rebuild HDF5 with parallel support? 
/* Define if we have parallel support */
/* #undef H5_HAVE_PARALLEL */

**Comment by mrodozov** [comment]
Certainly, so what do I have to put in the header, 

`#define H5_HAVE_PARALLEL` 
?

**Comment by smuzaffar** [comment]
@mrodozov , you need to configure it with `--enable-parallel`  option ( please see the details https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/release_docs/INSTALL_parallel )
