### ISSUE TITLE
libunwind (dependency in igprof) is not setup with CMSSW in 10_6_X

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#6131]
```
cmsrel CMSSW_10_6_X_2020-07-29-2300
cd CMSSW_10_6_X_2020-07-29-2300/src
cmsenv
igprof -pp -o pp.gz -z -d -t top top
```

leads to 
```
error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory
```

```
source /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/external/libunwind/1.2.1-pafccj/etc/profile.d/init.sh
```
apparently solves the problem, but I don't expect a manual fix to be needed

libunwind comes as a dependency in igprof 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/igprof.spec

**Comment by slava77** [comment]
assign core

**Comment by mrodozov** [comment]
This is weird because 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/igprof.spec#L8
I'm checking what is happening. If Igprof is requiring libunwind libunwind has to be available

**Comment by smuzaffar** [comment]
@mrodozov , we are missing libunwind-toolfile in 10.6.X, please include it and add it in cmssw-tool-conf.spec

**Comment by smuzaffar** [comment]
+core
#6135 should fix this
