### ISSUE TITLE
Update OpenMPI to version 4.0.x

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#6132]
Hi,
CMSSW is bundled with  OpenMPI version 2.1.5, which is marked as "retired" on the OpenMPI pages:
![image](https://user-images.githubusercontent.com/4069793/89121641-cd378a80-d4c0-11ea-9a07-28999b4f6b8e.png)

Shall we move to the current release series, OpenMPI 4.0.x ?
The latest release is [version 4.0.4](https://www.mail-archive.com/announce@lists.open-mpi.org/msg00129.html), from June 2020.

**Comment by mrodozov** [comment]
once I fix this #6128 and #6119 I'll get it

**Comment by smuzaffar** [comment]
done

**Comment by fwyzard** [comment]
Thank you :+1:
