### ISSUE TITLE
Error rebuilding IB?

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#6219]
Hi @smuzaffar @mrodozov 
I'm trying to rebuild CMSSW_11_2_CXXMODULE_X_2020-09-07-2300 with a fix, but I've run into two problems - have you seen these?

 1) ```PKGTOOLS/cmsBuild --weekly -a slc7_amd64_gcc820 -j 16 -k build cmssw``` led to cmsBuild rebuilding root. I have changed only cmssw.spec and there are no commits to CMSDIST since the IB. week1 is getting correctly picked up as the correct cache.

 2) Then of course the dependencies build - however, the fastjet build dies (reproducibly) with

```
/build/dlange/200908/BUILD/slc7_amd64_gcc820/external/fastjet/3.3.4/fastjet-3.3.4/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [aclocal.m4] Error 127
error: Bad exit status from /build/dlange/200908/tmp/rpm-tmp.Y5Jtf0 (%build)


RPM build errors:
    Bad exit status from /build/dlange/200908/tmp/rpm-tmp.Y5Jtf0 (%build) 
```

**Comment by davidlange6** [comment]
It looks like adding

```
autoreconf -f -i
```

Before configure solves my second issue (which was what was blocking me). Reasons not to commit this?

**Comment by smuzaffar** [comment]
@davidlange6 
1. Was your build area initialized last week? It  could be that it was setup to use cms.week0 and now it is cms.week1? Note that `--weekly` pints to current week. This week it is `cms.week1` and last week it was `cms.week0`

2. You already found the solution. I think it worked for IBs as version of autotools on build nodes/docker container might have matched the version 1.16.
  Correct colution is to add dependency (BuildRequires) on autotools and run `autoreconf -f -i` to re-generate the configuration

**Comment by davidlange6** [comment]
On Sep 8, 2020, at 1:53 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6>

  1.  Was your build area initialized last week? It could be that it was setup to use cms.week0 and now it is cms.week1? Note that --weekly pints to current week. This week it is cms.week1 and last week it was cms.week0


No - I started fresh today. Week1 was correctly picked up according to the logs.


  1.
  2.  You already found the solution. I think it worked for IBs as version of autotools on build nodes/docker container might have matched the version 1.16.
Correct colution is to add dependency (BuildRequires) on autotools and run autoreconf -f -i to re-generate the configuration


Ok, I did 50% of that:). I can try adding also a build dependency later.

**Comment by smuzaffar** [comment]
ah right. For (1), we are in process of migrating cmsrep server (SLC6 phase out). For this purpose I have setup a new server for IBs. I want to run this for couple of week to see the performance. Once tests are over then I will update the landb-alias cmsrep to point to new server. Please for now pass  `--server http://cmsrep03.cern.ch/cgi-bin/cmspkg`  option to cmsBuild.

**Comment by davidlange6** [comment]
ok, I think this is all understood now! Thanks.
