### ISSUE TITLE
ROOT update

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmsdist#6351]
Please, include the following PR in our ROOT external. It's instrumental in DD4hep migration. Thanks!
https://github.com/root-project/root/pull/6736

@civanch - FYI

**Comment by smuzaffar** [comment]
@ianna , I have asked @agheata  to backport the change to root v6.22 branch. Once we have it in 6.22 then we can pick it up for our 11.2.X (which is based on root 6.22)

**Comment by smuzaffar** [comment]
two root commits which were needed are now part of cmssw master IBs ( https://github.com/cms-sw/cmsdist/pull/6382 ). Today;s 11h00 IB should have latest dd4heo and updated root with two commits needed for reflected solid title setting
