### ISSUE TITLE
DD4hep update to master

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmsdist#6390]
Please update to DD4hep to master branch:
https://github.com/AIDASoft/DD4hep/pull/736

* This includes a new development in a G4 converter to handle reflected volumes CMS way (adding a prefix `_refl`)
* Fixes Assembly conversion to G4
* Removes duplicate volumes message

@dpiparo and @civanch - FYI

**Comment by smuzaffar** [comment]
@ianna  https://github.com/cms-sw/cmsdist/pull/6391 should bring in the latest dd4hep.

**Comment by smuzaffar** [comment]
@ianna , tests are finished but looks like the unit test failure is still thre https://github.com/cms-sw/cmsdist/pull/6391#issuecomment-724864651

**Comment by mrodozov** [comment]
we can get the latest DD4Hep (in any case)
