### ISSUE TITLE
cms-data/RecoTracker-TkSeedGenerator repo needed

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmsdist#6445]
We need a new data repo cms-data/RecoTracker-TkSeedGenerator for the DeepCore PR cms-sw/cmssw#32222.

@vberta once this is created, you can create a PR in the data repo to add your weight file.

**Comment by vberta** [comment]
> We need a new data repo cms-data/RecoTracker-TkSeedGenerator for the DeepCore PR [cms-sw/cmssw#32222](https://github.com/cms-sw/cmssw/pull/32222).
> 
> @vberta once this is created, you can create a PR in the data repo to add your weight file.

Thank you, I'll do that as soon as is available

**Comment by mrodozov** [comment]
@silviodonato would you create the repo ? I don't have the rights to create new repos on cms-data

**Comment by silviodonato** [comment]
@mrodozov @jpata 
here you are https://github.com/cms-data/RecoTracker-TkSeedGenerator

**Comment by jpata** [comment]
thank you Silvio! @vberta, please take note.
