### ISSUE TITLE
adding JsonCpp library

### ISSUE THREAD

**Issue by smorovic** [cms-sw/cmsdist#648]
Hi,

This library is now used internally in EventFilter/Utlities. DQM group has also expressed interest in using it (to produce json files for DQM stream merging), so I suggest to include this library as an external dependency.

Library code is located here:
http://sourceforge.net/projects/jsoncpp/files/
EventFilter/Utilities includes v0.5.0 which is a latest stable version.

Unfortunately, the source comes only with MSVC build files, so I had to create a simple make file to produce a shared library:
/afs/cern.ch/user/s/smorovic/public/jsoncpp/Makefile
(also I copied the source tar gz here)

The rpm spec should not be complicated to do. It only needs to take what is in "include", as well as a library/symlink created by make in "lib" directory.

Regards,
Srecko

**Comment by ktf** [comment]
Ciao, how about convert everything to use [`boost::property_tree`](http://www.boost.org/doc/libs/1_55_0/doc/html/boost_propertytree/parsers.html#boost_propertytree.parsers.json_parser) instead of jsoncpp?

**Comment by diguida** [comment]
@ktf 
I found the same `boost` package yesterday during the ORP meeting, but forgot to reply here: thanks for not being as absent-minded as me ;-)
I can try to give a look into it at the same time.

**Comment by smorovic** [comment]
Hi,
It looks as the reader is not thread safe, I actually manage to get a crash with two threads parsing json strings.

If you want to try:
gcc /afs/cern.ch/user/s/smorovic/public/boost_json_reader.cc -lstdc++ -lpthread

it should be possible to 'fix' that with
#define BOOST_SPIRIT_THREADSAFE
but that didn't compile with my test program...

While now we aren't parsing two json files at the same time, it is not certain that we won't at some point (depending when input source actually starts opening input data vs. other modules parsing their json definitions).

Also it doesn't format the json as nicely. For example arrays as written with boost json_writer:
[
"1",
"2"
]

With jsoncpp:
"[1,2]"

This will create a mess out of microstate arrays which will typically have a few thousand entries, so I'm afraid that boost is not an option here.

If DQM side can use boost (write_json does not seem to cause crashes from multithreaded use, AFAICT), then we can avoid adding another external, though.

**Comment by ghost** [comment]
@smorovic is there still the need of this?
Can I close this issue?

**Comment by smorovic** [comment]
Hi, @degano, it can be closed...
DQM (and HLT scalers monitoring) went with producing json files in another way.
