### ISSUE TITLE
cms-data/RecoLocalCalo-HcalRecProducers repo needed

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmsdist#6481]
A new data repo cms-data/RecoLocalCalo-HcalRecProducers would be needed for the PR https://github.com/cms-sw/cmssw/pull/32272.

cc @jeffkrupa @kpedro88 @silviodonato @qliphy

**Comment by slava77** [comment]
after noticing that the files are actually in some "generic enough" (not a private /random location) external repo (https://github.com/fastmachinelearning/sonic-models), I'm not sure we really a need an explicit copy in cms-data.
I still think that we will need the cmsdist to know about this external with some versioning in place.

**Comment by kpedro88** [comment]
It's an interesting proposal to treat sonic-models as a separate data external. For organizational purposes, it would certainly be easier on the server side to mount all the models from one place.

**Comment by davidlange6** [comment]
Presumably cms isn’t going to want to carry around everything that lands in this repo? But a data external could just pull specific files (or a tag etc) from it and avoid the maintenance duplication. 

But then these files need to stay around and not get randomly cleaned or reorganized..

**Comment by makortel** [comment]
Do we want to set a precedent that CMS-specific ML models to be used in CMSSW can be placed in "random places" outside of CMS' control (even if an update of the data external would require an update in cmsdist)?

**Comment by davidlange6** [comment]
> On Dec 3, 2020, at 6:10 PM, Matti Kortelainen <notifications@github.com> wrote:
> 
> 
> Do we want to set a precedent that CMS-specific ML models to be used in CMSSW can be placed in "random places" outside of CMS' control (even if an update of the data external would require an update in cmsdist)?

I think that would best.

**Comment by slava77** [comment]
what I had in mind is that cmsdist would still have information about the tag/branch of the model files; the same way we deal with the external code.

I didn't think of the exact mechanism of how to make the files available to the sonic server; perhaps cms-data repo with access on the server side presumed to be via `CMSSW_DATA_PATH` or `CMSSW_SEARCH_PATH` is still an easier solution and everything will be in our control.

**Comment by kpedro88** [comment]
In general, I think we'll need to "aggregate" models from different locations (even just different cms-data repos), and I am working on some code to automate this for server deployment. So either approach (cms-data or separate external) is really fine with me at this time.

**Comment by smuzaffar** [comment]
Getting data from external repos and treating those as data files (e.g. accessing via `CMSSW_SEARCH_PATH`) is trivial. We just need to add an extra `spec` and its toolfile to expose its data via  CMSSW_SEARCH_PATH. 
As @slava77  mentioned, cmsdist will keep the record of `tag` of external tool , so it should be safe.

**Comment by smuzaffar** [comment]
cms-sw/cmssw#32272 itself is closed, do we still need a data external in cmssw to pull the ML models? if yes then should I proceed with the head of https://github.com/fastmachinelearning/sonic-models and make those files available as `RecoLocalCalo/HcalRecProducers/data/<files>` ? If not then can we close this issue?

**Comment by kpedro88** [comment]
I think this can be closed.
