### ISSUE TITLE
add myproxy client to singularity images

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmsdist#6498]
myproxy client is needed to use CRAB Client, in addition to voms-proxy-* stuff which is already in the singularity images. Can you consider adding it ? See alto this old thread: https://hypernews.cern.ch/HyperNews/CMS/
myproxy client is in EPEL, I think that you can simply do `yum install myproxy` when building the image

**Comment by smuzaffar** [comment]
@belforte , which images you are talkng about? It should be present in cmssw/cc7:amd64 and cmssw/cc8:amd64 images [a]. And I think the cms images for grid (cmssw/cms:rhel* should also have it).

https://github.com/cms-sw/cms-docker/blob/master/cc7/Dockerfile.amd64#L15
https://github.com/cms-sw/cms-docker/blob/master/cc8/Dockerfile#L25

**Comment by belforte** [comment]
I have tried cc7 a few times and wasn't there. I will check again and double check if it is latest

**Comment by belforte** [comment]
```
(base) Singularity cc7:latest:~> which voms-proxy-info
/usr/bin/voms-proxy-info
(base) Singularity cc7:latest:~> which myproxy-info
/usr/bin/which: no myproxy-info in (/home/belforte/miniconda3/bin:/home/belforte/miniconda3/condabin:/cvmfs/cms.cern.ch/common:/home/belforte/scripts:/usr/sue/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/belforte/mybin:/home/belforte/myCC7/bin)
(base) Singularity cc7:latest:~> 
```
started with:
```
singularity -s shell  -B /cvmfs docker://cmssw/cc7:latest --login
```

**Comment by belforte** [comment]
but indeed is there in docker://cmssw/cc7:amd64
so the problem was in using latest .. hmm  Maybe I saw some older instructions the first time I setup my things
current http://cms-sw.github.io/singularity.html is indeed OK (and have a look I do not remember!)
ok. sorry. close
