### ISSUE TITLE
Upgrade Rucio client

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#6502]
Can we please update the Rucio client to 1.23.11.post3?

Also, if there is a python3 environment we should start to include Rucio in that as well. You can pip3 install the rucio client to get a python3 version with dependencies.

Thanks,

Eric

**Comment by ericvaandering** [comment]
I think this goes to @bockjoo

**Comment by bockjoo** [comment]
@smuzaffar was handling Rucio upgrade through Jenkins.

**Comment by bockjoo** [comment]
Shahzad is not responding so far.
I am wondering if he is on vacation.
Please let me know if you want me to take an action now.

**Comment by makortel** [comment]
> I am wondering if he is on vacation.

Yes, Shahzad is on vacation.

**Comment by bockjoo** [comment]
I tried to install Rucio client with
ARCHITECTURE="slc7_amd64_gcc700"
CMS_PIP_VERSION="9.0.3-pafccj"
but it complains:
pyrsistent requires Python '>=3.5' but the running Python is 2.7.14

**Comment by bockjoo** [comment]
The current Rucio client is upgraded to 1.23.11.post3:
[cvcms@lxcvmfs106 ~]$ source /cvmfs/cms.cern.ch/rucio/setup.sh 
rucio 1.23.11.post3

**Comment by ericvaandering** [comment]
Thanks @bockjoo . That's the python2 version? 

I'm unsure if CMS has begun supplying a python3 environment to users that could benefit from Rucio. That can wait until @smuzaffar comes back if needed.

**Comment by ericvaandering** [comment]
```-bash-4.2$ source /cvmfs/cms.cern.ch/rucio/setup.sh
ls: cannot access /cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib/python*/site-packages: Permission denied
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/bin/rucio", line 63, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'
```

Is this a caching issue that will resolve itself?

**Comment by bockjoo** [comment]
> Thanks @bockjoo . That's the python2 version?
> 
> I'm unsure if CMS has begun supplying a python3 environment to users that could benefit from Rucio. That can wait until @smuzaffar comes back if needed.

I had to use pip3 to install the rucio client. 
It looks like rucio requires pyrsistent and pyrsistent requires python3. So, it had to be pip3 to install the client.
Yes, it is the python3 version of the Rucio.

**Comment by ericvaandering** [comment]
See above. This install seems quite broken (not just for me) and we definitely still need the python2 version installed as well. 

Thanks

**Comment by bockjoo** [comment]
> ```
> ls: cannot access /cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib/python*/site-packages: Permission denied
> Traceback (most recent call last):
>   File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/bin/rucio", line 63, in <module>
>     import argcomplete
> ModuleNotFoundError: No module named 'argcomplete'
> ```
> 
> Is this a caching issue that will resolve itself?

[cvcms@lxcvmfs106 ~]$ ls -al /cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib/python3.6/site-packages | head -3
total 1200
drwx------ 68 cvcms cvcms   4096 Dec 18 18:28 .
drwx------  3 cvcms cvcms     27 Dec 18 18:28 ..
The following 3 directories had the mod 700 and I changed the mode to 755 for them:
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib/python3.6
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib/python3.6/site-packages
Please try again a few minutes later.

**Comment by bockjoo** [comment]
> See above. This install seems quite broken (not just for me) and we definitely still need the python2 version installed as well.
> 
> Thanks
As I mentioned above, this rucio requires  pyrsistent and pyrsistent requires python3
python2 version needs to have a different setup.sh, I am afraid.
First, please check the upgraded rucio and let me know if you still want me to undo the upgrade.

**Comment by ericvaandering** [comment]
Well, this new version does seem to work. But I think it's a little more than we are ready for. When I said "as well" I'd like the python3 as an option for adventurous people.

Can you install 1.23.11.post3 of the python2 client and have it setup with source /cvmfs/cms.cern.ch/rucio/setup.sh and rename the current setup script to /cvmfs/cms.cern.ch/rucio/setup-py3.sh?

**Comment by bockjoo** [comment]
I don't know how to install it with python2. When I use python2, it fails  because of python3 requirement.
Since python3 is provided by cvmfs, I don't see why python3 ruicio should be adventurous.
If you must have python2 rucio, I have to undo the upgrade.

**Comment by ericvaandering** [comment]
Well, it's not the same language base for the client we previously had and when that was setup, there was no problem setting it up under python2.

Can we 
1) Leave the current setup.sh as is?
2) Make a setup-py2.sh which points to the old 1.22.x client which was installed (and is python2)
3) Relax until the new year and see if we need a 1.23.x version under python2 (and figure out how to do it)?

**Comment by bockjoo** [comment]
Sorry about that!
I have created setup-py2.sh.
Can you try?

**Comment by ericvaandering** [comment]
Basic functionality works at least. Thanks @bockjoo and happy holidays!

**Comment by smuzaffar** [comment]
I now have installed `1.23.11.post4` using system `python3` [a]. @ericvaandering , can you please test it by sourcing  `/cvmfs/cms.cern.ch/rucio/setup.sh`

[a]
```
[lxplus]$ source  /cvmfs/cms.cern.ch/rucio/setup.sh
rucio 1.23.11.post4
```

**Comment by smuzaffar** [comment]
`1.23.11.post4` is now available for both python2 and python3
