### ISSUE TITLE
Request for updated external (mva for trackerDriven seeding)

### ISSUE THREAD

**Issue by dbenedet** [cms-sw/cmsdist#651]
Necessary for:
https://github.com/cms-sw/cmssw/pull/3690

The 9 files are already in the dedicated afs area:
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat1.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat2.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat3.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat4.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat5.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat6.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat7.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat8.xml
http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVA_BDTTrackDrivenSeed_cat9.xml

**Comment by ktf** [comment]
Ciao Daniele. Can you please do a pull request to https://github.com/cms-data/RecoParticleFlow-PFTracking with the files? Thanks. @degano can you take care of this tomorrow?

**Comment by ghost** [comment]
@dbenedet I am taking care of this now.
I noticed that 

```
-http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVAnalysis_BDT.weights_convBremFinder_19Apr.txt
-http://cmsdoc.cern.ch/cms/data/CMSSW/RecoParticleFlow/PFTracking/data/MVAnalysis_BDT.weights_convBremFinder_19Apr_IntToFloat.txt
```

Might not be used anymore, can I safely remove them from the repository?

**Comment by dbenedet** [comment]
Yes, they can be removed. Do you also update the new files? 

Thanks

**Comment by ghost** [comment]
Done in #659.
