### ISSUE TITLE
Update of setuptools needed 

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#6555]
More and more python package updates fail due to our old setuptools version. Could we update it ~now? 
For python2, the most recent version is 44.1.1 (which is not so new any more but gains a year of development compared to what we have..)

**Comment by davidlange6** [comment]
I started a local test with 44.1.1 for python2 and 51.1.2 for python3. I'll start a PR if it goes ok.

**Comment by smuzaffar** [comment]
this is done via https://github.com/cms-sw/cmsdist/pull/6557
