### ISSUE TITLE
LCG plugins are not registered

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmsdist#6609]
Created a local developers area from a CMSSW_11_3_X_2021-01-26-0100 IB

Added packages locally: 
DetectorDescription/DDCMS
Geometry

Built them, but when run a test, I get an error:

```
$ cmsRun DetectorDescription/DDCMS/test/python/testGeometry2021.py 
TimeReport> Report activated
TimeReport> Report columns headings for events: eventnum runnum timetaken
TimeReport> Report columns headings for modules: eventnum runnum modulelabel modulename timetakeni
TimeReport> JobTime=1.6122e+09 JobCPU=1.61319

Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 01-Feb-2021 17:53:20.995 CET
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
DD4hep           WARN  ++ Using globally Geant4 unit system (mm,ns,MeV)
CompactLoader    INFO  +++ Processing compact file: /build/yana/DD4Hep/Units/CMSSW_11_3_X_2021-01-26-0100/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml with flag (null)
PluginService    ERROR Factory requested: DDDefinition_XML_reader (N10__cxxabiv120__function_type_infoE) :bad any_cast
PluginService    ERROR Stub is invalid!
TimeModule> 1 1 test DDCMSDetector 0.0953901
TimeModule> 1 1 testVectors DDTestVectors 0.000160217
TimeModule> 1 1 testDump DDTestDumpFile 9.89437e-05
TimeModule> 1 1 testGeoIter DDTestDumpGeometry 5.81741e-05
TimeModule> 1 1 p PathStatusInserter 3.69549e-05
TimeModule> 1 1 TriggerResults TriggerResultInserter 1.5974e-05
----- Begin Fatal Exception 01-Feb-2021 17:53:21 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module DDCMSDetector/'test'
   [3] Using EventSetup component DDDetectorESProducer/'' to make data DDDetector/'CMS' in record IdealGeometryRecord
   [4] Running EventSetup component DDDetectorESProducer/'
Exception Message:
A std::exception was thrown.
dd4hep: Failed to locate plugin to interprete files of type "DDDefinition" - no factory:DDDefinition_XML_reader. 		No factory with name Create(DDDefinition_XML_reader) for type DDDefinition_XML_reader found.
		Please check library load path and/or plugin factory name.
dd4hep: while parsing /build/yana/DD4Hep/Units/CMSSW_11_3_X_2021-01-26-0100/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
dd4hep: with plugin:DD4hep_CompactLoader
----- End Fatal Exception -------------------------------------------------
TimeEvent> 1 1 0.096998

```

Checking the plugin registration. Indeed, the file is empty:
```
[yana@cmsdev20 src]$ ls -al ../lib/slc7_amd64_gcc900/libDetectorDescriptionDD4HepPlugins*
-rw-rw-r--. 1 yana zh 0 Feb  1 17:43 ../lib/slc7_amd64_gcc900/libDetectorDescriptionDD4HepPlugins.components
-rwxrwxr-x. 1 yana zh 331464 Feb  1 17:43 ../lib/slc7_amd64_gcc900/libDetectorDescriptionDD4HepPlugins.so
```

@cvuosalo - FYI

**Comment by smuzaffar** [comment]
assign externals
I am looking at it @ianna

**Comment by Dr15Jones** [comment]
@smuzaffar we see that same error in several of the IBs as well.

**Comment by cvuosalo** [comment]
@mrodozov FYI

**Comment by cvuosalo** [comment]
@ianna Thanks for diagnosing the problem.

**Comment by smuzaffar** [comment]
@ianna , do you see the issue with CMSSW_11_3_X_2021-02-01-1100 ?

**Comment by smuzaffar** [comment]
OK I can reproduce it with CMSSW_11_3_X_2021-01-26-0100  ( which is a full release) but not in CMSSW_11_3_X_2021-02-01-1100 ( whichis a patch release) . Let me check why it fails for dev area based on full release

**Comment by smuzaffar** [comment]
CMSSW_11_3_X_2021-01-26-0100 is a special release with new DD4Hep. I noticed that `scram b` failed with error message 
```
/bin/sh: /cvmfs/cms-ib.cern.ch/nweek-02665/slc7_amd64_gcc900/external/dd4hep/v01-15x-bf5c228ca26cee82eff09d2f238eae95/bin/listcomponents: No such file or directory
```
so looks like for newer DD4Hep they have renamed the executable `listcomponents` to `listcomponents_dd4hep`. 

I will update the build rules to fix this.

**Comment by smuzaffar** [comment]
@ianna , #6610 should allow to override the dd4help listcomponents binary via toolfile. Once merged then I will create a PR with new dd4help

**Comment by smuzaffar** [comment]
@ianna  and @cvuosalo , dd4hep plugin issue is fixed now but latest dd4hep still fails ( see the results https://github.com/cms-sw/cmsdist/pull/6612#issuecomment-771757949 ) . Can you please try to run /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/6612/12640/install.sh ( as mentioned in the comment) . This will create a cmssw dev area with latest dd4hep changes. Please see why unit tests and workflow are failing with new dd4hep

**Comment by cvuosalo** [comment]
@ianna Should the failing DTGeometryBuilder unit test simply be disabled?

**Comment by ianna** [comment]
> @ianna Should the failing DTGeometryBuilder unit test simply be disabled?

Yes, I think it would be best. We cannot provide a quick fix for it. It’s a ROOT issue. What we can do is to write a new comparison test that does not depend on legacy ROOT geometry.

**Comment by cvuosalo** [comment]
I think this problem has been fixed.

**Comment by smuzaffar** [comment]
+externals
yes this is fixed by https://github.com/cms-sw/cmsdist/pull/6612 . This is only needed for newer dd4hep version
