### ISSUE TITLE
Proposing inclusion of new external tool 'dip'

### ISSUE THREAD

**Issue by sikler** [cms-sw/cmsdist#6647]
Dear all,

 CERN's DIP (Data Interchange Protocol) is an important and easy way to asynchronously exchange small amounts of information between the LHC and the experiments. So far, the vital beamspot information from CMS to LHC was transmitted using a java tool. In preparation to Run3 and to get rid of the java dependency, that tool was rewritten in a configurable, C++ based client that uses the C++ implementation of DIP API (includes and shared objects). The draft pull request with more details is below:
 https://github.com/cms-sw/cmssw/pull/32866

 It needs the external tool 'dip' and 'log4cplus', for the moment they are configured manually (scram setup). (In fact log4cplus is included in the dip distribution.) What is needed are the header files for development and the shared objects. AFAIK no source distribution of dip exists. The shared objects have been compiled with gcc 4.8.5, and seem to coexist and run with CMSSW packages compiled for gcc 8 or 9.

 Dip is available from (latest version is 5.7.0):
 https://readthedocs.web.cern.ch/display/ICKB/DIP+API

 I would like to request to include 'dip' package into cmsdist.
  
Thanks,
 Ferenc

**Comment by smuzaffar** [comment]
@sikler , yes looks like they only have binary distribution only for x86_64 arch. This means our non-x86_64 (aarch64, ppc64le) can not use it. 
Also I could not find any license information, not sure if we can even distribute it.

**Comment by davidlange6** [comment]
Looks like log4cplus is here https://github.com/log4cplus/log4cplus - but I don’t think we can do anything without a build recipe for dip.

**Comment by davidlange6** [comment]
Or cc8 builds I guess..

**Comment by sikler** [comment]
I have started a ticket at Industrial Controls Engineering Support (JIRA), will see
https://its.cern.ch/jira/browse/ENS-28989

From another post there, it seems that dip binary package for gcc 8.x could be built "as favour"
https://its.cern.ch/jira/browse/ENS-24970

**Comment by davidlange6** [comment]
Seems we can’t distribute source. Do we need to copy the example of oracle-fake for this case and have a dummy library that fulfills the interface? I presume that this library won’t work outside of p5 regardless.

**Comment by smuzaffar** [comment]
@sikler , are you planning to use the library in cmssw ? I see that it only distribute `.so` without any headers. So if you want to build CMSSW packages to link against this library then (as David suggested) we have to fake the implementatio and provide a header so that compiler does not complain.

**Comment by sikler** [comment]
@smuzaffar They distribute .so _with_ headers, this is all I need. The only issue is the old compiler version, but so far I had success with running.

The plan is to integrate the beamspot DIP server into CMSSW, but it would only run on a given machine on the technical network (so it would not run for simulation or for reconstruction). Not sure how deep integration is needed in this case, to me a plain copy of headers and .so would be enough, although not too elegant.

**Comment by sikler** [comment]
@smuzaffar Hi, so what is the plan with this?
- it seems that DIP sources won't be part of CMSSW
- are we waiting for DIP developers to compile their package in gcc9.3.0?
- how can I (as a CMSSW developer) run my server client using DIP and log4cplus in the future; are they going to become external packages?
Thanks, Ferenc

**Comment by smuzaffar** [comment]
yes, DIP sources will not be part of CMSSW but once we know how to build and distribute then they can be added as cmssw dependencies. 

Also I am not sure about the License statement. Looks like it ( https://gitlab.cern.ch/industrial-controls/services/dip-hq/dip/-/blob/develop/LICENSE) is Copyright CERN but it also  mentions that it is under No-License. 

Once we have the build instructions and green light for distribution then I can start integrating it

**Comment by sikler** [comment]
@smuzaffar Ok, great, thanks.

**Comment by smuzaffar** [comment]
@sikler , #6740 should include dip (libdip.so and headers)

**Comment by sikler** [comment]
@smuzaffar Excellent, thanks very much.
Would it be possible to include/add log4cplus as well?

**Comment by smuzaffar** [comment]
ok log4cplus (include and static lib  liblog4cplus.a) added

**Comment by smuzaffar** [comment]
dip and log4cplus are now part of 11.3.0.pre5 release. @sikler , can you please test and see if every thing you need is there.

**Comment by sikler** [comment]
@smuzaffar Sorry for the delay. Tried in 11_3_0_pre5, compiled and got

Caught exception An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load lib/slc7_amd64_gcc900/pluginBeamSpotDipServer.so because /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_0_pre5/external/slc7_amd64_gcc900/lib/libdip.so: **undefined symbol: _ZN7SStringD1Ev**
 will ignore pluginBeamSpotDipServer.so and continue.

Not clear what should provide _ZN7SStringD1Ev. It seems that log4cplus.a does not provide that.
Any ideas?

**Comment by smuzaffar** [comment]
@sikler , https://github.com/cms-sw/cmsdist/pull/6765 should fix it. I am now including the platform dependent includes and static libs where `SString` is defined

**Comment by smuzaffar** [comment]
@sikler, can you please re-try using latest CMSSW_11_3_X IBs?

**Comment by sikler** [comment]
@smuzaffar Tried now, compiles and runs without any problem! Thanks so much.
I will start testing how it actually functions with help of some DIP browser, but that is not anymore a CMSSW business...
