### ISSUE TITLE
llvm/clang 11.1

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#6666]
Whenever it's convenient, we could start upgrading llvm/clang to version 11.1 .

Note that 11.0 had an ABI incompatibility with 10.0 and 12.0 (trunk), which is fixed in 11.1 .

**Comment by mrodozov** [comment]
alright so no 11.0 :)

**Comment by mrodozov** [comment]
I'm leaving this link here so that I won't search for it
https://bugs.llvm.org/show_bug.cgi?id=46526
