### ISSUE TITLE
moving hepmc patches to a GitHub repo?

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#6721]
hi @smuzaffar , all
I'd like to move the patches in CMSDIST to hepmc into a GitHub for hepmc 
eg, like https://github.com/davidlange6/hepmc2/tree/47b8eea6430dd796cb08a12e2dd73c244d0c5e44

Is that ok?

**Comment by smuzaffar** [comment]
sounds reasonable, I have created a repo https://github.com/cms-externals/hepmc . @mrodozov , can you please populate it with hepmc source https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/master/hepmc.spec#L2 and apply the current patches

**Comment by mrodozov** [comment]
sure I'll get them as commits on top

**Comment by davidlange6** [comment]
I have them in the repo - I can just port them over and make a pr to cmsdist

**Comment by mrodozov** [comment]
![Screenshot 2021-03-11 at 18 54 31](https://user-images.githubusercontent.com/3791215/110823999-4d19a480-829b-11eb-8689-8350904fa940.png)
something is wrong with the permissions of that repo I cant push or create new branches 
if I had permissions to create a branch this would've show 'create branch ...' above view all branches

**Comment by smuzaffar** [comment]
run the jenkins job  to update the permissions

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cmsdist/pull/6722
