### ISSUE TITLE
Rucio setup does not work on cc8/lxplus8

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#6784]
The rucio setup command (`source /cvmfs/cms.cern.ch/rucio/setup.sh`) does not work on lxplus8. The first problem I can see is that there is no `cc8` directory in `/cvmfs/cms.cern.ch/rucio/x86_64/`

The second may be that `which python` does not return a python on that machine. It appears you must specify python2 or python3

**Comment by smuzaffar** [comment]
@ericvaandering , `rucio client 1.25.2` is now available for CC8 but only for python3. 

[a]
```
lxplus8> source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
rucio 1.25.2
```

**Comment by ericvaandering** [comment]
Not -> now? 

Thanks, python3 only is great.

**Comment by smuzaffar** [comment]
yes NOW :-)

**Comment by ericvaandering** [comment]
This is no longer working:
```
[ewv@lxplus8s16 ~]$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
Error: Unable to find rucio version 'current'
[ewv@lxplus8s16 ~]$ 

```

While someone is looking at this, can Rucio be updated to the 1.27 release. Also on slc7 if possible (for both python2 and python3)?
