### ISSUE TITLE
Special IB to test DD4hep master

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmsdist#6812]
Could we, please, have a special IB including the latest DD4hep master? It will facilitate integration tests for a proposed change that is needed to use Assemblies in CMS geometry description:

https://github.com/AIDASoft/DD4hep/issues/804

@bsunanda, @civanch and @cvuosalo - FYI

**Comment by civanch** [comment]
What is faster, update DD4Hep to this preliminary update or create a new IB? I would guess, that if DD4Hep update concerns only Assemblies, it will not affect other shapes of Run-3 WF and can be safely merged. The only difficulty: we do not have 12_0 master just now.

**Comment by cvuosalo** [comment]
We saw that the handling of assemblies by DD4hep can cause big problems to DD4hep simulation, so I think the separate IB would be safer.

**Comment by mrodozov** [comment]
Dears, as soon as we setup the 12_0 IBs i'll build the IB
The first 12_0 IB is building now
Cheers,
M.

**Comment by bsunanda** [comment]
Please make sure that internal optimization within G4Converter of dd4hep is switched off in this build of dd4hep
________________________________

**Comment by mrodozov** [comment]
> Please make sure that internal optimization within G4Converter of dd4hep is switched off in this build of dd4hep

this will be a cmake option I assume ? @ianna do you know what should be added as cmake config ?

**Comment by ianna** [comment]
> > Please make sure that internal optimization within G4Converter of dd4hep is switched off in this build of dd4hep
> 
> this will be a cmake option I assume ? @ianna do you know what should be added as cmake config ?

I don't think there is such an option. I've looked at the code and it follows G4 guide correctly. The G4 itself might have such an optimisation for `G4Assemblies`...

**Comment by mrodozov** [comment]
is this the 
GEANT4_USE_GDML (to be turned to OFF)
variable ?

**Comment by civanch** [comment]
@mrodozov, no, GEANT4_USE_GDML is unrelated, let it be ON.

**Comment by civanch** [comment]
I do not see possible option inside dd4hep.spec, which may help to disable optimisation. @ianna , have you an idea?

**Comment by ianna** [comment]
> I do not see possible option inside dd4hep.spec, which may help to disable optimisation. @ianna , have you an idea?

no, there are none.

**Comment by civanch** [comment]
May be IB should be done without any extra condition?

**Comment by mrodozov** [comment]
I'll build the IB with the latest master on DD4Hep and let @bsunanda to advise on this option

**Comment by bsunanda** [comment]
As Yana suggested, we use the default options - no special option is required. We understand the issue between ddd and dd4hep.
________________________________

**Comment by mrodozov** [comment]
the IB is available
CMSSW_12_0_DD4_X_2021-04-19-0900

**Comment by bsunanda** [comment]
Thanks
________________________________

**Comment by ianna** [comment]
Thanks!
