### ISSUE TITLE
Openloops package is missing for downloading

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmsdist#6823]
Dears generators people, 

I'm having issues now in already two rebuilds of openloops because of missing download
namely this one
heftpplljjj

```
- process: ppvvv2 ... download from repository: public... extract ... done
- process: heftpplljjj ... ERROR: not available (installed: {})
ERROR: process downloader failed.
error: Bad exit status from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/tmp/rpm-tmp.0NsfLo (%build)

```

where do I find this or should I cut it out ? 

Thank you 
Mircho

**Comment by mrodozov** [comment]
assign generators

**Comment by SiewYan** [comment]
Hi @mrodozov , the user defined process libraries are specified here (troubled lib) [1]. You may delete it from the list for your work.

[1] https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/openloops-user.coll.file#L158

**Comment by mrodozov** [comment]
it's fine for me to just "cut it out" but is it ok to remove it for production ?

**Comment by SiewYan** [comment]
I think you can remove it, probably the process lib is obsolete or superseded as it is indicated ERROR.

**Comment by mrodozov** [comment]
I'll check it.

**Comment by agrohsje** [comment]
You can see the list here: 
https://openloops.hepforge.org/process_library.php
There is no heftppll anymore.

**Comment by mrodozov** [comment]
none of the ppll* processes are not there or just this one ?

**Comment by agrohsje** [comment]
None of the heftppll ones, i.e. 
heftppllj
heftpplljj
heftpplljjj

**Comment by mrodozov** [comment]
alright im removing them all
