### ISSUE TITLE
Update DD4Hep to the most recent version

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#6824]
In special IB CMSSW_12_0_DD4_X_2021-04-19-2300 it was shown that with the recent PRs for ECAL geometry is fine. We need to update DD4Hep to this version in the master thread first, later in 11_3_X.

**Comment by civanch** [comment]
FYI @bsunanda, @ianna, @mrodozov, this is needed to merge https://github.com/cms-sw/cmssw/pull/33339

**Comment by mrodozov** [comment]
so you want it in 12_0 and after in 11_3 ?

**Comment by civanch** [comment]
Yes, exactly.

**Comment by civanch** [comment]
@mrodozov , Thanks!
