### ISSUE TITLE
Test Eigen 3.4-rc1

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmsdist#6833]
We should check if CMSSW and the externals are happy with 3.4-rc1, and report any problems:

> Eigen 3.4-rc1 has been released on April 19, 2021.
> 
> Depending on the amount of reported issues, 3.4 will be released late April or early May.
> 
> The source archive is available at: https://gitlab.com/libeigen/eigen/-/releases/3.4-rc1
> Please check the [release page](https://eigen.tuxfamily.org/index.php?title=3.4) for a list of changes.

Can we try building it for the various compilers and architectures of the `master` branch ?

**Comment by mrodozov** [comment]
sure I'll try it

**Comment by smuzaffar** [comment]
@mrodozov is looking in to integrate Tensorflow 2.5, hopefully that will allow us to move forward with eigen version
