### ISSUE TITLE
Herwig source not available

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmsdist#6863]
Dears, 

we have trouble downloading Herwig 7.2.2 from Hepforge,
would you please suggest additional location ?

**Comment by mrodozov** [comment]
assign generators

**Comment by smuzaffar** [comment]
@mrodozov , do we still have the issue with this?

**Comment by smuzaffar** [comment]
problem was with Hepforge.org itself and at one point we were able to download the sources and sources are now cached in cmsrep.

**Comment by mrodozov** [comment]
hepforge is still having trouble and now gcc10 is failing 
`10:42:46 Error while downloading http://www.hepforge.org/archive/thepeg/ThePEG-2.2.2.tar.bz2: [Errno 104] Connection reset by peer`

**Comment by smuzaffar** [comment]
yes issue is in general with hepforge.org which is not reachable

**Comment by smuzaffar** [comment]
here is what HepForge admin replied

> Our servers went down late Saturday due to hardware failure. Since then, our IT department is hard at work to solve the problem. Hopefully, HepForge will get back up soon.

**Comment by mrodozov** [comment]
we have the gcc10 and 9_4 failing I hope we can survive for some time with older IBs.
I'll check more often when it's back to build the failing ibs

**Comment by smuzaffar** [comment]
hepforge is getting back now and ThePeg sources are downloadable now
