### ISSUE TITLE
cms-data/RecoTracker-DisplacedRegionalTracking repository needed

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#6905]
in connection with cms-sw/cmssw#32806
please create a repository for keeping the inference model files in cms-data/RecoTracker-DisplacedRegionalTracking

the repository can be either empty or populated with files in https://github.com/cms-sw/cmssw/tree/69445fe0bcd1fc645217b2fb260bd29b3e8e155c/RecoTracker/DisplacedRegionalTracking/data

Thank you.

**Comment by mrodozov** [comment]
@silviodonato has the permissions to create new repos on cms-data

**Comment by silviodonato** [comment]
@mrodozov I've added the repository https://github.com/cms-data/RecoTracker-DisplacedRegionalTracking with the files pointed by @slava77

**Comment by slava77** [comment]
> @mrodozov I've added the repository https://github.com/cms-data/RecoTracker-DisplacedRegionalTracking with the files pointed by @slava77

Thank you!.

Now we need a tag and an update in cms-data data/cmsswdata.txt

**Comment by mrodozov** [comment]
when you create a PR on that data repo and merge it the tag will be created with the new record in cmsswdata.txt

**Comment by silviodonato** [comment]
> when you create a PR on that data repo and merge it the tag will be created with the new record in cmsswdata.txt

@mrodozov  I've already committed the files https://github.com/cms-data/RecoTracker-DisplacedRegionalTracking/commit/400759d4fc8c1e6f3782fbc4d826ac036b48b739

**Comment by mrodozov** [comment]
no worries. once the repo is there I can fix it

**Comment by smuzaffar** [comment]
repository has been created and there is already an cmsdist PR  #6907 to integrate this new data externals
