### ISSUE TITLE
Warning when using professor2 tool

### ISSUE THREAD

**Issue by guitargeek** [cms-sw/cmsdist#6939]
When compiling CMSSW, I get the following warning:
```
****WARNING: Invalid tool py2-sympy. Please fix professor2 file.
```
Can you solve this by changing cmsdist somehow? Thanks!

**Comment by mrodozov** [comment]
I can, but we made a shift to remove some py2 packages to py3 only (sympy one of them)
can we rather try to use the py3 version ?
https://github.com/cms-sw/cmsdist/pull/6878/files

**Comment by davidlange6** [comment]
That likely works after transitioning everything to py3. 
As this tool is not used at build time, perhaps it is just not needed in the tool file? (Anyway it does not impact any tests)

**Comment by mrodozov** [comment]
@guitargeek it was not clear you want the py2-sympy tool back or you don't want the warning :D

**Comment by guitargeek** [comment]
Ah sorry, I didn't know you were asking me something :)

I'd just like to see the warning go away. I would be fine if the `py2-sympy` line is removed from the professor2 file. That should be harmless, because professor is not even used in CMSSW.

**Comment by mrodozov** [comment]
got it
