### ISSUE TITLE
Rucio source check if cmsos command available

### ISSUE THREAD

**Issue by juztas** [cms-sw/cmsdist#6944]
It would be nice if Rucio checks if cmos command available and if not - raise an error (either point to TWiki or ask to source cmsset_default.sh)
```
-bash-4.2$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
-bash: cmsos: command not found
Error: Unable to find rucio version 'current'
-bash-4.2$ source /cvmfs/cms.cern.ch/cmsset_default.sh
-bash-4.2$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
```
Diverted from: https://github.com/dmwm/CMSRucio/issues/233

**Comment by smuzaffar** [comment]
@juztas , this should be fixed by cms-sw/cms-bot#1561 . The changes are publish on cvmfs and should be visible in few minutes
