### ISSUE TITLE
Add new HF shower library

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#700]
A new HF shower library has been created to be used with 7_1_0_pre8. It is available at

/afs/cern.ch/user/k/kheyn/public/For_Salavat/HFShowerLibrary_npmt_eta4_16en.root

and should be accessible in  /afs/cern.ch/cms/data/CMSSW/SimG4CMS/Calo/data

Old shower libraries should not be removed.

**Comment by ghost** [comment]
Solved with #704
