### ISSUE TITLE
Update LHAPDF 6.3.0

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#7097]
It seems that `lhapdf 6.2.3` python interface does not build with `python 3.9`. There is a newer version `lhapdf 6.3.0` ( https://lhapdf.hepforge.org/install.html ) available. Any objections on updating lhapdf to `6.3.0` ? 

We also have https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/lhapdf_makeLinks.file which creates symlinks for LHAPDF data sets from /cvmfs/cms.cern.ch/lhapdf/pdfsets in to lhapdf package. Currently it is doing it for version `/cvmfs/cms.cern.ch/lhapdf/pdfsets/6.2.3c` ? Instead of creating symlinks for individual pdfsets, can we just create symlink to the top level directory e.g. `lhapdf/share/LHAPDF -> /cvmfs/cms.cern.ch/lhapdf/pdfsets/%{setsversion}` ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/lhapdf.spec#L2 ) ?

**Comment by smuzaffar** [comment]
assign generators

**Comment by agrohsje** [comment]
@smuzaffar your proposed changes look good to me. let me ask @qliphy : in the past, did we run special relvals when moving to a new pdf or just the regular pr tests? pdf files shouldn't be touched by the transition so I assume there is no need.

**Comment by qliphy** [comment]
@agrohsje  I remember GEN also checked effects manually upon PDF changes.  But here PDF files are not changed, then I agree the proposal.

**Comment by agrohsje** [comment]
Hi @smuzaffar : Will you prepare or should @mkirsano help?

**Comment by smuzaffar** [comment]
I can prepare @agrohsje . Only thing I am not sure is about the pdfsets. Should I update the pdfset to point to `/cvmfs/cms.cern.ch/lhapdf/pdfsets/6.3.0f` or should it remain `/cms.cern.ch/lhapdf/pdfsets/6.2.3c` ? Currently in LHAPDF installation (  /cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/lhapdf/6.2.3-c1eb4a3de9442449bc7452c2cc7a734e/share/LHAPDF) we have symlinks points to `/cms.cern.ch/lhapdf/pdfsets/6.2.3c` plus some extra pdfs (from `6.1` ) downlaoded from https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/lhapdf.spec#L8 . So I am not sure what to do for LHAPDF 6.3.0.

**Comment by agrohsje** [comment]
thanks so much @smuzaffar . I would say we should keep:
Source4: http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MSTW2008nlo68cl.tar.gz
Source5: https://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MMHT2014lo68cl.tar.gz
Source6: https://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MMHT2014nlo68cl.tar.gz
but can ignore:
Source2: http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/cteq6l1.tar.gz
Source3: http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/CT10.tar.gz
Source 2 and 3 are not included in our default PDF lists:
https://github.com/cms-sw/genproductions/blob/master/MetaData/pdflist_5f_2017.dat
https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/make_rwl.py
and not the pdf's for p8 tunes like monash.
Do you know which PDF's were dropped between 6.3 and 6.2? If nothing relevant was dropped I would prefer using 6.3. 
@qliphy What do you think?

**Comment by smuzaffar** [comment]
@agrohsje , these following pdfs are dropped in `6.3.0f` with respect to `6.2.3c`
```
MRST2004qed
cteq6
```

**Comment by agrohsje** [comment]
So 6.3 should be fine and we just need to add the 3 additional sources pointed out above. Thanks @smuzaffar .
Maybe we can wait for @qliphy to confirm my proposal.

**Comment by smuzaffar** [comment]
these sources are already part of `6.3.0f` 
```
Source4: http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MSTW2008nlo68cl.tar.gz
Source5: https://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MMHT2014lo68cl.tar.gz
Source6: https://www.hepforge.org/archive/lhapdf/pdfsets/6.1/MMHT2014nlo68cl.tar.gz
```
so do we still need to explicitly download and add? By the way these url do not work any more.

**Comment by mkirsano** [comment]
Sorry for not participating earlier

  If I remember correctly, some sets are dowloaded explicitly to have a 
possibility of some builds and tests without cvmfs. May be we don't need 
this now?

08/07/21 11:58, Malik Shahzad Muzaffar пишет:

**Comment by agrohsje** [comment]
Thanks @mkirsano for the additional input. Because I checked LHAPDF and the ones above were also in the versions I checked from 6.1 and 6.2 : 
https://lhapdf.hepforge.org/downloads/?f=pdfsets/v6.backup

**Comment by mkirsano** [comment]
I can make the update if needed

  Anyway, the instruction is here: 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideLHAPDF

08/07/21 12:07, agrohsje пишет:

**Comment by smuzaffar** [comment]
@mkirsano , please go ahead with the update.

**Comment by agrohsje** [comment]
@mkirsano thanks. do you remember where independence from cvmfs was needed? or you plan to ignore and we add later in case still useful?

**Comment by mkirsano** [comment]
I am not sure, may be some CMSSW build computers did not have cvmfs.

For now I can remove downloading some of the sets, the ones that you say 
are not used.

08/07/21 12:34, agrohsje пишет:
