### ISSUE TITLE
Integrate new fastjet release (3.4.0) with thread safety natively

### ISSUE THREAD

**Issue by rappoccio** [cms-sw/cmsdist#7131]
The latest version of fastjet (3.4.0)[http://fastjet.fr/repo/fastjet-3.4.0.tar.gz] has thread support natively enabled. We may be able to get away without making patches. 

CMS should only need the --enable-limited-thread-safety mode, so we can avoid the speed penalty from the full --enable-thread-safety mode.

FYI @laurenhay @kpedro88 @camclean @kirschen (I don't think I remember Laurent's github name, if someone wants to tag him ;) )

**Comment by smuzaffar** [comment]
@ddaina can you please take care of it?

**Comment by smuzaffar** [comment]
@rappoccio , https://github.com/cms-sw/cmsdist/pull/7134 should update fastjet to 3.4.0. CMS already uses ` --enable-limited-thread-safety` since 3.4.0-beta.

**Comment by rappoccio** [comment]
@smuzaffar Thanks a lot! This is great. :)
