### ISSUE TITLE
Update correctionlib to v2.0

### ISSUE THREAD

**Issue by nsmith-** [cms-sw/cmsdist#7300]
With https://github.com/cms-nanoAOD/correctionlib/releases/tag/v2.0.0 we have a stable schema and are almost done with implementing all POG corrections. In #6659 v1.1 was added to cmsdist. In the new version, there are some changes to the package:
- Python 3 installation is done through pip+scikit-build
- Python 2 installation is done through makefile only (reduced library)
- C++ shared library separately compiled and can be linked to directly

In https://github.com/cms-nanoAOD/correctionlib#installation an overview of the installation is given, but I guess this needs adapting to cmsdist. FYI @davidlange6

**Comment by smuzaffar** [comment]
@nsmith-  , https://github.com/cms-sw/cmsdist/pull/7301 should update correctionlib to version 2.0.0
