### ISSUE TITLE
Correctionlib 2.1

### ISSUE THREAD

**Issue by nsmith-** [cms-sw/cmsdist#7510]
A minor release https://github.com/cms-nanoAOD/correctionlib/releases/tag/v2.1.0 just has some small internal changes, dependencies are the same as 2.0.
Is it possible also to backport this to CMSSW 10_6_X release? I am happy to help of course.

**Comment by smuzaffar** [comment]
#7515 should include the v2.1.0

**Comment by tvami** [comment]
I did a backport to 10_6_X: https://github.com/cms-sw/cmsdist/pull/7519
I hope this was all that's needed in 10_6_X and there was no other steps, @nsmith- please confirm!

**Comment by nsmith-** [comment]
I would expect more needs to be done, as that branch did not have any of the dependencies already.
I think we should backport the sum of the changes in
- https://github.com/cms-sw/cmsdist/pull/7515
- https://github.com/cms-sw/cmsdist/pull/7301
- https://github.com/cms-sw/cmsdist/pull/6659
- https://github.com/cms-sw/cmssw/pull/35296

**Comment by smuzaffar** [comment]
@nsmith-  why you need this for 10.6.X?  Correctionlib is only available for python3 and 10.6.X is python2 only release? So which part of cmssw code in 10.6.X uses it?

**Comment by nsmith-** [comment]
@smuzaffar see #7523

**Comment by smuzaffar** [comment]
thanks @nsmith-  for the pr for 10.6.X
