### ISSUE TITLE
Update DD4hep to latest v01-19 for 12_3

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmsdist#7513]
To keep up with the latest DD4hep release, please update DD4hep to v01-19 for 12_3.

**Comment by cvuosalo** [comment]
@mrodozov Could you please create a PR for this issue? Thanks.

**Comment by cvuosalo** [comment]
@civanch FYI

**Comment by makortel** [comment]
> @mrodozov Could you please create a PR for this issue? Thanks.

@mrodozov has left CMS. @smuzaffar @iarspider

**Comment by smuzaffar** [comment]
#7514 should move to latest v01-19 tag ( plus few updates on top of it)
