### ISSUE TITLE
Is py3-theanets still needed?

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmsdist#7517]
* Last update on PyPi was in January 2016 (nearly 6 years ago)
* Requires a version of py3-climate only available on CMS mirror
* Last update on Github was in June 2018, one of the changes was to drop py3-climate in favor of py3-click

If we drop py-theanets, we can drop climate as well

**Comment by smuzaffar** [comment]
@iarspider ,please go ahead and open a PR to drop it

**Comment by smuzaffar** [comment]
I do not think there is any thing in cmssw which require it ( just a simple unit test which can be dropped too)

**Comment by smuzaffar** [comment]
closing this issue as `py3-theanets` has been dropped via #7518
