### ISSUE TITLE
Need Rucio update to 1.27 on both lxplus7 and lxplus8 

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#7530]
This is no longer working on lxplus8
```
[ewv@lxplus8s16 ~]$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
Error: Unable to find rucio version 'current'
[ewv@lxplus8s16 ~]$ 
```

But there is a new release of Rucio out, the 1.27 series. Can this client be installed everywhere and in python2  and python3 flavors for SLC7 based OSes? There is no need to get older clients working on any release.

@bockjoo or @smuzaffar ?

**Comment by bockjoo** [comment]
Shahzad usually handles the ruclo-client upgrade. I am not familiar with this Jenkins.
By the way,
[bockjoo@lxplus8s17 ~]$ ARCH=$(uname -m)/$(/cvmfs/cms.cern.ch/common/cmsos | cut -d_ -f1)
[bockjoo@lxplus8s17 ~]$ echo $ARCH
x86_64/cs8

There is no cs8 direcotry: 
[bockjoo@lxplus8s17 ~]$  ls /cvmfs/cms.cern.ch/rucio/x86_64/
cc8  slc7

As a result,
[bockjoo@lxplus8s17 ~]$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
Error: Unable to find rucio version 'current'

Do we need a cs8 directory symlinked to cc8?

**Comment by ericvaandering** [comment]
I would guess so.

Sent from a mobile device.

On Dec 29, 2021, at 9:17 PM, Bockjoo Kim ***@***.***> wrote:

﻿

Shahzad usually handles the ruclo-client upgrade. I am not familiar with this Jenkins.
By the way,
***@***.*** ~]$ ARCH=$(uname -m)/$(/cvmfs/cms.cern.ch/common/cmsos | cut -d_ -f1)
***@***.*** ~]$ echo $ARCH
x86_64/cs8

There is no cs8 direcotry:
***@***.*** ~]$ ls /cvmfs/cms.cern.ch/rucio/x86_64/
cc8 slc7

As a result,
***@***.*** ~]$ source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
Error: Unable to find rucio version 'current'

Do we need a cs8 directory symlinked to cc8?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cms-2Dsw_cmsdist_issues_7530-23issuecomment-2D1002854953&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=hBmW3LVAbWVFUlwB7nI4k0Eibqk-3I_xv4z8R1ShpuSHDwwuMCI5VzN6hXpzyvY3&s=mYTexdJkWi7HjA9OjceKTjYh2zOL2_26RLqUpmMcd4Q&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAMYJLXXGQZHKL6FOUBDGN3UTPFKLANCNFSM5K6WBAWQ&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=hBmW3LVAbWVFUlwB7nI4k0Eibqk-3I_xv4z8R1ShpuSHDwwuMCI5VzN6hXpzyvY3&s=ZSxs60t5p2n-1JWvCnFsJyvfev23jHC51QapOKcqrpM&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=hBmW3LVAbWVFUlwB7nI4k0Eibqk-3I_xv4z8R1ShpuSHDwwuMCI5VzN6hXpzyvY3&s=g0_ocUkwSfqkmquIYjIQG35OqbNsMMcTmhitMq2Vyls&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=hBmW3LVAbWVFUlwB7nI4k0Eibqk-3I_xv4z8R1ShpuSHDwwuMCI5VzN6hXpzyvY3&s=X7jxwlYqY_5MECM39YhhZgy5RQzzKAeGVDVlWuK1ZEg&e=>.

**Comment by bockjoo** [comment]
It's sym-linked and you should be able to see the rucio-client version 1.25.2.
I guess Shahzad will handle the installation of 1.27 (I guess it is 1.27.2?).

**Comment by ericvaandering** [comment]
Thanks @bockjoo and Happy New Year! Rucio 1.27.3 is out, but maybe there is no client release. If so 1.27.2 is fine.

**Comment by smuzaffar** [comment]
@ericvaandering , `rucio-clients 1.27.2` is now installed for slc7 and cc8/cs8 for python3.
