### ISSUE TITLE
Update UTM to 0.10.0 for Displaced Jet bit at L1T

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmsdist#7542]
Please update the UTM library to version 0.10.0 which adds grammar for displaced jet bit at L1T.

https://gitlab.cern.ch/cms-l1t-utm/utm/-/tree/utm_0.10.0

Attn @mrodozov @smuzaffar

**Comment by smuzaffar** [comment]
@rekovic , https://github.com/cms-sw/cmsdist/pull/7543 should update utm to version 0.10.0
