### ISSUE TITLE
update cryptograohy 

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#7548]
@iarspider , can you please check if we can move cryptography version 3.3.2. The versuion we have in cmssw is vulnerable

**Comment by iarspider** [comment]
@smuzaffar I don't think so: newer version of Cryptography want OpenSSL 1.1.0 or 1.1.1, and in CentOS 7 it is 1.0.1

**Comment by smuzaffar** [comment]
ah ok, closing this issue then
