### ISSUE TITLE
Cleanup unused/obsolete files from default branch

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#7559]

**Comment by smuzaffar** [comment]
@raaid07 can you please look in to this?

**Comment by smuzaffar** [comment]
these are the files which might not be in used any more

```
0001-Revert-r248245-breaks-ROOT.patch
alpgen.patch
beecrypt.spec
cms_oracleocci_abi_hack-fake.spec
cms_oracleocci_abi_hack.spec
cmssw-src.spec
cmssw-xmldata-build.file
conddbdata-rpm-build.file
configurations.file
dasgoclient-binary.spec
data-build-github-new.file
data-rpm-build.file
dire.spec
distcc-gcc7.patch
eigen-altivec-fix.patch
evtgen-1.6.0-configure-new-gcc.patch
gcc-checker-plugin.spec
gcc-remove-LWG2825-LWG2756-r245024.patch
geant4-bench.spec
geant4-G4NEUTRONXS.spec
gengetopt-parallelbuild.patch
gengetopt.spec
icc-provides.spec
icc-scram.spec
lcg-dummy.spec
libatomic_ops.spec
libffi-3.2.1-fix-include-path.patch
libunwind-fix-comma.patch
local-cern-siteconf.spec
local-princeton-siteconf.spec
make-4.2.1.patch
modulemaps/clhep.modulemap.file
mysql.spec
neon.spec
p5-compress-zlib.spec
p5-extutils-makemaker.spec
p5-sort-key.spec
p5-text-glob.spec
p5-time-hires.spec
partial.py.file
patch-setup.patch
pcre2-toolfile.spec
pip/nbdime.file
popt.spec
pylint-2.4.2-encoding.patch
readline6.3-upstream-patches1-6.patch
readline.spec
root_boost_mm.patch
tauola-27.121-gfortran.patch
tfilea.patch.file
tgsinventorfix.cc.file
tkonlinesw-cmake-build.file
valgrind-python.supp.file
vincia.spec
weekly.spec
xgboost-arm-and-ppc-py-0-82.patch
```

**Comment by raaid07** [comment]
I have opened some pull requests to remove these unused files. The following files are not part of the default branch that is why I have not opened any pr for these.
- modulemaps/clhep.modulemap.file
- root_boost_mm.patch
- tfilea.patch.file

The following files are still in use
- tkonlinesw-cmake-build.file
- valgrind-python.supp.file

**Comment by smuzaffar** [comment]
Thanks @raaid07 for taking care of this cleanup. Yes you are right `modulemaps/clhep.modulemap.file,  root_boost_mm.patch, tfilea.patch.file` are not available in default cmsdist branch. I will take care of those cleanup. Also `tkonlinesw-cmake-build.file and valgrind-python.supp.file` are only used for `osx` arch and as we are not build IBs for `osx` that is why our automatic system marked these as unused.

**Comment by smuzaffar** [comment]
all unused files are now removed
