### ISSUE TITLE
dasgoclint failed due to to parse X509 proxy

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#7701]
@vkuznet , We now see that randomly dasgoclient failed to to parse X509 proxy. We have seen this error few times [a] during the IB tests. Any idea why it is randonly failing? Note that test [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_ROOT6_X_2022-03-18-2300/pyRelValMatrixLogs/run/39634.21_TTbar_14TeV+2026D88PU_ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTriggerPU+RecoGlobalPU+MiniAODPU/step2_TTbar_14TeV+2026D88PU_ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTriggerPU+RecoGlobalPU+MiniAODPU.log#/) worked fine

[a]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-03-18-2300/unitTestLogs/PhysicsTools/Utilities#/1569-1569
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-03-18-2300/pyRelValMatrixLogs/run/39634.21_TTbar_14TeV+2026D88PU_ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTriggerPU+RecoGlobalPU+MiniAODPU/step2_TTbar_14TeV+2026D88PU_ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTriggerPU+RecoGlobalPU+MiniAODPU.log#/

**Comment by vkuznet** [comment]
@smuzaffar I doubt it is something related to my code. I didn't change certificate part for years. Said that, we need to check few possibilities:
- does the proxy reside on shared FS, like AFS?
- did we (CMS, lxplus) changed root CAs?
- you should provide info how do you obtain the proxy file, e.g do you run voms-proxy-init before calling dasgoclient? Can you printout voms-proxy-info before calling dasgoclient? Can you copy proxy file to local FS like /tmp area and use it with dasgoclient?

Before we get any of those details I don't have specific recipe how to proceed with this.

You may easily check the sequence:
- obtain your proxy via `voms-proxy-init -voms cms -rfc`
- provide output of `vocms-proxy-info`
- setup your X509_PROXY_USER to the file pointed in above command
- run dasgoclient with any query

If I do this sequence on lxplus everything works fine, so you should provide output of all commands on the node where it is executed. I suggest that you adjust your workflow to add voms commands before running dasgoclient. There may be different issues here, e.g. expired proxy, issue with shared FS, etc.

**Comment by smuzaffar** [comment]
@vkuznet , this is a very random and low frequency error. We do run `voms-proxy-init -voms cms` before all tests , so we should have a valid proxy. It works most of the time. This is first time I have seen such an error.

Note this test was run on a Openstack VM on local SSD disk (AFS is not available of these VMs). `voms-proxy-init` was run on Sat 00h10  (proxy was valid till Sun 00h10) and the unit test was run before Sat 01h22. So proxy should be valid when test was run.

[a]
```
00:10:54 Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmsbot/CN=545661/CN=Robot: CMS Build Bot
00:10:55 Creating temporary proxy ..................................................... Done
00:10:55 Contacting  voms-cms-auth.app.cern.ch:443 [/DC=ch/DC=cern/OU=computers/CN=cms-auth.web.cern.ch] "cms" Done
00:10:55 Creating proxy .......................................................................... Done
00:10:55 
00:10:55 Your proxy is valid until Sun Mar 20 00:10:55 2022
```

**Comment by vkuznet** [comment]
@smuzaffar thanks for confirmation. I looked at code which does parsing the X509 proxy. You can see it here: https://github.com/vkuznet/x509proxy/blob/master/x509proxy.go#L135-L150 In both logs you provided the error originated from https://github.com/vkuznet/x509proxy/blob/master/x509proxy.go#L141 which makes me think that it may somehow be dependent from OpenSSL library used to generate the query. Is it possible to identify nodes (their OSes) and environment which were used to obtain X509 proxy. If it is the case of OpenSSL library version I need to know which version was used and see how I can adjust code to parse such proxy certificate. It would be also helpful if you'll save proxy file in jobs which fail and pass it to me. Even if proxy certificate will be expired I can use it to try read operation and check what causing this error.

**Comment by vkuznet** [comment]
Can you also add to the log output of the following command:
```
openssl x509 -inform pem -in -noout -text -in $X509_USER_PROXY
```
where `X509_USER_PROXY` is a environment pointing to your proxy file (or use file path itself).
This should dump content of the proxy certificate including encoded PEM block.

**Comment by smuzaffar** [comment]
@vkuznet , first test was run on `cmsbuild80` which is CentOS7 based OpenStack VM but the tests always run in a singularity container. e.g for this job we use cmssw/cc7/x86_64 container you you can run yourself on lxplus
```
[cmsbuild@lxplus729 ~]$ cmssw-cc7
Singularity> openssl version  
OpenSSL 1.0.2k-fips  26 Jan 2017
```

I do not think it is OpenSSL issue otherwise it should fail all the time. Could it be that another process run on the same system which override the proxy file while das client was trying to read it? Though normally only one Jenkins job should run on a VM

**Comment by smuzaffar** [comment]
by the way, we also have RHEL8 based host [a] with different version of OpenSSL and this test works fine there too. I think chances of some other process deleting/overriding the proxy might have caused this issue. I will keep an eye on such issue in future and will try to see if any other cleanup jab ran when this happened.

[a]
```
[cmsbld@cmsbuild90-rh8 ~]$ openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

**Comment by vkuznet** [comment]
thanks for details, yes, your idea seems more plausible to me. But if you run stuff within container then I would expect that all files will be local to container and you have sequence of scripts to execute, e.g. run `voms-proxy-init`, then run `dasgoclient`, then run something, then run clean-up job, is it not the case? Since I don't know how you organize the workflow it is hard for me to judge anything there. In other words, can you copy proxy file you generate to different location before you run `dasgoclient`, then set properly `X509_USER_PROXY`, and after `dasgoclient` finished remove this local copy?

**Comment by smuzaffar** [comment]
you are right about files in container but we mount `/tmp` so generated proxy file should be on host :-) We do not set any X509_USER_PROXY , the default `/tmp/x509up_uUID` should be used. 

I would close this issue and will open a new one if we again get such an error.
