### ISSUE TITLE
Rucio and Python3

### ISSUE THREAD

**Issue by nhoerman** [cms-sw/cmsdist#7861]
Hello experts,

in the rucio file the first line of
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/bin/rucio
the python3 directory
#!/usr/bin/python3

is hardcoded and not
#!/usr/bin/env python3

so that rucio can use the env setting with e.g. the cvmfs installation of python3 ? Would this work and if yes can it be changed to the env setting ? Or is there another solution ?

Best regards,
Natascha

**Comment by smuzaffar** [comment]
@nhoerman , we simply use `pip install` to install rucio and it uses system python path. I can update the install script to replace `/usr/bin/python3` with `/usr/bin/env python3`

**Comment by smuzaffar** [comment]
@nhoerman , I just have installed rucio client `1.28.3` which uses `/usr/bin/env python3`. Can you please try setting up the env by running `/cvmfs/cms.cern.ch/rucio/setup-py3.sh 1.28.3` and check if it uses python3 form PATH instead of system one?

**Comment by nhoerman** [comment]
Thanks a lot for the fast new version, it works.
