### ISSUE TITLE
Make alternative IB 7_1_0_g410p02

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#809]
2nd patch to Geant4 10.0 is available at url:
http://geant4.web.cern.ch/geant4/support/download.shtml

As was agreed at last OPR and SIM meetings this patch should be first integrated to special IB 7_1_0_g410p02 to be compared with 7_1_0.

10.0p02 should be built in the same way as 10.0p01 in sequential mode and with the same other compile options.

For 7_2_X_GEANT10 it should be built in MT mode with modifications of cmake scripts as was done when 10.0p01 was built.

**Comment by civanch** [comment]
This old issue has been implemented in 7_2_0_pre3 and has been validated by RelVal procedures. Because results are positive, Geant4 10.0p02 can be backported to 7_1_X (together with "big plugin") to be used for mass production.

**Comment by ktf** [comment]
Do you have better numbers for the big plugin speedup?

**Comment by civanch** [comment]
My measure is not extremly accurate, because I am using cmsdev04 without a gurantee of stable state. This estimate gives ~6%. Needs to be re-measured for 7_1_X.

**Comment by civanch** [comment]
Geant4 10.0p02 is used now by 7_1_X and all 7_2_X branches, so this issue can be closed.
