### ISSUE TITLE
Missing libnvidia-ml issue for ppc64le

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#8110]
@fwyzard , We noticed that for ppc64le test build are get build errors like [a]. I think this is due to the `cuda-nvml` dependency https://github.com/cms-sw/cmssw/blob/master/HeterogeneousCore/CUDAUtilities/BuildFile.xml#L3 . Note that although power nodes has GPU and cuda installation on host but we start the singularity container without `--nv` option so cuda driver for host should not ve available inside the container. For some strange reason the https://github.com/cms-sw/cmssw-config/blob/scramv3/SCRAM/hooks/runtime/00-nvidia-drivers#L41 check passes and adds `${CUDA_BASE}/drivers` in LD_LIBRARY_PATH [b]. Any idea why `cuda-compatible-runtime` passed though we have not started container with nvidia enabled?

  The ` libnvidia-ml` is part of `${CUDA_BASE}/lib64/stubs` . Can we copy/make links for it under  `${CUDA_BASE}/drivers` too ?

[a]
```
>> Leaving Package CondCore/EgammaPlugins
error: edmWriteConfigs caught an exception while loading a plugin library.
The executable will return success (0) so scram will continue,
but no cfi files will be written.
An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load /scratch/cmsbuild/jenkins_a/workspace/test-os-alma8/inst/el8_ppc64le_gcc10/CMSSW_12_5_X_2022-09-27-2300/tmp/el8_ppc64le_gcc10/src/CondCore/EcalPlugins/src/CondCoreEcalPlugins/libCondCoreEcalPlugins.so because libnvidia-ml.so.1: cannot open shared object file: No such file or directory
```

[b]
```
Singularity> echo $LD_LIBRARY_PATH 
/.singularity.d/libs
Singularity> ls $LD_LIBRARY_PATH 
Singularity>  bash -ex ./config/SCRAM/hooks/runtime/00-nvidia-drivers 
+ '[' -z '' ']'
+ SCRAM=scram
++ scram_tag cuda CUDA_BASE
++ TOOL=cuda
++ TAG=CUDA_BASE
++ scram tool tag cuda CUDA_BASE
+ CUDA_BASE=/cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379
++ scram_tag cuda-compatible-runtime CUDA_COMPATIBLE_RUNTIME_BASE
++ TOOL=cuda-compatible-runtime
++ TAG=CUDA_COMPATIBLE_RUNTIME_BASE
++ scram tool tag cuda-compatible-runtime CUDA_COMPATIBLE_RUNTIME_BASE
+ RUNTIME_TEST=/cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda-compatible-runtime/1.0-e46efa35a3328b581fe6b9399d536465/test/cuda-compatible-runtime
+ '[' '!' /cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379 ']'
+ '[' '!' -d /cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/ ']'
+ '[' '!' -x /cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda-compatible-runtime/1.0-e46efa35a3328b581fe6b9399d536465/test/cuda-compatible-runtime ']'
+ /cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda-compatible-runtime/1.0-e46efa35a3328b581fe6b9399d536465/test/cuda-compatible-runtime -k
+ CUDA_COMPATIBILITY=/cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/drivers
+ '[' -d /cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/drivers ']'
+ LD_LIBRARY_PATH=/cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/drivers:/.singularity.d/libs
+ /cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda-compatible-runtime/1.0-e46efa35a3328b581fe6b9399d536465/test/cuda-compatible-runtime -k
+ echo RUNTIME:path:append:LD_LIBRARY_PATH=/cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/drivers
RUNTIME:path:append:LD_LIBRARY_PATH=/cvmfs/cms-ib.cern.ch/nweek-02752/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/drivers
```

**Comment by fwyzard** [comment]
The compatibility drivers normally do not include `libnvidia-ml.so`:
![image](https://user-images.githubusercontent.com/4069793/192996036-ae8470a5-1e40-4c02-89be-f51dd31e1bef.png)

I'll try to have a look at what we are doing... is there a way I can reproduce what the build is doing ?

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by smuzaffar** [comment]
> I'll try to have a look at what we are doing... is there a way I can reproduce what the build is doing ?

yes you can, you need to do the following on power node ( I will send you instructions on how to login to power node)
```
source /cvmfs/cms.cern.ch/cmsset_default.sh 
cmssw-el8 -B /scratch:/data
mkdir /data/`whoami`/test
cd /data/`whoami`/test
scram p CMSSW_12_5_X_2022-09-27-2300
cd CMSSW_12_5_X_2022-09-27-2300
cmsenv
git cms-addpkg HeterogeneousCore/CUDAUtilities
scram b -v -j 10
ldd lib/el8_ppc64le_gcc10/libHeterogeneousCoreCUDAUtilities.so | grep libnvidia
        libnvidia-ml.so.1 => not found
```
You can also try to build `CondCore/EcalPlugins` which will cause build failure as root will fail to load the library dueto missing ` libnvidia-ml.so.1`.

`libnvidia-ml.so.1` should come from either `cuda/lib/stubs` or from system cuda driver installation. As `cuda-compatible-runtime` passed  so `config/SCRAM/hooks/runtime/00-nvidia-drivers`   added `cuda/drivers` where the `libnvidia-ml.so` is missing. 

Note that things works if container is started with `--nv` options (`cmssw-el8 --nv -B /scratch:/data`) as in this case system cuda libs are available via LD_LIBRARY_PATH.

**Comment by smuzaffar** [comment]
@fwyzard , were you able to look in to this? ppc64 IBs [failed to build](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_ppc64le_gcc10/CMSSW_12_6_X_2022-10-02-2300/CUDADataFormats/CaloCommon) due to this missing `libnvidia-ml.so.1` library.

**Comment by fwyzard** [comment]
Not yet.

What has changed in the pp64 IBs to make them start failing ?

**Comment by smuzaffar** [comment]
drop of `--nv` from the singularity container started up. This was done to avoid unit tests/relvals start using GPU (which, for power nodes, goes to some strange state and cause a lot of errors)

**Comment by fwyzard** [comment]
The main problem is that Singularity is not a real container, it's little more than a script that sets environment variables, and does not provide any isolation between the client environment and the host system.

Inside Singularity all devices are still visible:
```
Singularity> ls -l -h /dev/nvidia*
crw-rw-rw- 1 root root 195, 254 Sep 28 03:25 /dev/nvidia-modeset
crw-rw-rw- 1 root root 238,   0 Sep 28 03:25 /dev/nvidia-uvm
crw-rw-rw- 1 root root 238,   1 Sep 28 03:25 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Sep 28 03:25 /dev/nvidia0
crw-rw-rw- 1 root root 195,   1 Sep 28 03:25 /dev/nvidia1
crw-rw-rw- 1 root root 195,   2 Sep 28 03:25 /dev/nvidia2
crw-rw-rw- 1 root root 195,   3 Sep 28 03:25 /dev/nvidia3
crw-rw-rw- 1 root root 195, 255 Sep 28 03:25 /dev/nvidiactl
```

Since CMSSW packages NVIDIA drivers and libraries, they can be used to run on the GPUs:
```
Singularity> /cvmfs/cms-ib.cern.ch/nweek-02753/el8_ppc64le_gcc10/external/cuda-compatible-runtime/1.0-e46efa35a3328b581fe6b9399d536465/test/cuda-compatible-runtime -vCUDA driver not detected

Singularity> LD_LIBRARY_PATH=/cvmfs/cms-ib.cern.ch/nweek-02753/el8_ppc64le_gcc10/external/cuda/11.5.2-2fdd815f4265b93fa1122d3d7f612379/drivers:$LD_LIBRARY_PATH /cvmfs/cms-ib.cern.ch/nweek-02753/el8_ppc64le_gcc10/external/cuda-compatible-runtime/1.0-e46efa35a3328b581fe6b9399d536465/test/cuda-compatible-runtime -v
CUDA driver version 11.5
CUDA runtime version 11.5
```

If the job should _not_ use the GPUs, either make the system actually not expose them (_e.g._ use `cgroups` to make the NVIDIA devices not visible to the client application), or tell the application to ignore them (_e.g._ set `CUDA_VISIBLE_DEVICES=` an empty list).

Bundling `libnvidia-ml.so` with the drivers is not a good solution, because as far as I know it _must_ match the version of the kernel driver and `libcuda.so` installed on the system, so including it would actually break the possibility of using the drivers bundled with CMSSW (unless they are the exact same version as the kernel drivers). Which is the reson why it is not included neither in the CUDA runtime nor in the compatibility libraries.

**Comment by smuzaffar** [comment]
OK thanks @fwyzard, for now I have enabled the `--nv` option for power nodes. I  will check if I can come up with simple workaround for this.

**Comment by smuzaffar** [comment]
setting `CUDA_VISIBLE_DEVICES=` helped for ppc64le nodes. `cuda-compatible-runtime` failed and let scram properly add the `stubs` directory in to `LD_LIBRARY_PATH`

**Comment by makortel** [comment]
> This was done to avoid unit tests/relvals start using GPU (which, for power nodes, goes to some strange state and cause a lot of errors)

Have these been a long-term problem or appeared recently? Can you tell if the problems are specific to the Power nodes we use for testing, or general to any Power machine with NVIDIA GPU?

**Comment by smuzaffar** [comment]
@makortel , this is a general problem with any GPU based node that if cuda driver is updated but node is not restarted then it starts breaking gpu based tests. The OpenLab managed (our PowerPC) nodes has this problem since long. Other GPU nodes e.g. the HTCondor GPU nodes are well managed and they get properly restarted when cuda driver is updated.

**Comment by makortel** [comment]
Thanks @smuzaffar. I wonder if we could ask the nodes to be restarted (I'm sure you did already). We have an allocation for Summit (which is Power+NVIDIA system), and I think it would be useful to be able to exercise the Power+NVIDIA setup in our IBs as well (since the hardware is there). On the other hand, for any work within that allocation an existing release will be used, so testing current developments is not strictly necessary (except for longer term).

**Comment by smuzaffar** [comment]
@makortel , sure. I have reconfigured power nodes in Jenkins to let IBs/PR tests start using GPU is needed.
