### ISSUE TITLE
Migration to CLHEP 2.4.6.0

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#8209]
For the new version of Geant4 it is recommended to update CLHEP library to 2.4.6.0. It is expected that this update may be done for all IBs of CMSSW including master. Regression is expected.

**Comment by smuzaffar** [comment]
@aandvalenzuela , @iarspider can you please take care of this and https://github.com/cms-sw/cmsdist/issues/8210 ? This should go in the dedicated G4 branches .

**Comment by iarspider** [comment]
@smuzaffar on it.

**Comment by smuzaffar** [comment]
thanks  @iarspider for #8211 which is good for G4/Vecgeom but we should also include clhep updte for Geant4 IB

**Comment by smuzaffar** [comment]
closing this
