### ISSUE TITLE
Update zstd to latest version 1.5.2

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmsdist#8220]
@iarspider or @aandvalenzuela can you pleae take care of it?  Also I think the section https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_0_X/master/zstd.spec#L15-L20 is not needed any more.

**Comment by aandvalenzuela** [comment]
Sure, see https://github.com/cms-sw/cmsdist/pull/8221
