### ISSUE TITLE
New optimized HF shower library for Run-3

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#8288]
Would it be possible to integrate a new optimized shower library for Run3? When the library will be installed we will update the reader/writer and assume to use it for 2023 MC. New file is:

/afs/cern.ch/user/k/kheyn/public/For_Sunanda/HFShowerLibrary_run3_v7.root

to be included to data/SimG4CMS/Calo/data/

The authors expect a significant performance gain. Their tests  show good agreement between old and new results.

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@smuzaffar , LeV have prepared a new version of SL for Run3. Salavat have tested it. The file is available at afs: 

/afs/cern.ch/user/k/kheyn/public/For_Salavat/HFShowerLibrary_run3_v7.root 

Would it be possible to substitute v7, which is already inside CMS data? There is no sense to increment version number, because the current v7 is not yet used in any WF and it is responsible for crashes in some cases.

**Comment by civanch** [comment]
assign simulation

**Comment by smuzaffar** [comment]
@civanch , https://github.com/cms-sw/cmsdist/pull/8292 has been updated to include the new SL v7. Is there any cmssw PR to tests it?

**Comment by civanch** [comment]
No, there is no WF so far. This time v7 was tested privately by both LeV and Salavat, so is better prepared than previous, where Salavat was not involved. 

After troubles with previous, we decided that by default v6 is used, v7 may be enabled via modifier. When v7 will be updated we will start testing first privately, then will make PR.

**Comment by smuzaffar** [comment]
ok @civanch , so once https://github.com/cms-sw/cmsdist/pull/8292 tests are done then we will integrate SL v7 in 13.1.X

**Comment by civanch** [comment]
Is done

**Comment by civanch** [comment]
+1
