### ISSUE TITLE
Procedure for cms-data backports

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmsdist#8337]
A recent cms-data PR https://github.com/cms-data/PhysicsTools-NanoAOD/pull/14 needs to be backported for CMSSW_10_6_X.

In master, that PR was included in tag V01-03-00: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_1_X/master/data/cmsswdata.txt#L9

CMSSW_10_6_X is currently on tag V01-01-00: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/data/cmsswdata.txt#L23

To follow the minimal change policy for backports, we would need to merge the backport PR on top of V01-01-00 (rather than moving CMSSW_10_6_X to V01-03-00, which includes other changes.) To me, that requires a branch based on V01-01-00 for the PR target. Can someone make this branch so the backport PR can be submitted? Or is there a different procedure to follow?

**Comment by smuzaffar** [comment]
@kpedro88 , normally when we have conflicting changes then we create a separate branch (based on old tag) for cms-data repo and integrate changes on top of that branch. For example in this case we can create CMSSW_10_6_X branch based on V01-01-00 and then you can open a PR for that branch. But as the difference[a] in V01-03-00 and  V01-01-00 are some new files, so I would suggest to just include V01-03-00 for 10.6.X release too.

[a]
```
> git diff --name-only V01-03-00..V01-01-00
breg_training_2016.onnx
breg_training_2017.onnx
breg_training_2018.onnx
btagDeepFlavRefineNN_CHS.onnx
creg_training_2016.onnx
creg_training_2017.onnx
creg_training_2018.onnx
```

**Comment by sbein** [comment]
hi @kpedro88, @smuzaffar, I was just readying the tag change to cmsdist when I realized that the model file btagDeepFlavRefineNN_CHS.onnx that exists in V01-03-00 will not work because of backwards compatibility issues with the onnx version in CMSSW_10_6_X. We had to re-export the model in an earlier ONNX version to prevent a crash. Should we just add the new (older-versioned) onnx file for CMSSW_10_6 to the head of cms-data and then proceed to change the tag in cmsdist? Or should we develop on top of the V01-01-00 tag?

**Comment by kpedro88** [comment]
I think in this case a separate branch/tag starting from V01-01-00 should be used. (Otherwise, it's rather confusing to have V01-04?-00 with older versions of models than V01-03-00.) @smuzaffar can you make the needed branch?

**Comment by sbein** [comment]
Hi @smuzaffar, sorry if I missed a development somewhere - will it be alright to create the needed branch?

**Comment by smuzaffar** [comment]
ah sorry @sbein , I was away last week and did not follow this issue. https://github.com/cms-data/PhysicsTools-NanoAOD/tree/CMSSW_10_6_X branch  based on V01-01-00 tag is now available.

**Comment by smuzaffar** [comment]
cms-data branch for 10.6.X was created.
