### ISSUE TITLE
Update UTM to 0.11.0

### ISSUE THREAD

**Issue by epalencia** [cms-sw/cmsdist#8343]
An updated utm library (version 0.11.0) is expected to be released soon. It will contain the following new features:

- new MUS2 object (for HTM triggers)
- new MU-INDEX cut for MU object (for monitoring seeds)
- new ZDCP, ZDCM objects (HCAL ZDC+/ZDC-)
- new ADT object and ADT-ASCORE cut (anomaly detection trigger)

Documentation for integration in emulator/tools will be provided with the release.

n.b. an updated TME will follow up after the release (~ mid March).

(Information from Bernhard Arnold)

**Comment by smuzaffar** [comment]
thanks @epalencia for the information. please ping here again once the new tag is ready or feel free to open a PR with the required changes for https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_1_X/master/utm.spec

**Comment by epalencia** [comment]
Just for completeness, since this update is needed for the data taking, a backport to 13_0 will be made as well.

**Comment by epalencia** [comment]
The updated library is available: https://gitlab.cern.ch/cms-l1t-utm/utm/tree/utm_0.11.0

**Comment by perrotta** [comment]
@elfontan

**Comment by elfontan** [comment]
For reference, related PRs:
- Master: https://github.com/cms-sw/cmsdist/pull/8352
- Backport to CMSSW_13_0_Xhttps://github.com/cms-sw/cmsdist/pull/8354 

Relevant L1 updates relying on this update:
- Fix of the uGT L1_SingleMuX_EMTF, L1_SingleMuX_OMTF and L1_SingleMuX_BMTF algos ([CMSLITDPG-1075](https://its.cern.ch/jira/browse/CMSLITDPG-1075))
- New L1 seed for two loose HMT showers ([CMSLITDPG-1087](https://its.cern.ch/jira/browse/CMSLITDPG-1087))

**Comment by smuzaffar** [comment]
UTM 0.11.2 has been integrated in 13.1.X and 13.0.X
