### ISSUE TITLE
Please upgrade frontier_client to 2.10.1

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmsdist#8446]
Please update [frontier_client](http://frontier.cern.ch/dist) to version 2.10.1. Here are the [release notes](http://frontier.cern.ch/dist/clientreleasenotes.txt).
This new version includes the Python bindings and [patch](https://github.com/cms-externals/frontier_client/pull/2) that are added by CMSSW. These additions by CMSSW are no longer needed, since they are now included in frontier_client 2.10.1 itself

**Comment by iarspider** [comment]
@cvuosalo could you please also incorporate [this fix](https://github.com/cms-externals/frontier_client/commit/9a63575736ae2da49b51e630796a3b3a65e9bd37.diff) and tag a new version? Thanks!

**Comment by cvuosalo** [comment]
@iarspider I don't understand the requested change. It is not compatible with the version of `pacparser.h` that we are using.

**Comment by iarspider** [comment]
@cvuosalo understood. We will apply the fix on our side then. Out of curiosity, is there any particular reason why you are using old (<= 1.3.8) version of pacparser?

**Comment by DrDaveD** [comment]
We just hadn't gotten around to updating it.  We could include it in the next release.
