### ISSUE TITLE
Request to make a special build to test Geant4 11.1.ref04

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#8503]
In order to test new Geant4 reference version versus data with low pileup a special build is needed on top of  12_6_0 using current G4VECGEOM configuration for Geant4, DD4hep, CLHEP, and VecGeom.

**Comment by civanch** [comment]
@bsunanda, is this combination of packages correct or you need 12_6_0_pre2 ?

**Comment by bsunanda** [comment]
I think 12_6_0 + new G4 will be sufficient
________________________________

**Comment by smuzaffar** [comment]
@iarspider , can you please take care of it. All you need is to use REL/CMSSW_12_6_0/el8_amd64_gcc11 cmsdist tag, update changes needed for Geant4 11.1.ref04 and build the CMSSW_12_6_0_G4 release on one of the cmsdev nodes.

**Comment by bsunanda** [comment]
Hi

Please let me know if this build is ready and how to setup this version (like cmsrel ...). Thanks and regards

Sunanda
________________________________

**Comment by iarspider** [comment]
@bsunanda I am working on it, will let you know as soon as it's ready.

**Comment by iarspider** [comment]
@bsunanda the requested release is available here: `cmsbuild32:/build/razumov/geant4_11.1.ref04_8503/BUILD/el8_amd64_gcc10`. You can set it up the usual way.

**Comment by bsunanda** [comment]
Hi

Could you give me the commands how to build the CMSSW in my area on build32? I think "cmsrel" will not work. Thanks for making this build any way? Best regards

Sunanda
________________________________

**Comment by iarspider** [comment]
@bsunanda cmssw is already built in that area. You can set it up with
```
$ cmssw-el8
$ source /build/razumov/geant4_11.1.ref04_8503/BUILD/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_G411ref4/etc/profile.d/init.sh
```

(@smuzaffar can correct me if this is not the right way to do it)

**Comment by smuzaffar** [comment]
`init.sh` files are only used by packaging system. Users should use `scram` e.g. in this case @bsunanda please do

```
> cmssw-el8
Singularity> source /build/razumov/geant4_11.1.ref04_8503/BUILD/cmsset_default.sh
Singularity> scram list -c CMSSW
CMSSW           CMSSW_12_6_0_G411ref4     /build/razumov/geant4_11.1.ref04_8503/BUILD/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_G411ref4
Singularity> scram p  CMSSW_12_6_0_G411ref4
```

**Comment by bsunanda** [comment]
Thanks a lot

Sunanda
________________________________
