### ISSUE TITLE
Add C++ interface to HDF5 build

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmsdist#8530]
This is accomplished by adding '--enable-cxx' to the configuration. This will generate an additional library so we may need an additional scram tool to specify when to link with that library.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
thanks @Dr15Jones, I am on it

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/8541 should enable the cxx interface.
