### ISSUE TITLE
Please upgrade frontier_client to 2.10.2

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmsdist#8549]
Please update [frontier_client](http://frontier.cern.ch/dist) to version 2.10.2. Here are the [release notes](http://frontier.cern.ch/dist/clientreleasenotes.txt).
This new release supports the latest v1.4.2 pacparser, which contains a security fix.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I wonder if the(se) frontier updates are something we should backport to earlier release cycles?
