### ISSUE TITLE
setup of DBS_CLIENT via CRAB broken in CMSSW 12 +

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmsdist#8566]
this line
https://github.com/cms-sw/cmsdist/blob/d34e50e14f8a0cb4bd911942ecb1f14586451923/crab/crab-setup.sh.file#L15
fails becasue `python` can not be found resulting in an annoying message.

Rather than fixing for python3, I propose to remove this, since old [DBS Client](http://github.com/dmwm/DBS) is not compatible with current DBS server. 
We should also stop pulling in old DBS Client in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_2_X/master/crab-build.file

@smuzaffar if you agree I will make a PR for both files and the crab-prod/pre/dev spec files

**Comment by smuzaffar** [comment]
@belforte , I have no objections, if you think this is not going to break crab/dbs then please go ahead and open a PR
