### ISSUE TITLE
Thread-safe HDF5 compiler option

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmsdist#8569]
It looks like a special compiler option is needed to allow HDF5 to be run in a multi-threaded program. See

https://support.hdfgroup.org/HDF5/faq/threadsafe.html

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
Upon further investigation, it appears that the thread-safety compile option does not work if one also builds the C++ interface.

I looked at High5 and it also has threading issues (even when used with HDF5 compiled with thread-safety). See https://github.com/BlueBrain/HighFive/discussions/675

**Comment by Dr15Jones** [comment]
So my suggestion now is to turn on thread-safety and remove the C++ interface call.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/8603 should build hdf5 in threadsafe mode. Note that this means we have to diable both [high level libs](https://github.com/HDFGroup/hdf5/blob/hdf5-1_14_1/configure#L30531-L30532) and [cxx](https://github.com/HDFGroup/hdf5/blob/hdf5-1_14_1/configure#L30542-L30544)
