### ISSUE TITLE
question about py2/py3

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmsdist#8570]
Hi 
what is it the release number from which it is safe to switch from py2 to py3  for using FWCore ?

CRABClient imports and run the PSet.py, so that defines the python version for CRAB as well.

We currently use python3 for CMSSW_12 and up and python2 for CMSSW up tp 11. But I noticed
that python3 is part of CMSSW since 10_x. So I felt like asking.

CRABClient code is compatible with both py2 and py3, but when it runs inside python3 we can also mix with Rucio python client, which will be convenient.

FYI @mapellidario @novicecpp

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@belforte Did I understand you correctly that you're asking for the earliest CMSSW release where `FWCore.ParameterSet` became safe to use from python3?

Adding @davidlange6

**Comment by belforte** [comment]
that, and  `FWCore.PythonUtilities.LumiList`
and of course dependencies from them which I am not aware of.

**Comment by belforte** [comment]
hmm.. seems like  `FWCore.PythonUtilities.LumiList` breaks on python3 up to CMSSW_11 as it requires `urllib2` . That settles it. Sorry that I asked.

**Comment by makortel** [comment]
Right, as far as I can tell `FWCore.PythonUtilities.LumiList` became python3-friendly with https://github.com/cms-sw/cmssw/pull/28439 in CMSSW_11_0_0.

(and asking is always fine!)

**Comment by belforte** [comment]
ah.. so maybe we _can_ use py3 also for CMSW_11 ? @davidlange6
