### ISSUE TITLE
CMSSW vs. Rucio Client vs. CRABClient

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmsdist#8737]
I hope this is a sensible place for a small discussion on this topic. If not, tell me where/how/when.
I thought that it is better than a mail thread.
@smuzaffar @ericvaandering  @klannon @dciangot
(CC @novicecpp @mapellidario )

At the moment, when using a CMSSW release with python3, Rucio python client also works.
This makes it very attractive to use Rucio python calls inside CRAB Client, and
surely there are a lot of places where it would be useful.

We talked about this in CRAB team and believe that we do not need to make it work for earlier
releases, we will put the needed checks and warnings. (BTW, will CMSSW <12 be still in use
in Run3 era ?)

What is your opinion on this ?
What worries me is the future. Things like at a certain point Rucio moves to python 3.30 while CMSSW stays at 3.20 and they are not fully compatible, or (God forbids) python4.
OTOH, I am an anxious pessimist, so maybe this worry is w/o ground and we can happily pursue the integration.

(yeah... https://twiki.cern.ch/twiki/bin/viewauth/CMS/Rucio still says that Rucio and CMSSW are not compatible, but the only incompatibility that we have is CMSSW vs. gfal-* which I suspect will never go away).

Thanks for your attention

**Comment by belforte** [comment]
P.S. If I could have come to CERN this week, it would have been a nice coffee/beer topic, bill on me of course. Sorry about that. If you happen to visit Italy and can arrange for a stop in Udine, I will be happy to rectify this !

**Comment by makortel** [comment]
> (BTW, will CMSSW <12 be still in use in Run3 era ?)

The 2022 data were collected with 12_4_X, but (to my understanding) all the Run 2 activities continue with earlier releases (notably 10_6_X for the Ultra Legacy)

**Comment by smuzaffar** [comment]
@belforte , we do not distribute `rucio-client` along with cmssw. @ericvaandering had requested its standalone deployment under cvmfs (/cvmfs/cms.cern.ch/rucio). We only update rucio client when someone from computing ask for it. Current installed version is `1.28.3` which is more than a year old. 

One reason that it works under cmssw env is that rucio installation has its complete dependency installed under /cvmfs/cms.cern.ch/rucio so it should not depend on cmssw env. On the other hard, if you set rucio env and then cmssw then that could break cmssw itself :-)

**Comment by ericvaandering** [comment]
Right on both points. We haven't asked for an update although we probably should. Generally the client changes very slowly (and python2 is not supported after 1.29).

To the larger point, yes, rucio comes along with its own set of dependencies. I suspect this could be made compatible with any CMSSW with python3 if that was something someone wanted to look at. At least as far as the things people would want to do with the client in a combined environment. 

@belforte fortunately the Rucio client is fairly conservative in the versions of python it supports. And very conservative in making old clients work with new server releases. So it should not be a real issue that the Rucio required python version gets ahead of CMSSW.

**Comment by belforte** [comment]
thanks @makortel , we believe we can live with "users or UL data will not find Rucio stuff integrated in CRAB client"

thanks @smuzaffar for the precisation. I know the history (and personally see no problem in going to a more recent client there) but I have overlooked the `source /cvmfs/cms.cern.ch/rucio/setup-py3.sh` may likely break `cmsenv` by bringing its own binaries. OTOH we (CRAB and Diego) have evidence that it is enough to add `/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/` to `$PYTHONPATH` to make Rucio Python client work with "system python3".
Indeed we do not want "you type crab status and cmsRun is broken". Let me explore more with "add to PYTHONPATH" which IIUC should be safe cmsw-wise.

**Comment by belforte** [comment]
hm..
@ericvaandering, Rucio client seems a bit picky in dependencies, the current on in CVMFS does not like
urllib3 v.1.26.15 from CMSSW and insists for 1.26.8 [1]
It may be that updating the rucio client will solve, but it makes me uneasy about long term compatibility.

Do you expert know some python-side trick which may help to temporarely redirect python search path ? There's a clear separation inside CRAB Client between the little part which uses CMSSW paraphernalia and what does not, we mostly rely on CMSSW env. in order to avoid depending on "random system python3" and the age-old problem with libcurl.
 
[1]
```
>>> from rucio.client import Client
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
>>> 

```

**Comment by belforte** [comment]
anyhow I think it will be good to update Rucio python3 client in /cvmfs to currently supported version. If nothing else to be conistent with what people may use via pip install. Eric, who has the authority to make that decision ?

**Comment by ericvaandering** [comment]
Me. :-) Let me figure out how to make the ticket again.

**Comment by belforte** [comment]
looking "harder" the problem I reported earlier is ultimately due to the fact that 
`/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages` does not contain `chardet` so the import falls back to the CMSSW version which is `5.1.0` while the older `requests` version in rucio directory only accepts up to `5.0`
I suspect that when the Rucio client was pip installed in cvmfs it was satisfied with the dependencies in the OS and so did not add the needed `chardet` (OS likely has chardet version 3 or 4, it is required by the `requests` package which in Rucio client 1.28.3 says `# chardet_version >= 3.0.2, < 5.0.0`)

I presume that updating Rucio client will solve. OTOH it may be that messages of the sort `warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported`
are all in all harmless. I will test.

**Comment by belforte** [comment]
I have rectified some of my confusion in testing and reached a tentative conclusion, based also on #8739 

* CRABClient will use, on whichever OS it runs, the Rucio client for that arch as setup by 
```
source /cvmfs/cms.cern.ch/rucio/setup-py3.sh
```

* We will make sure that cmssw environment is not only changed during the execution of CRABClient commands (a forked subprocess in the end as per https://github.com/dmwm/CRABClient/blob/master/bin/crab

* We will restrict use of Rucio python client inside CRAB to CMSSW releases where it works, and too bad for people stuck in SL6 era.
  * initial very simple testing indicates that CMSSW_10_6_x is OK, so UL is covered, thanks Matti.

With this I thank everybody and believe that ball is back in CRAB fiels, so am closing.

**Comment by smuzaffar** [comment]
@belforte , Is it crab client or server which now needs rucio? If it is crab client then does this mean we have to deploy rucio for `ppc64le` and `aarch64`?

**Comment by belforte** [comment]
the idea is indeed to add to CRABClient, so we will need it on those arch's as well. Thanks for pointing out. In the end it has to be available to users anyhow, whether inside CRABClient or not. Depends of course on how much those archs will be used by whom for what.
In other words: we need to make Rucio client available wherever there will be CMS people needing it.
In current situation, we can certainly wait.

**Comment by belforte** [comment]
CRABClient will still work if Rucio is not available, simply it will not offer some extra features which makes it easy to work with data on Rucio.
