### ISSUE TITLE
Backport bug fix for Geant4 11.1

### ISSUE THREAD

**Issue by hahnjo** [cms-sw/cmsdist#8783]
We need to backport a fix to Geant4 11.1.2:
```patch
diff --git a/source/processes/electromagnetic/utils/src/G4TransportationWithMsc.cc b/source/processes/electromagnetic/utils/src/G4TransportationWithMsc.cc
index bf828c8b7ec..601121913b9 100644
--- a/source/processes/electromagnetic/utils/src/G4TransportationWithMsc.cc
+++ b/source/processes/electromagnetic/utils/src/G4TransportationWithMsc.cc
@@ -372,8 +372,7 @@ G4double G4TransportationWithMsc::AlongStepGetPhysicalInteractionLength(
             // 2) Call SampleScattering(), which *may* change it.
             const G4ThreeVector displacement =
               mscModel->SampleScattering(fTransportEndMomentumDir, minSafety);
-            // 3) Get the changed direction and inform G4Transportation.
-            fMomentumChanged         = true;
+            // 3) Get the changed direction.
             fTransportEndMomentumDir = *fParticleChangeForMSC->GetProposedMomentumDirection();
 
             const G4double r2 = displacement.mag2();
@@ -469,6 +468,12 @@ G4double G4TransportationWithMsc::AlongStepGetPhysicalInteractionLength(
 
         fParticleChange.ProposeTrueStepLength(totalTruePathLength);
 
+        // Inform G4Transportation that the momentum might have changed due
+        // to scattering. We do this unconditionally to avoid the situation
+        // where the last step is done without MSC and G4Transportation reset
+        // the flag, for example when running without field.
+        fMomentumChanged = true;
+
         return totalGeometryStepLength;
       }
     }
```

Since commit 8d156a75988a99af0fdeab074851c4bace99b580 cmsdist is using the sources from https://github.com/Geant4/geant4. Looking into past discussions, we cannot include patches in such setup. Can the `geant4.spec` be changed to build from https://github.com/cms-externals/geant4/tree/cms/v11.1.2? Then I will open a PR in that repo to apply the above change.

cc @smuzaffar @civanch

**Comment by civanch** [comment]
@hahnjo , I just have a look and see the branch: https://github.com/cms-externals/geant4/tree/cms/v11.1.2

Please try to commit to this branch. @smuzaffar , please, confirm that this suggestion is correct.

**Comment by smuzaffar** [comment]
yes  , https://github.com/cms-externals/geant4/tree/cms/v11.1.2 is the correct branch to apply patches for Geant 11.1.2.

**Comment by smuzaffar** [comment]
@hahnjo , please open PR for  https://github.com/cms-externals/geant4/tree/cms/v11.1.2 . PR tests can be run without update geant4.spec ( but I will update it once PR tests are successful)

**Comment by hahnjo** [comment]
> please open PR for https://github.com/cms-externals/geant4/tree/cms/v11.1.2

https://github.com/cms-externals/geant4/pull/76

> PR tests can be run without update geant4.spec

Ah ok, good to know.

Further investigation suggests that CMS may be less affected than we initially thought because it always has a field manager attached, even if the field is zero. In that case, it's possible that simulation doesn't even trigger the problem - I will test based on the PR build.
