### ISSUE TITLE
Support for central man pages

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#90]
We need to have support for central man-pages, in particular for cms-git-utils, but also for scram and a few other tools we have. @davidlt @smuzaffar ideas where to put them? shall we have an extra line in `cmsset_default.{sh,csh}` which adds `MANPATH=%instroot/common/man:$MANPATH`?

**Comment by ktf** [comment]
@davidlt I think the new cms-common gets this done. Can you please check and install them at CERN and follow up with Christoph / Bockjoo about the various sites?

**Comment by davidlt** [comment]
@ktf , it is now available at CERN.

**Comment by davidlt** [comment]
It's now also done for `OSG` and `CVMFS`. Closing.
