### ISSUE TITLE
Migrate master from Geant4 11.1.2 to 11.2.1

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#9085]
The new Geant4 11.2.1 is validated by SIM group (https://indico.cern.ch/event/1394263/ ). It is shown that there are no technical problems and no difference in physics results. CPU/memory analysis shows minor advantage (CPU - 0-3% depending on WF, less memory - see https://nhoerman.web.cern.ch/nhoerman/cms_simulation/olsky-05/Summary_MinBias_TTbar_SMS-T1tttt_ZEE_SIM_CMSSW_14_1_G4VECGEOM_8_thread_run-3_FullSim.html ).

We propose switch Geant4 master to variant tested in G4VECGEOM branch, which includes Geant4 itself and datasets  G4EMLOW-8.5, G4ABLA-3.3, G4INCL-1.2.

We expect regular validation within 14_1_0_pre2 without creation of a parallel IB and without extra validation campaign.

**Comment by smuzaffar** [comment]
> The new Geant4 11.2.1 is validated by SIM group (https://indico.cern.ch/event/1394263/ )

@civanch , this sim validation was done based on 14.0.G4Vecgeom IBs ... right?

> We expect regular validation within 14_1_0_pre2 without creation of a parallel IB and without extra validation campaign.

Are you suggesting to update Geant4 11.2.1 directly in 14.1.X master IB without the need of CMSSW_14_1_0_pre2_G4VECGEOM release and its validation?

**Comment by civanch** [comment]
@smuzaffar , we make validation on top of 14_1_X_G4VECGEOM branch.

Because we do not see a change on level of our tests, we propose to include 11.2.1 into 14_1_X master and validate with 14_1_0_pre2 without creation extra IB. We do not expect full regressing but this release of Geant4 is really technical.

**Comment by smuzaffar** [comment]
> we propose to include 11.2.1 into 14_1_X master and validate with 14_1_0_pre2 without creation extra IB.

@civanch , "without creation extra IB" you mean extrra/special CMSSW_14_1_0_pre2_G4VECGEOM release. .... right?
So if I understand correctly, we want to update Geant4 in 14.1.X master from current geant4 version `11.1.2` to `11.2.1` and just build 14.1.0.pre2 with it and validate it ....  right?

**Comment by civanch** [comment]
@smuzaffar , yes, exactly.
