### ISSUE TITLE
Update the ROOT v6.30 patch 

### ISSUE THREAD

**Issue by anigamova** [cms-sw/cmsdist#9160]
The RooFit developers updated the v6-30-00-patches branch essential to release a new version of [Combine](https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/tree/main) with ROOT v6.30. Can we please get the following commit [`v6-30-00-patches/85f0fd973b2` ](https://github.com/root-project/root/commit/dcf4d2a31a3d92ed40860df06499926c44a99668) picked up for the CMSSW_14_1_X? Thanks!

**Comment by makortel** [comment]
Just to make sure, is 14_1_X enough? I.e. there is no need to have the change in 14_0_X?

**Comment by anigamova** [comment]
yes it is enough, we'll recommend to use CMSSW_14_1_X with the new combine release, thanks!

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/9162 updates root 6.30 for CMSSW_14_1_X. @makortel, to test it fully for all archs, I think we should wait for 14.1.0.pre3 (to be build tomorrow) before updating root
