### ISSUE TITLE
new cms-data RecoTracker-LSTCore repository is needed

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#9202]
tracking is going to submit a PR soon to cms-sw/cmssw introducing a new package RecoTracker/LSTCore. It needs a related place to keep initialization/setup files.

It seems more practical to get a new repository for these files; in cms-data RecoTracker-LSTCore

In case a sneak preview is needed, the files will come from https://github.com/SegmentLinking/TrackLooper/tree/master/data. An empty repository may be easier to start.

@VourMa @ariostas
@cms-sw/reconstruction-l2

**Comment by slava77** [comment]
type tracking

**Comment by slava77** [comment]
ping

**Comment by smuzaffar** [comment]
@slava77 , one can request a new data repo by opening cms-sw/cmssw issue with title `Create repository Subsystem/PackageName` and once issue is fully signed then bot will create the data repo. But this only works for data repos for which we have a cmssw package. If `RecoTracker/LSTCore` is an acceptable package name then I can update bot to add it under @cms-sw/reconstruction-l2  sothat bot can create the data repo

**Comment by smuzaffar** [comment]
@cms-sw/reconstruction-l2 , any objection on adding `RecoTracker/LSTCore` ( package not yet in cmssw though) under reconstruction ?

**Comment by mandrenguyen** [comment]
Sounds good

**Comment by smuzaffar** [comment]
repository created ( see https://github.com/cms-sw/cmssw/issues/45051 )
