### ISSUE TITLE
Migrate DD4hep external library to v1-29

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#9254]
In the recent version of DD4hep an important fix is introduced: order of instantiation of geometry objects is fixed to be stable, no random change of this order anymore. This fix may fix issue cms-sw/cmssw#40205 and guarantees the same order of instantiation of sensitive detectors.

It is possible that this update from v01-27-2 to v1-29 will keep regression - subject of tests. So, I would not exclude of update to this version of DD4hep directly in the master. If there will be problems we may first switch to G4VECGEOM branch.

The page of dd4hep:  https://github.com/AIDASoft/DD4hep/blob/master/doc/ReleaseNotes.md

**Comment by iarspider** [comment]
@civanch just to clarify: we should first try updating DD4Hep in CMSSW_14_1_X/master branch, but if the tests fail we should first merge it into CMSSW_14_1_X/g4 branch to test it in G4VEGGEOM IBs, right?

**Comment by civanch** [comment]
@iarspider , yes i suspect that updated library will work with the master.
