### ISSUE TITLE
Migrate master from Geant4 11.2.1 to 11.2.2

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#9294]
After installation of the new Geant4 patch 11.2.2 at G4VECGEOM and GEANT4 branches number of tests were performed for robustness and for calorimeter responses. Results are in a good statistical agreement. This confirms Geant4 statement that the new patch is pure technical.

We propose to test 11.2.2 for the master. Regression would not be expected but this change should not require any re-calibration including no change of parameters of PF. We also not see a reason for a special PdmV campaign. It is enough to test on level of pre-release.

**Comment by smuzaffar** [comment]
@iarspider , can you please open PR to update geant4 for 14.1.X master

**Comment by smuzaffar** [comment]
done via https://github.com/cms-sw/cmsdist/pull/9297
