### ISSUE TITLE
Making use of latest correctionlib

### ISSUE THREAD

**Issue by GuillelmoGomezCeballos** [cms-sw/cmsdist#9444]
Hello,

as reported here: https://cms-talk.web.cern.ch/t/correctionlib-not-working-on-cmssw-14-x/51248/3

The correctionlib version available in CMSSS_14_X is too old and it must be updated as soon as possible. There is at least one bug which is preventing to make it usable at all. Can it this be done?

Thanks a lot, Guillelmo

P.S. The bug is fixed in: https://github.com/cms-nanoAOD/correctionlib/commit/fa17477cc87752aba621ae9e97fcd843ba2ba5c9

**Comment by smuzaffar** [comment]
this has been fixed. next 14.1.X release should contain the latest version of correctionlib
