### ISSUE TITLE
New CMSSW_14_2_X release with ROOT 6.32.06 

### ISSUE THREAD

**Issue by anigamova** [cms-sw/cmsdist#9457]
Hi! We would like to test recent ROOT developments in Combine, could you please release a stable CMSSW_14_2_X build with ROOT 6.32.06? thanks!

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , if no objections that I can trigger the build of CMSSW_14_2_0_pre2_ROOT632 which should be identical CMSSW_14_2_0_pre2 but using the root 6.32 (only for el8_amd64_gcc12)

**Comment by smuzaffar** [comment]
I have started the build here https://github.com/cms-sw/cmssw/issues/46294

**Comment by smuzaffar** [comment]
`CMSSW_14_2_0_pre2_ROOT632` for `el8_amd64_gcc12` is available now

**Comment by anigamova** [comment]
nice, thanks a lot!
