### ISSUE TITLE
Request for a new external: eigen

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmsdist#989]
I would like to ask to build and distribute "eigen" as external in CMSSW

site
http://eigen.tuxfamily.org/index.php?title=Main_Page
version tested in CMSSW_7_2_X
http://bitbucket.org/eigen/eigen/get/3.2.2.tar.gz

eigen is header only

**Comment by bendavid** [comment]
Probably important are the notes here on "Using Eigen in a multithreaded application"
http://eigen.tuxfamily.org/dox/TopicMultiThreading.html

**Comment by VinInn** [comment]
definitively we do not won't eigen (or any other external) to use OpenMP behind our back.
This is a issue that will come more and more.
let's use -DEIGEN_DONT_PARALLELIZE for the time being even (if NOT using -fopenmp should be enough)

In the long term we will need to understand how to support parallel algorithms in externals with TBB

**Comment by bendavid** [comment]
Yes, I think we also need to make sure the " Eigen::initParallel()" call gets inserted in the right place in the framework.

**Comment by VinInn** [comment]
No. not for the time being.
we do not want Eigen to go parallel by its own. I manage to crash a node mixing framework and openMP...

**Comment by bendavid** [comment]
Hi Vincenzo,
Maybe I misunderstood the page, but I think that initParallel() is meant when the REST of the application is multithreaded, even if Eigen is not.  (I suppose it takes care of some non-thread-safe initialization which must happen before the library can be used and which would otherwise be triggered automatically at first use.)

**Comment by VinInn** [comment]
Sorry @bendavid, you are fully right...
we need to call `Eigen::initParallel()` in the main or earlier.
 @Dr15Jones, could you please have a look? thanks

**Comment by ghost** [comment]
@VinInn I am looking into this.
I should have a spec soon.

**Comment by smuzaffar** [comment]
I already have the spec and testing it now. Hopefully I will include in 
14h00 IB.

**Comment by smuzaffar** [comment]
this is done here #992 . It basically copies Eigen directory under include and set CPPDEFINES flag EIGEN_DONT_PARALLELIZE. IT should be available in 14h00 72X IB. One can use it by adding

```
<use name="eigen"/>
```

in the BuildFile.xml

**Comment by VinInn** [comment]
thanks, will verify in the evening

**Comment by Dr15Jones** [comment]
Just call `Eigen::initParallel` from your module's constructor. That will occur on the main thread and will happen before any calls to any other Eigen functions would happen on a different thread.
